\ X11 interface

Module X11

also DOS

library libX11 libX11.so.6
library libXext libXext.so.6 \ depends libX11

base @ hex

' noop alias has-utf8
' noop alias has-png
' noop alias has-xft

legacy off

libX11 XGetModifierMapping int (int) XGetModifierMapping     ( dpy -- modmap )
libX11 XNewModifiermap int (int) XNewModifiermap ( maxkeys -- modmap )
libX11 XInitImage int (int) XInitImage      ( image -- status )
libX11 XOpenDisplay int (int) XOpenDisplay    ( name -- dpy )
libX11 XDisplayName int (int) XDisplayName    ( string -- string )
libX11 XKeysymToString int (int) XKeysymToString ( keysym -- string )
libX11 XGContextFromGC int (int) XGContextFromGC ( gc -- gcontext )
libX11 XStringToKeysym int (int) XStringToKeysym ( string -- keysym )
libX11 XMaxRequestSize int (int) XMaxRequestSize ( dpy -- n )
libX11 XExtendedMaxRequestSize int (int) XExtendedMaxRequestSize ( dpy -- n )
libX11 XResourceManagerString int (int) XResourceManagerString  ( dpy -- string )
libX11 XScreenResourceString int (int) XScreenResourceString   ( screen -- string )
libX11 XDisplayMotionBufferSize int (int) XDisplayMotionBufferSize        ( dpy -- u )
libX11 XVisualIDFromVisual int (int) XVisualIDFromVisual     ( visual -- visualID )
libX11 XLockDisplay int (int) XLockDisplay    ( dpy -- r )
libX11 XUnlockDisplay int (int) XUnlockDisplay  ( dpy -- r )
libX11 XAddExtension int (int) XAddExtension   ( dpy -- extcodes )
libX11 XEHeadOfExtensionList int (int) XEHeadOfExtensionList   ( object -- extdata** )
libX11 XDefaultRootWindow int (int) XDefaultRootWindow      ( dpy -- window )
libX11 XRootWindowOfScreen int (int) XRootWindowOfScreen     ( screen -- window )
libX11 XDefaultVisualOfScreen int (int) XDefaultVisualOfScreen  ( screen -- visual )
libX11 XDefaultGCOfScreen int (int) XDefaultGCOfScreen      ( screen -- gc )
libX11 XBlackPixelOfScreen int (int) XBlackPixelOfScreen     ( screen -- u )
libX11 XWhitePixelOfScreen int (int) XWhitePixelOfScreen     ( screen -- u )
libX11 XNextRequest int (int) XNextRequest    ( dpy -- u )
libX11 XLastKnownRequestProcessed int (int) XLastKnownRequestProcessed      ( dpy -- u )
libX11 XServerVendor int (int) XServerVendor   ( dpy -- string )
libX11 XDisplayString int (int) XDisplayString  ( dpy -- string )
libX11 XDefaultColormapOfScreen int (int) XDefaultColormapOfScreen        ( screen -- colormap )
libX11 XDisplayOfScreen int (int) XDisplayOfScreen        ( screen -- dpy )
libX11 XDefaultScreenOfDisplay int (int) XDefaultScreenOfDisplay ( dpy -- screen )
libX11 XEventMaskOfScreen int (int) XEventMaskOfScreen      ( screen -- mask )
libX11 XScreenNumberOfScreen int (int) XScreenNumberOfScreen   ( screen -- n )
libX11 XSetErrorHandler int (int) XSetErrorHandler        ( handler -- errorhandler )
libX11 XSetIOErrorHandler int (int) XSetIOErrorHandler      ( handler -- ioerrorhandler )
libX11 XFreeStringList int (int) XFreeStringList ( list -- r )
libX11 XActivateScreenSaver int (int) XActivateScreenSaver    ( dpy -- r )
libX11 XAutoRepeatOff int (int) XAutoRepeatOff  ( dpy -- r )
libX11 XAutoRepeatOn int (int) XAutoRepeatOn   ( dpy -- r )
libX11 XBitmapBitOrder int (int) XBitmapBitOrder ( dpy -- n )
libX11 XBitmapPad int (int) XBitmapPad      ( dpy -- n )
libX11 XBitmapUnit int (int) XBitmapUnit     ( dpy -- n )
libX11 XCellsOfScreen int (int) XCellsOfScreen  ( screen -- n )
libX11 XCloseDisplay int (int) XCloseDisplay   ( dpy -- r )
libX11 XConnectionNumber int (int) XConnectionNumber       ( dpy -- r )
libX11 XDefaultDepthOfScreen int (int) XDefaultDepthOfScreen   ( screen -- i )
libX11 XDefaultScreen int (int) XDefaultScreen  ( dpy -- i )
libX11 XDoesBackingStore int (int) XDoesBackingStore       ( screen -- i )
libX11 XDoesSaveUnders int (int) XDoesSaveUnders ( screen -- flag )
libX11 XDisableAccessControl int (int) XDisableAccessControl   ( dpy -- r )
libX11 XEnableAccessControl int (int) XEnableAccessControl    ( dpy -- r )
libX11 XFlush int (int) XFlush  ( dpy -- r )
libX11 XFree int (int) XFree   ( data -- r )
libX11 XFreeExtensionList int (int) XFreeExtensionList      ( list -- r )
libX11 XFreeFontNames int (int) XFreeFontNames  ( list -- r )
libX11 XFreeFontPath int (int) XFreeFontPath   ( list -- r )
libX11 XFreeModifiermap int (int) XFreeModifiermap        ( modmap -- r )
libX11 XGrabServer int (int) XGrabServer     ( dpy -- r )
libX11 XHeightMMOfScreen int (int) XHeightMMOfScreen       ( screen -- n )
libX11 XHeightOfScreen int (int) XHeightOfScreen ( screen -- n )
libX11 XImageByteOrder int (int) XImageByteOrder ( dpy -- n )
libX11 XMaxCmapsOfScreen int (int) XMaxCmapsOfScreen       ( screen -- n )
libX11 XMinCmapsOfScreen int (int) XMinCmapsOfScreen       ( screen -- n )
libX11 XNoOp int (int) XNoOp   ( dpy -- r )
libX11 XPending int (int) XPending        ( dpy -- n )
libX11 XPlanesOfScreen int (int) XPlanesOfScreen ( screen -- n )
libX11 XProtocolRevision int (int) XProtocolRevision       ( dpy -- n )
libX11 XProtocolVersion int (int) XProtocolVersion        ( dpy -- n )
libX11 XQLength int (int) XQLength        ( dpy -- n )
libX11 XRefreshKeyboardMapping int (int) XRefreshKeyboardMapping ( event_map -- r )
libX11 XResetScreenSaver int (int) XResetScreenSaver       ( dpy -- r )
libX11 XScreenCount int (int) XScreenCount    ( dpy -- n )
libX11 XUngrabServer int (int) XUngrabServer   ( dpy -- r )
libX11 XVendorRelease int (int) XVendorRelease  ( dpy -- n )
libX11 XWidthMMOfScreen int (int) XWidthMMOfScreen        ( screen -- n )
libX11 XWidthOfScreen int (int) XWidthOfScreen  ( screen -- n )
libX11 XSetLocaleModifiers int (int) XSetLocaleModifiers     ( modifier_list -- string )
libX11 XCloseOM int (int) XCloseOM        ( om -- status )
libX11 XSetOMValues int (int) XSetOMValues    ( ...om -- string )
libX11 XGetOMValues int (int) XGetOMValues    ( ...om -- string )
libX11 XDisplayOfOM int (int) XDisplayOfOM    ( om -- dpy )
libX11 XLocaleOfOM int (int) XLocaleOfOM     ( om -- string )
libX11 XCreateOC int (int) XCreateOC       ( ...om -- XOC )
libX11 XDestroyOC int (int) XDestroyOC      ( oc -- r )
libX11 XOMOfOC int (int) XOMOfOC ( oc -- XOM )
libX11 XSetOCValues int (int) XSetOCValues    ( ...oc -- string )
libX11 XGetOCValues int (int) XGetOCValues    ( ...oc -- string )
libX11 XBaseFontNameListOfFontSet int (int) XBaseFontNameListOfFontSet       ( fontset -- string )
libX11 XLocaleOfFontSet int (int) XLocaleOfFontSet        ( fontset -- string )
libX11 XContextDependentDrawing int (int) XContextDependentDrawing        ( fontset -- flag )
libX11 XDirectionalDependentDrawing int (int) XDirectionalDependentDrawing    ( fontset -- flag )
libX11 XContextualDrawing int (int) XContextualDrawing      ( fontset -- flag )
libX11 XExtentsOfFontSet int (int) XExtentsOfFontSet       ( fontset -- fontsetextents )
libX11 XCloseIM int (int) XCloseIM        ( im -- status )
libX11 XDisplayOfIM int (int) XDisplayOfIM    ( im -- dpy )
libX11 XLocaleOfIM int (int) XLocaleOfIM     ( im -- string )
libX11 XCreateIC int (int) XCreateIC       ( im -- XIC )
libX11 XDestroyIC int (int) XDestroyIC      ( ic -- r )
libX11 XSetICFocus int (int) XSetICFocus     ( ic -- r )
libX11 XUnsetICFocus int (int) XUnsetICFocus   ( ic -- r )
libX11 XwcResetIC int (int) XwcResetIC      ( ic -- wstring )
libX11 XmbResetIC int (int) XmbResetIC      ( ic -- string )
libX11 XIMOfIC int (int) XIMOfIC ( ic -- XIM )
libX11 XDestroyRegion int (int) XDestroyRegion  ( reg -- r )
libX11 XEmptyRegion int (int) XEmptyRegion    ( reg -- r )
libX11 XwcFreeStringList int (int) XwcFreeStringList       ( list -- r )
libX11 Xpermalloc int (int) Xpermalloc      ( size -- addr )
libX11 XrmStringToQuark int (int) XrmStringToQuark        ( string -- quark )
libX11 XrmPermStringToQuark int (int) XrmPermStringToQuark    ( string -- quark )
libX11 XrmQuarkToString int (int) XrmQuarkToString        ( quark -- string )
libX11 XrmDestroyDatabase int (int) XrmDestroyDatabase      ( dbase -- r )
libX11 XrmGetDatabase int (int) XrmGetDatabase  ( dpy -- dbase )
libX11 XrmGetFileDatabase int (int) XrmGetFileDatabase      ( filename -- dbase )
libX11 XrmGetStringDatabase int (int) XrmGetStringDatabase    ( string -- dbase )
libX11 XrmLocaleOfDatabase int (int) XrmLocaleOfDatabase     ( dbase -- string )

libX11 XLoadQueryFont int int (int) XLoadQueryFont  ( dpy name -- fontstruct )
libX11 XAllocColor int int int (int) XAllocColor     ( color colormap dpy -- status )
libX11 XGetWindowAttributes int int int (int) XGetWindowAttributes    ( dpy win windows_attributes_r -- status )
libX11 XChangeWindowAttributes int int int int (int) XChangeWindowAttributes ( dpy win valuemask attributes -- r )
libX11 XGetErrorText int int int int (int) XGetErrorText   ( dpy code buffer_r length -- r )
libX11 XSupportsLocale (int) XSupportsLocale ( -- flag )
libX11 XGetVisualInfo int int int int (int) XGetVisualInfo  ( dpy vinfo_mask vinfo_templ nitems_r -- vinfo* )
libX11 XCreateColormap int int int int (int) XCreateColormap ( alloc visual w dpy -- colormap )
libX11 XOpenIM int int int int (int) XOpenIM ( dpy rdb res_name res_class -- XIM )
libX11 XGetIMValues_1 int int int int (ptr) XGetIMValues    ( im ... -- string )
libX11 XGetIMValues_2 int int int int int int (ptr) XGetIMValues    ( im ... -- string )
libX11 XGetIMValues_3 int int int int int int int int (ptr) XGetIMValues  ( im ... -- string )
libX11 XSetIMValues_1 int int int int (ptr) XSetIMValues    ( im ... -- string )
libX11 XSetIMValues_2 int int int int int int (ptr) XSetIMValues    ( im ... -- string )
libX11 XSetIMValues_3 int int int int int int int int (ptr) XSetIMValues    ( im ... -- string )
libX11 XVaCreateNestedList_1 int int int int (ptr) XVaCreateNestedList     ( ...unused -- vanestedlist )
libX11 XVaCreateNestedList_2 int int int int int int (ptr) XVaCreateNestedList     ( ...unused -- vanestedlist )
libX11 XVaCreateNestedList_3 int int int int int int int int (ptr) XVaCreateNestedList     ( ...unused -- vanestedlist )
libX11 XVaCreateNestedList_4 int int int int int int int int int int (ptr) XVaCreateNestedList     ( ...unused -- vanestedlist )
libX11 XCreateIC_1 int int int int (ptr) XCreateIC       ( im -- XIC )
libX11 XCreateIC_2 int int int int int int (ptr) XCreateIC       ( im -- XIC )
libX11 XCreateIC_3 int int int int int int int int (ptr) XCreateIC       ( im -- XIC )
libX11 XCreateIC_4 int int int int int int int int int int (ptr) XCreateIC       ( im -- XIC )
libX11 XCreateIC_5 int int int int int int int int int int int int (ptr) XCreateIC       ( im -- XIC )
libX11 XCreateGC int int int int (ptr) XCreateGC ( dpy d valuemask values -- gc )
libX11 XDestroyWindow int int (int) XDestroyWindow  ( dpy win -- r )
libX11 XKeycodeToKeysym int int int (int) XKeycodeToKeysym        ( dpy keycode index -- keysym )
libX11 XCreateFontSet int int int int int (int) XCreateFontSet  ( dpy base_font_name_list missing_charset_list missing-charset_count def_string -- fontset )
libX11 XFreeColors int int int int int (int) XFreeColors     ( dpy colormap pixels npixels planes -- r )

legacy on

previous

\ -1 libX11 _XPrivDisplay               _XPrivDisplay   ( -- addr )
\ -1 libX11 _Xdebug                       _Xdebug         ( -- addr )
2 libX11 XQueryFont                     XQueryFont      ( XID dpy -- fontstruct )
5 libX11 XGetMotionEvents               XGetMotionEvents        ( neventsr stop start w dpy -- timecoord )
3 libX11 XDeleteModifiermapEntry        XDeleteModifiermapEntry ( mod keycode modmap -- modmap )
3 libX11 XInsertModifiermapEntry        XInsertModifiermapEntry ( mod keycode modmap -- modmap )
A libX11 XCreateImage                   XCreateImage    ( b/line bmpad h w data offset format depth visual dpy -- image )
8 libX11 XGetImage                      XGetImage       ( format planemask h w y x d dpy -- image )
B libX11 XGetSubImage                   XGetSubImage    ( dy dx dimage format planemask h w y x d dpy -- image )
0 libX11 XrmInitialize                  XrmInitialize   ( -- r )
2 libX11 XFetchBytes                    XFetchBytes     ( nbytesr dpy -- buffer )
3 libX11 XFetchBuffer                   XFetchBuffer    ( buffer nbytesr dpy -- buffer )
2 libX11 XGetAtomName                   XGetAtomName    ( atom dpy -- name )
4 libX11 XGetAtomNames                  XGetAtomNames   ( namesr count atoms dpy -- status )
3 libX11 XGetDefault                    XGetDefault     ( option program dpy --  string )
3 libX11 XInternAtom                    XInternAtom     ( flag atomname dpy -- atom )
5 libX11 XInternAtoms                   XInternAtoms    ( atoms flag count names dpy -- status )
2 libX11 XCopyColormapAndFree           XCopyColormapAndFree    ( colormap dpy -- colormap )
7 libX11 XCreatePixmapCursor            XCreatePixmapCursor     ( y x bgcol fgcol mask source dpy -- cursor )
7 libX11 XCreateGlyphCursor             XCreateGlyphCursor      ( bgcol fgcol maskc sourcec maskfont sourcefont dpy -- cursor )
2 libX11 XCreateFontCursor              XCreateFontCursor       ( shape dpy -- cursor )
2 libX11 XLoadFont                      XLoadFont       ( name dpy -- font )
2 libX11 XFlushGC                       XFlushGC        ( gc dpy -- r )
5 libX11 XCreatePixmap                  XCreatePixmap   ( depth h w d dpy -- pixmap )
5 libX11 XCreateBitmapFromData          XCreateBitmapFromData   ( h w data d dpy -- pixmap )
8 libX11 XCreatePixmapFromBitmapData    XCreatePixmapFromBitmapData     ( depth bg fg h w data d dpy -- pixmap )
9 libX11 XCreateSimpleWindow            XCreateSimpleWindow     ( bg border bwidth h w y x parent dpy -- window )
2 libX11 XGetSelectionOwner             XGetSelectionOwner      ( atom dpy -- window )
( +) C libX11 XCreateWindow                  XCreateWindow   ( attribs valuemask visual class depth borderwidth h w y x parent dpy -- window )
3 libX11 XListInstalledColormaps        XListInstalledColormaps ( num_r w dpy -- colormap* )
4 libX11 XListFonts                     XListFonts      ( actual_count_r maxnames pattern dpy -- char** )
5 libX11 XListFontsWithInfo             XListFontsWithInfo      ( info_r count_r maxnames pattern dpy -- char** )
2 libX11 XGetFontPath                   XGetFontPath    ( npaths_r dpy -- char** )
2 libX11 XListExtensions                XListExtensions ( nextensions_r dpy -- char** )
3 libX11 XListProperties                XListProperties ( num_prop_r w dpy -- atom* )
3 libX11 XListHosts                     XListHosts      ( status_r nhosts_r dpy -- hostaddr* )
2 libX11 XLookupKeysym                  XLookupKeysym   ( index key_event -- keysym )
4 libX11 XGetKeyboardMapping            XGetKeyboardMapping     ( keysym/keycode_r keycode_c first_kc dpy -- keysym* )
0 libX11 XInitThreads                   XInitThreads    ( -- status )
2 libX11 XInitExtension                 XInitExtension  ( name dpy -- extcodes )
2 libX11 XFindOnExtensionList           XFindOnExtensionList    ( number structure -- extdata )
2 libX11 XRootWindow                    XRootWindow     ( screen_nr dpy -- window )
2 libX11 XDefaultVisual                 XDefaultVisual  ( screen_nr dpy -- visual )
2 libX11 XDefaultGC                     XDefaultGC      ( screen_nr dpy -- gc )
2 libX11 XBlackPixel                    XBlackPixel     ( screen_nr dpy -- u )
2 libX11 XWhitePixel                    XWhitePixel     ( screen_nr dpy -- u )
0 libX11 XAllPlanes                     XAllPlanes      ( -- u )
2 libX11 XDefaultColormap               XDefaultColormap        ( screen_nr dpy -- colormap )
2 libX11 XScreenOfDisplay               XScreenOfDisplay        ( screen_nr dpy -- screen )
2 libX11 XListPixmapFormats             XListPixmapFormats      ( count_r dpy -- pixmapformatvalues )
3 libX11 XListDepths                    XListDepths     ( count_r screen_nr dpy -- int* )
5 libX11 XReconfigureWMWindow           XReconfigureWMWindow    ( changes mask screen_nr w dpy -- status )
4 libX11 XGetWMProtocols                XGetWMProtocols ( count_r protocols_r w dpy -- status )
4 libX11 XSetWMProtocols                XSetWMProtocols ( count protocols w dpy -- status )
3 libX11 XIconifyWindow                 XIconifyWindow  ( screen_nr w dpy -- status )
3 libX11 XWithdrawWindow                XWithdrawWindow ( screen_nr w dpy -- status )
4 libX11 XGetCommand                    XGetCommand     ( argc_r argv_r w dpy -- status )
4 libX11 XGetWMColormapWindows          XGetWMColormapWindows   ( count_r windows_r w dpy -- status )
4 libX11 XSetWMColormapWindows          XSetWMColormapWindows   ( count colormap_windows w dpy -- status )
3 libX11 XSetTransientForHint           XSetTransientForHint    ( propw w dpy -- r )
2 libX11 XAddHost                       XAddHost        ( host dpy -- r )
3 libX11 XAddHosts                      XAddHosts       ( num hosts dpy -- r )
2 libX11 XAddToExtensionList            XAddToExtensionList     ( extdata structure -- r )
2 libX11 XAddToSaveSet                  XAddToSaveSet   ( w dpy -- r )
7 libX11 XAllocColorCells               XAllocColorCells        ( pixels pixels_r planes planemask_r contig colormap dpy -- status )
B libX11 XAllocColorPlanes              XAllocColorPlanes       ( bmask_r gmask_r rmask_r blues greens reds colors pixels_r contig colormap dpy -- status )
5 libX11 XAllocNamedColor               XAllocNamedColor        ( exact_def_r screen_def_r cname colormap dpy -- status )
3 libX11 XAllowEvents                   XAllowEvents    ( time event_mode dpy -- r )
2 libX11 XBell                          XBell   ( percent dpy -- r )
4 libX11 XChangeActivePointerGrab       XChangeActivePointerGrab        ( time cursor event_mask dpy -- r )
4 libX11 XChangeGC                      XChangeGC       ( values valuemask gc dpy -- r )
3 libX11 XChangeKeyboardControl         XChangeKeyboardControl  ( values valuemask dpy -- r )
5 libX11 XChangeKeyboardMapping         XChangeKeyboardMapping  ( num_codes keysyms keysyms/keycode first_kc dpy -- r )
6 libX11 XChangePointerControl          XChangePointerControl   ( threshold accel_denom accel_num do_thres do_accel dpy -- r )
( +) 8 libX11 XChangeProperty                XChangeProperty ( elements data mode format type property w dpy -- r )
3 libX11 XChangeSaveSet                 XChangeSaveSet  ( change_mode w dpy -- r )
4 libX11 XCheckIfEvent                  XCheckIfEvent   ( arg predicate event_return dpy -- flag )
3 libX11 XCheckMaskEvent                XCheckMaskEvent ( event_r event_mask dpy -- flag )
3 libX11 XCheckTypedEvent               XCheckTypedEvent        ( event_r event_type dpy -- flag )
4 libX11 XCheckTypedWindowEvent         XCheckTypedWindowEvent  ( event_r event_type w dpy -- flag )
4 libX11 XCheckWindowEvent              XCheckWindowEvent       ( event_r event_mask w dpy -- flag )
3 libX11 XCirculateSubwindows           XCirculateSubwindows    ( direction w dpy -- r )
2 libX11 XCirculateSubwindowsDown       XCirculateSubwindowsDown        ( w dpy -- r )
2 libX11 XCirculateSubwindowsUp         XCirculateSubwindowsUp  ( w dpy -- r )
7 libX11 XClearArea                     XClearArea      ( exposures h w y x w dpy -- r )
2 libX11 XClearWindow                   XClearWindow    ( w dpy -- r )
4 libX11 XConfigureWindow               XConfigureWindow        ( values value_mask w dpy -- r )
6 libX11 XConvertSelection              XConvertSelection       ( time requestor property target selection dpy -- r )
A libX11 XCopyArea                      XCopyArea       ( dy dx h w y x gc dest src dpy -- r )
4 libX11 XCopyGC                        XCopyGC ( dest valuemask src dpy -- r )
B libX11 XCopyPlane                     XCopyPlane      ( plane dy dx h w y x gc dest src dpy -- r )
2 libX11 XDefaultDepth                  XDefaultDepth   ( screen_nr dpy -- i )
3 libX11 XDefineCursor                  XDefineCursor   ( cursor w dpy -- r )
3 libX11 XDeleteProperty                XDeleteProperty ( atom w dpy -- r )
2 libX11 XDestroySubwindows             XDestroySubwindows      ( w dpy -- r )
2 libX11 XDisplayCells                  XDisplayCells   ( screen_nr dpy -- i )
2 libX11 XDisplayHeight                 XDisplayHeight  ( screen_nr dpy -- i )
2 libX11 XDisplayHeightMM               XDisplayHeightMM        ( screen_nr dpy -- i )
3 libX11 XDisplayKeycodes               XDisplayKeycodes        ( min_keycodes_r max_keycodes_r dpy -- r )
2 libX11 XDisplayPlanes                 XDisplayPlanes  ( screen_nr dpy -- i )
2 libX11 XDisplayWidth                  XDisplayWidth   ( screen_nr dpy -- i )
2 libX11 XDisplayWidthMM                XDisplayWidthMM ( screen_nr dpy -- i )
9 libX11 XDrawArc                       XDrawArc        ( angle2 angle1 h w y x gc d dpy -- r )
5 libX11 XDrawArcs                      XDrawArcs       ( narcs arcs gc d dpy -- r )
7 libX11 XDrawImageString               XDrawImageString        ( length string y x gc d dpy -- r )
7 libX11 XDrawImageString16             XDrawImageString16      ( length string y x gc d dpy -- r )
7 libX11 XDrawLine                      XDrawLine       ( y2 y1 x2 x1 gc d dpy -- r )
6 libX11 XDrawLines                     XDrawLines      ( mode npoints points gc d dpy -- r )
5 libX11 XDrawPoint                     XDrawPoint      ( y x gc d dpy -- r )
6 libX11 XDrawPoints                    XDrawPoints     ( mode npoints point gc d dpy -- r )
7 libX11 XDrawRectangle                 XDrawRectangle  ( h w y x gc d dpy -- r )
5 libX11 XDrawRectangles                XDrawRectangles ( nrects rects gc d dpy -- r )
5 libX11 XDrawSegments                  XDrawSegments   ( nsegments segments gc d dpy -- r )
7 libX11 XDrawString                    XDrawString     ( length string y x gc d dpy -- r )
7 libX11 XDrawString16                  XDrawString16   ( length string y x gc d dpy -- r )
7 libX11 XDrawText                      XDrawText       ( nitems items y x gc d dpy -- r )
7 libX11 XDrawText16                    XDrawText16     ( nitems items y x gc d dpy -- r )
2 libX11 XEventsQueued                  XEventsQueued   ( mode dpy -- i )
3 libX11 XFetchName                     XFetchName      ( name_r w dpy -- status )
9 libX11 XFillArc                       XFillArc        ( angle2 angle1 h w y x gc d dpy -- r )
5 libX11 XFillArcs                      XFillArcs       ( narcs arcs gc d dpy -- r )
7 libX11 XFillPolygon                   XFillPolygon    ( mode shape npoints points gc d dpy -- r )
7 libX11 XFillRectangle                 XFillRectangle  ( h w y x gc d dpy -- r )
5 libX11 XFillRectangles                XFillRectangles ( nrects rects gc d dpy -- r )
2 libX11 XForceScreenSaver              XForceScreenSaver       ( mode dpy -- r )
2 libX11 XFreeColormap                  XFreeColormap   ( colormap dpy -- r )
2 libX11 XFreeCursor                    XFreeCursor     ( cursor dpy -- r )
2 libX11 XFreeFont                      XFreeFont       ( fontstruct dpy -- r )
3 libX11 XFreeFontInfo                  XFreeFontInfo   ( actual_count free_info names -- r )
2 libX11 XFreeGC                        XFreeGC ( gc dpy -- r )
2 libX11 XFreePixmap                    XFreePixmap     ( pixmap dpy -- r )
D libX11 XGeometry                      XGeometry       ( hr wr yr xr yadder xadder fh fw bw default_pos pos screen dpy -- n )
6 libX11 XGetErrorDatabaseText          XGetErrorDatabaseText   ( int buffer_r default_string message name dpy -- r )
3 libX11 XGetFontProperty               XGetFontProperty        ( value_r atom fontstruct -- flag )
4 libX11 XGetGCValues                   XGetGCValues    ( values_r valuemask gc dpy -- status )
9 libX11 XGetGeometry                   XGetGeometry    ( depth_r borderw_r h_r w_r y_r x_r root_r d dpy -- status )
3 libX11 XGetIconName                   XGetIconName    ( icon_name-r w dpy -- status )
3 libX11 XGetInputFocus                 XGetInputFocus  ( revert_to_r focus_r dpy -- r )
2 libX11 XGetKeyboardControl            XGetKeyboardControl     ( values_r dpy -- r )
4 libX11 XGetPointerControl             XGetPointerControl      ( threshold_r accel_denom_r accel_num_r dpy -- r )
3 libX11 XGetPointerMapping             XGetPointerMapping      ( nmap map_r dpy -- n )
5 libX11 XGetScreenSaver                XGetScreenSaver ( allow_exposures_r prefer_blanking_r interval_r timeout_r dpy -- r )
3 libX11 XGetTransientForHint           XGetTransientForHint    ( prop_w_r w dpy -- status )
C libX11 XGetWindowProperty             XGetWindowProperty      ( prop_r bytes_after_r nitems_r actual_format_r actual_typer req_type delete length offset property w dpy -- n )
9 libX11 XGrabButton                    XGrabButton     ( cursor confine_to keyboard_mode pointer_mode owner_events grab_window modifiers button dpy -- r )
8 libX11 XGrabKey                       XGrabKey        ( keyboard_mode pointer_mode owner_events grab_events grab_window modifiers keycode dpy -- r )
6 libX11 XGrabKeyboard                  XGrabKeyboard   ( time keyboard_mode pointer_mode owner_events grab_window dpy -- n )
9 libX11 XGrabPointer                   XGrabPointer    ( time cursor confine_to keyboard_mode pointer_mode owner_events grab_window dpy -- n )
4 libX11 XIfEvent                       XIfEvent        ( arg predicate event_r dpy -- r )
2 libX11 XInstallColormap               XInstallColormap        ( colormap dpy -- r )
2 libX11 XKeysymToKeycode               XKeysymToKeycode        ( keysym dpy -- keycode )
2 libX11 XKillClient                    XKillClient     ( resource dpy -- r )
\ 1 libX11 XLastKnownRequestProcessed   XLastKnownRequestProcessed      ( dpy -- u )
5 libX11 XLookupColor                   XLookupColor    ( screen_def_r exact_def_r color_name colormap dpy -- status )
2 libX11 XLowerWindow                   XLowerWindow    ( w dpy -- r )
2 libX11 XMapRaised                     XMapRaised      ( w dpy -- r )
2 libX11 XMapSubwindows                 XMapSubwindows  ( w dpy -- r )
2 libX11 XMapWindow                     XMapWindow      ( w dpy -- r )
3 libX11 XMaskEvent                     XMaskEvent      ( event_r event_mask dpy -- r )
6 libX11 XMoveResizeWindow              XMoveResizeWindow       ( h w y x w dpy -- r )
4 libX11 XMoveWindow                    XMoveWindow     ( y x w dpy -- r )
2 libX11 XNextEvent                     XNextEvent      ( event_r dpy -- r )
4 libX11 XParseColor                    XParseColor     ( exact_def_r spec colormap dpy -- status )
5 libX11 XParseGeometry                 XParseGeometry  ( h_r w_r y_r x_r parsestring -- n )
2 libX11 XPeekEvent                     XPeekEvent      ( event_r dpy -- r )
4 libX11 XPeekIfEvent                   XPeekIfEvent    ( arg predicate event_r dpy -- r )
2 libX11 XPutBackEvent                  XPutBackEvent   ( event dpy -- r )
A libX11 XPutImage                      XPutImage       ( h w d_y d_x s_y s_x image gc d dpy -- r )
6 libX11 XQueryBestCursor               XQueryBestCursor        ( h_r w_r h w d dpy -- status )
7 libX11 XQueryBestSize                 XQueryBestSize  ( h_r w_r h w which_screen class dpy -- status )
6 libX11 XQueryBestStipple              XQueryBestStipple       ( h_r w_r h w which_screen dpy -- status )
6 libX11 XQueryBestTile                 XQueryBestTile  ( h_r w_r h w which_screen dpy -- status )
3 libX11 XQueryColor                    XQueryColor     ( def_in_out colormap dpy -- r )
4 libX11 XQueryColors                   XQueryColors    ( ncolors defs_in_out colormap dpy -- r )
5 libX11 XQueryExtension                XQueryExtension ( first_error_r first_event_r major_opcode_r name dpy -- flag )
2 libX11 XQueryKeymap                   XQueryKeymap    ( keys_r dpy -- r )
9 libX11 XQueryPointer                  XQueryPointer   ( mask_r win_y_r win_x_r root_y_r root_x_r child_r root_r w dpy -- flag )
8 libX11 XQueryTextExtents              XQueryTextExtents       ( overall_r font_descent_r font_ascent_r direction_r nchars string font_id dpy -- r )
8 libX11 XQueryTextExtents16            XQueryTextExtents16     ( overall_r font_descent_r font_ascent_r direction_r nchars string font_id dpy -- r )
6 libX11 XQueryTree                     XQueryTree      ( nchildren_r children_r parent_r root_r w dpy -- status )
2 libX11 XRaiseWindow                   XRaiseWindow    ( w dpy -- r )
8 libX11 XReadBitmapFile                XReadBitmapFile ( y_hot_r x_hot_r bitmap_r height_r width_r filename d dpy -- n )
6 libX11 XReadBitmapFileData            XReadBitmapFileData     ( y_hot_r x_hot_r bitmap_r height_r width_r filename -- n )
6 libX11 XRebindKeysym                  XRebindKeysym   ( bytes_string string mod_count list keysym dpy -- r )
4 libX11 XRecolorCursor                 XRecolorCursor  ( bg fg cursor dpy -- r )
2 libX11 XRemoveFromSaveSet             XRemoveFromSaveSet      ( w dpy -- r )
2 libX11 XRemoveHost                    XRemoveHost     ( host dpy -- r )
3 libX11 XRemoveHosts                   XRemoveHosts    ( num_hosts hosts dpy -- r )
5 libX11 XReparentWindow                XReparentWindow ( y x parent w dpy -- r )
4 libX11 XResizeWindow                  XResizeWindow   ( h w w dpy -- r )
3 libX11 XRestackWindows                XRestackWindows ( nwindows windows dpy -- r )
2 libX11 XRotateBuffers                 XRotateBuffers  ( rotate dpy -- r )
5 libX11 XRotateWindowProperties        XRotateWindowProperties ( npositions num_prop properties w dpy -- r )
3 libX11 XSelectInput                   XSelectInput    ( event_mask w dpy -- r )
5 libX11 XSendEvent                     XSendEvent      ( event_send event_mask propagate w dpy -- status )
2 libX11 XSetAccessControl              XSetAccessControl       ( mode dpy -- r )
3 libX11 XSetArcMode                    XSetArcMode     ( arc_mode gc dpy -- r )
3 libX11 XSetBackground                 XSetBackground  ( background gc dpy -- r )
3 libX11 XSetClipMask                   XSetClipMask    ( pixmap gc dpy -- r )
4 libX11 XSetClipOrigin                 XSetClipOrigin  ( clip_y_orig clip_x_orig gc dpy -- r )
7 libX11 XSetClipRectangles             XSetClipRectangles      ( ordering n rectangles clip_y_orig clip_x_orig gc dpy -- r )
2 libX11 XSetCloseDownMode              XSetCloseDownMode       ( close_mode dpy -- r )
4 libX11 XSetCommand                    XSetCommand     ( argc argv w dpy -- r )
5 libX11 XSetDashes                     XSetDashes      ( n dash_list dash_ofset gc dpy -- r )
3 libX11 XSetFillRule                   XSetFillRule    ( fill_rule gc dpy -- r )
3 libX11 XSetFillStyle                  XSetFillStyle   ( fill_style gc dpy -- r )
3 libX11 XSetFont                       XSetFont        ( font gc dpy -- r )
3 libX11 XSetFontPath                   XSetFontPath    ( ndirs directories dpy -- r )
3 libX11 XSetForeground                 XSetForeground  ( fg gc dpy -- r )
3 libX11 XSetFunction                   XSetFunction    ( function gc dpy -- r )
3 libX11 XSetGraphicsExposures          XSetGraphicsExposures   ( graphics_exposures gc dpy -- r )
3 libX11 XSetIconName                   XSetIconName    ( icon_name w dpy -- r )
4 libX11 XSetInputFocus                 XSetInputFocus  ( time revert_to focus dpy -- r )
6 libX11 XSetLineAttributes             XSetLineAttributes      ( join_style cap_style line_style line_width gc dpy -- r )
2 libX11 XSetModifierMapping            XSetModifierMapping     ( modmap dpy -- n )
3 libX11 XSetPlaneMask                  XSetPlaneMask   ( plane_mask gc dpy -- r )
3 libX11 XSetPointerMapping             XSetPointerMapping      ( nmap map dpy -- n )
5 libX11 XSetScreenSaver                XSetScreenSaver ( allow_exposures prefer_blanking interval timeout dpy -- r )
4 libX11 XSetSelectionOwner             XSetSelectionOwner      ( time owner selection dpy -- r )
6 libX11 XSetState                      XSetState       ( plane_mask function bg fg gc dpy -- r )
3 libX11 XSetStipple                    XSetStipple     ( stripple gc dpy -- r )
3 libX11 XSetSubwindowMode              XSetSubwindowMode       ( subwindow_mode gc dpy -- r )
4 libX11 XSetTSOrigin                   XSetTSOrigin    ( ts_y_orig ts_x_orig gc dpy -- r )
3 libX11 XSetTile                       XSetTile        ( tile gc dpy -- )
3 libX11 XSetWindowBackground           XSetWindowBackground    ( bg_pixel w dpy -- )
3 libX11 XSetWindowBackgroundPixmap     XSetWindowBackgroundPixmap      ( bg_pixmap w dpy -- r )
3 libX11 XSetWindowBorder               XSetWindowBorder        ( border_pixel w dpy -- r )
3 libX11 XSetWindowBorderPixmap         XSetWindowBorderPixmap  ( border_pixmap w dpy -- r )
3 libX11 XSetWindowBorderWidth          XSetWindowBorderWidth   ( width w dpy -- r )
3 libX11 XSetWindowColormap             XSetWindowColormap      ( colormap w dpy -- r )
4 libX11 XStoreBuffer                   XStoreBuffer    ( buffer nbytes bytes dpy -- r )
3 libX11 XStoreBytes                    XStoreBytes     ( nbytes bytes dpy -- r )
3 libX11 XStoreColor                    XStoreColor     ( color colormap dpy -- r )
4 libX11 XStoreColors                   XStoreColors    ( ncolors color colormap dpy -- r )
3 libX11 XStoreName                     XStoreName      ( window_name w dpy -- r )
5 libX11 XStoreNamedColor               XStoreNamedColor        ( flags pixel color colormap dpy -- r )
2 libX11 XSync                          XSync   ( discard dpy -- r )
7 libX11 XTextExtents                   XTextExtents    ( overall_r font_descent_r font_ascent_r direction_r nchars string font_struct -- r )
7 libX11 XTextExtents16                 XTextExtents16  ( overall_r font_descent_r font_ascent_r direction_r nchars string font_struct -- r )
3 libX11 XTextWidth                     XTextWidth      ( count string font_struct -- n )
3 libX11 XTextWidth16                   XTextWidth16    ( count string font_struct -- n )
8 libX11 XTranslateCoordinates          XTranslateCoordinates   ( child_r dest_y_r dest_x_r src_y src_x dest_w src_w dpy -- flag )
2 libX11 XUndefineCursor                XUndefineCursor ( w dpy -- r )
4 libX11 XUngrabButton                  XUngrabButton   ( grab_window modifiers button dpy -- r )
4 libX11 XUngrabKey                     XUngrabKey      ( grab_window modifiers keycode dpy -- r )
2 libX11 XUngrabKeyboard                XUngrabKeyboard ( time dpy -- r )
2 libX11 XUngrabPointer                 XUngrabPointer  ( time dpy -- r )
2 libX11 XUninstallColormap             XUninstallColormap      ( colormap dpy -- r )
2 libX11 XUnloadFont                    XUnloadFont     ( font dpy -- r )
2 libX11 XUnmapSubwindows               XUnmapSubwindows        ( w dpy -- r )
2 libX11 XUnmapWindow                   XUnmapWindow    ( w dpy -- r )
9 libX11 XWarpPointer                   XWarpPointer    ( dest_y dest_x src_h src_w src_y src_x dest_w src_w dpy -- r )
4 libX11 XWindowEvent                   XWindowEvent    ( event_r event_mask w dpy -- r )
7 libX11 XWriteBitmapFile               XWriteBitmapFile        ( y_hot x_hot h w bitmap filename dpy -- r )
4 libX11 XOpenOM                        XOpenOM ( res_class res_name rdb dpy -- XOM )
2 libX11 XFreeFontSet                   XFreeFontSet    ( fontset dpy -- r )
3 libX11 XFontsOfFontSet                XFontsOfFontSet ( font_name_list font_struct_list font_set -- n )
3 libX11 XmbTextEscapement              XmbTextEscapement       ( bytes_text text fontset -- n )
3 libX11 XwcTextEscapement              XwcTextEscapement       ( num_wchars text fontset -- n )
5 libX11 XmbTextExtents                 XmbTextExtents  ( overall_logical_r overall_ink_r bytes_text text fontset -- n )
5 libX11 XwcTextExtents                 XwcTextExtents  ( overall_logical_r overall_ink_r num_wchars text fontset -- n )
9 libX11 XmbTextPerCharExtents          XmbTextPerCharExtents   ( overal_logical_r overall_ink_r num_chars buffer_size logical_extents_buffer ink_extents_buffer bytes_text text fontset -- status )
9 libX11 XwcTextPerCharExtents          XwcTextPerCharExtents   ( overal_logical_r overall_ink_r num_chars buffer_size logical_extents_buffer ink_extents_buffer num_wchars text fontset -- status )
7 libX11 XmbDrawText                    XmbDrawText     ( nitems text_items y x gc d dpy -- r )
7 libX11 XwcDrawText                    XwcDrawText     ( nitems text_items y x gc d dpy -- r )
8 libX11 XmbDrawString                  XmbDrawString   ( bytes_text text y x gc fontset d dpy -- r )
8 libX11 XwcDrawString                  XwcDrawString   ( num_wchars text y x gc fontset d dpy -- r )
8 libX11 XmbDrawImageString             XmbDrawImageString      ( bytes_text text y x gc fontset d dpy -- r )
8 libX11 XwcDrawImageString             XwcDrawImageString      ( num_wchars text y x gc fontset d dpy -- r )
4 libX11 XSetICValues_1                 XSetICValues    ( ... ic -- string )
6 libX11 XSetICValues_2                 XSetICValues    ( ... ic -- string )
8 libX11 XSetICValues_3                 XSetICValues    ( ... ic -- string )
4 libX11 XGetICValues_1                 XGetICValues    ( ... ic -- string )
6 libX11 XGetICValues_2                 XGetICValues    ( ... ic -- string )
8 libX11 XGetICValues_3                 XGetICValues    ( ... ic -- string )
2 libX11 XFilterEvent                   XFilterEvent    ( w event -- flag )
6 libX11 XmbLookupString                XmbLookupString ( status_r keysym_r bytes_buffer buffer_r event ic -- n )
6 libX11 XwcLookupString                XwcLookupString ( status_r keysym_r wchars_buffer buffer_r event ic -- n )
[IFDEF] has-utf8
6 libX11 Xutf8LookupString              Xutf8LookupString ( status_r keysym_r wchars_buffer buffer_r event ic -- n )
[THEN]
6 libX11 XRegisterIMInstantiateCallback XRegisterIMInstantiateCallback  ( client_data callback res_class res_name rdb dpy -- flag )
6 libX11 XUnregisterIMInstantiateCallbac        XUnregisterIMInstantiateCallback        ( client_data callback res_class res_name rdb dpy -- flag )
3 libX11 XInternalConnectionNumbers     XInternalConnectionNumbers      ( count_r fd_r dpy -- status )
2 libX11 XProcessInternalConnection     XProcessInternalConnection      ( fd dpy -- r )
3 libX11 XAddConnectionWatch            XAddConnectionWatch     ( client_data callback dpy -- status )
3 libX11 XRemoveConnectionWatch         XRemoveConnectionWatch  ( client_data callback dpy -- status )

\ Xutil.h
\ The following functions are not performed by the XServer, but in Xlib.

0 libX11 XAllocClassHint                XAllocClassHint ( -- classhint* )
0 libX11 XAllocIconSize                 XAllocIconSize  ( -- iconsize* )
0 libX11 XAllocSizeHints                XAllocSizeHints ( -- sizehints* )
0 libX11 XAllocStandardColormap         XAllocStandardColormap  ( -- stdcmap* )
0 libX11 XAllocWMHints                  XAllocWMHints   ( -- wmhints* )
2 libX11 XClipBox                       XClipBox        ( rect reg -- r )
0 libX11 XCreateRegion                  XCreateRegion   ( -- reg )
0 libX11 XDefaultString                 XDefaultString  ( -- char* )
3 libX11 XDeleteContext                 XDeleteContext  ( context rid dpy -- n )
2 libX11 XEqualRegion                   XEqualRegion    ( r1 r2 -- r )
4 libX11 XFindContext                   XFindContext    ( data_r context rid dpy -- n )
3 libX11 XGetClassHint                  XGetClassHint   ( class_hints_r w dpy -- status )
4 libX11 XGetIconSizes                  XGetIconSizes   ( count_r size_list_r w dpy -- status )
3 libX11 XGetNormalHints                XGetNormalHints ( hints_r w dpy -- status )
5 libX11 XGetRGBColormaps               XGetRGBColormaps        ( prop count_r stdcmap_r w dpy -- status )
4 libX11 XGetSizeHints                  XGetSizeHints   ( prop hints_r w dpy -- status )
4 libX11 XGetStandardColormap           XGetStandardColormap    ( prop colormap_r w dpy -- status )
4 libX11 XGetTextProperty               XGetTextProperty        ( prop text_prop_r w dpy -- status )
3 libX11 XGetWMClientMachine            XGetWMClientMachine     ( text_prop_r w dpy -- status )
2 libX11 XGetWMHints                    XGetWMHints     ( w dpy -- WMHints* )
3 libX11 XGetWMIconName                 XGetWMIconName  ( text_prop_r w dpy -- status )
3 libX11 XGetWMName                     XGetWMName      ( text_prop_r w dpy -- status )
4 libX11 XGetWMNormalHints              XGetWMNormalHints       ( supplied_r hints_r w dpy -- status )
5 libX11 XGetWMSizeHints                XGetWMSizeHints ( prop supplied_r hints_r w dpy -- status )
3 libX11 XGetZoomHints                  XGetZoomHints   ( zhints_r w dpy -- status )
3 libX11 XIntersectRegion               XIntersectRegion        ( dr_r srb sra -- r )
3 libX11 XConvertCase                   XConvertCase    ( upper* lower* sym -- r )
5 libX11 XLookupString                  XLookupString   ( composestatus* keysym_r bufsize buffer event -- n )
5 libX11 XMatchVisualInfo               XMatchVisualInfo        ( vinfo_r class depth screen dpy -- status )
3 libX11 XOffsetRegion                  XOffsetRegion   ( dy dx reg -- r )
3 libX11 XPointInRegion                 XPointInRegion  ( y x reg -- flag )
3 libX11 XPolygonRegion                 XPolygonRegion  ( fill_rile n points -- reg )
5 libX11 XRectInRegion                  XRectInRegion   ( h w y x reg -- n )
4 libX11 XSaveContext                   XSaveContext    ( data context rid dpy -- n )
3 libX11 XSetClassHint                  XSetClassHint   ( class_hints w dpy -- r )
4 libX11 XSetIconSizes                  XSetIconSizes   ( count size_list w dpy -- r )
3 libX11 XSetNormalHints                XSetNormalHints ( hints w dpy -- r )
5 libX11 XSetRGBColormaps               XSetRGBColormaps        ( prop count stdcmaps w dpy -- r )
4 libX11 XSetSizeHints                  XSetSizeHints   ( prop hints w dpy -- r )
8 libX11 XSetStandardProperties         XSetStandardProperties  ( sizehints argc argv icon_pixmap icon_name window_name w dpy -- r )
4 libX11 XSetTextProperty               XSetTextProperty        ( prop text_prop w dpy -- r )
3 libX11 XSetWMClientMachine            XSetWMClientMachine     ( text_prop w dpy -- r )
3 libX11 XSetWMHints                    XSetWMHints     ( wm_hints w dpy -- r )
3 libX11 XSetWMIconName                 XSetWMIconName  ( text_prop w dpy -- r )
3 libX11 XSetWMName                     XSetWMName      ( text_prop w dpy -- r )
3 libX11 XSetWMNormalHints              XSetWMNormalHints       ( hints w dpy -- r )
9 libX11 XSetWMProperties               XSetWMProperties        ( class_hints wm_hints normal_hints argc argv icon_name window_name w dpy -- r )
9 libX11 XmbSetWMProperties             XmbSetWMProperties      ( class_hints wm_hints normal_hints argc argv icon_name window_name w dpy -- r )
4 libX11 XSetWMSizeHints                XSetWMSizeHints ( prop hints w dpy -- r )
3 libX11 XSetRegion                     XSetRegion      ( reg gc dpy -- r )
4 libX11 XSetStandardColormap           XSetStandardColormap    ( prop colormap w dpy -- r )
3 libX11 XSetZoomHints                  XSetZoomHints   ( zhints w dpy -- r )
3 libX11 XShrinkRegion                  XShrinkRegion   ( dy dx reg -- r )
3 libX11 XStringListToTextProperty      XStringListToTextProperty       ( text_prop_r count list -- status )
3 libX11 XSubtractRegion                XSubtractRegion ( dr_r srb sra -- r )
5 libX11 XmbTextListToTextProperty      XmbTextListToTextProperty       ( text_prop_r style count list dpy -- n )
5 libX11 XwcTextListToTextProperty      XwcTextListToTextProperty       ( text_prop_r style count list dpy -- n )
3 libX11 XTextPropertyToStringList      XTextPropertyToStringList       ( count_r list_r text_prop -- status )
4 libX11 XmbTextPropertyToTextList      XmbTextPropertyToTextList       ( count_r list_r text_prop dpy -- n )
4 libX11 XwcTextPropertyToTextList      XwcTextPropertyToTextList       ( count_r list_r text_prop dpy -- n )
3 libX11 XUnionRectWithRegion           XUnionRectWithRegion    ( dest_reg_r src_reg rect -- r )
3 libX11 XUnionRegion                   XUnionRegion    ( dr_r srb sra -- r )
&10 libX11 XWMGeometry                  XWMGeometry     ( gravity_r h_r w_r y_r x_r hints border_w default_geometry user_geometry screen_nr dpy -- n )
3 libX11 XXorRegion                     XXorRegion      ( dr_r srb sra -- r )

/* **************************************************************
 *
 * Memory Management
 *
 ****************************************************************/

0 libX11 XrmUniqueQuark                 XrmUniqueQuark  ( -- quark )
2 libX11 XrmStringToQuarkList           XrmStringToQuarkList    ( quarks string -- r )
3 libX11 XrmStringToBindingQuarkList    XrmStringToBindingQuarkList     ( quarks bindings string -- r )

struct{
    cell size
    cell addr
} XrmValue

5 libX11 XrmQPutResource                XrmQPutResource ( value type quarks bindings dbase -- r )
4 libX11 XrmPutResource                 XrmPutResource  ( value type spec dbase -- r )
4 libX11 XrmQPutStringResource          XrmQPutStringResource   ( value quarks bindings dbase -- r )
3 libX11 XrmPutStringResource           XrmPutStringResource    ( value spec dbase -- r )
2 libX11 XrmPutLineResource             XrmPutLineResource      ( line dbase -- r )
5 libX11 XrmQGetResource                XrmQGetResource ( value_r quark_t_r quark_c quark_n dbase -- r )
5 libX11 XrmGetResource                 XrmGetResource  ( value_r str_t_r str_c str_n dbase -- flag )
5 libX11 XrmQGetSearchList              XrmQGetSearchList       ( list_len list_r classes names dbase -- flag )
5 libX11 XrmQGetSearchResource          XrmQGetSearchResource   ( value_r type_r class name list -- flag )
2 libX11 XrmSetDatabase                 XrmSetDatabase  ( dbase dpy -- r )
3 libX11 XrmCombineFileDatabase         XrmCombineFileDatabase  ( flag dbase* filename -- status )
2 libX11 XrmPutFileDatabase             XrmPutFileDatabase      ( string dbase -- r )
2 libX11 XrmMergeDatabases              XrmMergeDatabases       ( dbase* dbase -- r )
3 libX11 XrmCombineDatabase             XrmCombineDatabase      ( flag dbase* dbase )
6 libX11 XrmEnumerateDatabase           XrmEnumerateDatabase    ( closure callback mode class_prefix name_prefix db -- flag )
6 libX11 XrmParseCommand                XrmParseCommand ( argv_io argc_io name table-count table dbase -- r )

\ X extensions

B libXext XShmPutImage                  XShmPutImage            ( send_event h w dy dx sy sx im gc win dpy -- status )

base !

include Xstring.fs

Module;
