\ X11 interface

Module X11

also DOS

library libX11 libX11.so.6
library libXext libXext.so.6 \ depends libX11

previous

base @ hex

' noop alias has-utf8
' noop alias has-png
' noop alias has-xft

\ -1 libX11 _XPrivDisplay               _XPrivDisplay   ( -- addr )
\ -1 libX11 _Xdebug                       _Xdebug         ( -- addr )
2 libX11 XLoadQueryFont                 XLoadQueryFont  ( name dpy -- fontstruct )
2 libX11 XQueryFont                     XQueryFont      ( XID dpy -- fontstruct )
5 libX11 XGetMotionEvents               XGetMotionEvents        ( neventsr stop start w dpy -- timecoord )
3 libX11 XDeleteModifiermapEntry        XDeleteModifiermapEntry ( mod keycode modmap -- modmap )
1 libX11 XGetModifierMapping            XGetModifierMapping     ( dpy -- modmap )
3 libX11 XInsertModifiermapEntry        XInsertModifiermapEntry ( mod keycode modmap -- modmap )
1 libX11 XNewModifiermap                XNewModifiermap ( maxkeys -- modmap )
A libX11 XCreateImage                   XCreateImage    ( b/line bmpad h w data offset format depth visual dpy -- image )
1 libX11 XInitImage                     XInitImage      ( image -- status )
8 libX11 XGetImage                      XGetImage       ( format planemask h w y x d dpy -- image )
B libX11 XGetSubImage                   XGetSubImage    ( dy dx dimage format planemask h w y x d dpy -- image )
1 libX11 XOpenDisplay                   XOpenDisplay    ( name -- dpy )
0 libX11 XrmInitialize                  XrmInitialize   ( -- r )
2 libX11 XFetchBytes                    XFetchBytes     ( nbytesr dpy -- buffer )
3 libX11 XFetchBuffer                   XFetchBuffer    ( buffer nbytesr dpy -- buffer )
2 libX11 XGetAtomName                   XGetAtomName    ( atom dpy -- name )
4 libX11 XGetAtomNames                  XGetAtomNames   ( namesr count atoms dpy -- status )
3 libX11 XGetDefault                    XGetDefault     ( option program dpy --  string )
1 libX11 XDisplayName                   XDisplayName    ( string -- string )
1 libX11 XKeysymToString                XKeysymToString ( keysym -- string )
3 libX11 XInternAtom                    XInternAtom     ( flag atomname dpy -- atom )
5 libX11 XInternAtoms                   XInternAtoms    ( atoms flag count names dpy -- status )
2 libX11 XCopyColormapAndFree           XCopyColormapAndFree    ( colormap dpy -- colormap )
4 libX11 XCreateColormap                XCreateColormap ( alloc visual w dpy -- colormap )
7 libX11 XCreatePixmapCursor            XCreatePixmapCursor     ( y x bgcol fgcol mask source dpy -- cursor )
7 libX11 XCreateGlyphCursor             XCreateGlyphCursor      ( bgcol fgcol maskc sourcec maskfont sourcefont dpy -- cursor )
2 libX11 XCreateFontCursor              XCreateFontCursor       ( shape dpy -- cursor )
2 libX11 XLoadFont                      XLoadFont       ( name dpy -- font )
4 libX11 XCreateGC                      XCreateGC       ( values valuemask d dpy -- gc )
1 libX11 XGContextFromGC                XGContextFromGC ( gc -- gcontext )
2 libX11 XFlushGC                       XFlushGC        ( gc dpy -- r )
5 libX11 XCreatePixmap                  XCreatePixmap   ( depth h w d dpy -- pixmap )
5 libX11 XCreateBitmapFromData          XCreateBitmapFromData   ( h w data d dpy -- pixmap )
8 libX11 XCreatePixmapFromBitmapData    XCreatePixmapFromBitmapData     ( depth bg fg h w data d dpy -- pixmap )
9 libX11 XCreateSimpleWindow            XCreateSimpleWindow     ( bg border bwidth h w y x parent dpy -- window )
2 libX11 XGetSelectionOwner             XGetSelectionOwner      ( atom dpy -- window )
C libX11 XCreateWindow                  XCreateWindow   ( attribs valuemask visual class depth borderwidth h w y x parent dpy -- window )
3 libX11 XListInstalledColormaps        XListInstalledColormaps ( num_r w dpy -- colormap* )
4 libX11 XListFonts                     XListFonts      ( actual_count_r maxnames pattern dpy -- char** )
5 libX11 XListFontsWithInfo             XListFontsWithInfo      ( info_r count_r maxnames pattern dpy -- char** )
2 libX11 XGetFontPath                   XGetFontPath    ( npaths_r dpy -- char** )
2 libX11 XListExtensions                XListExtensions ( nextensions_r dpy -- char** )
3 libX11 XListProperties                XListProperties ( num_prop_r w dpy -- atom* )
3 libX11 XListHosts                     XListHosts      ( status_r nhosts_r dpy -- hostaddr* )
3 libX11 XKeycodeToKeysym               XKeycodeToKeysym        ( index keycode dpy -- keysym )
2 libX11 XLookupKeysym                  XLookupKeysym   ( index key_event -- keysym )
4 libX11 XGetKeyboardMapping            XGetKeyboardMapping     ( keysym/keycode_r keycode_c first_kc dpy -- keysym* )
1 libX11 XStringToKeysym                XStringToKeysym ( sting -- keysym )
1 libX11 XMaxRequestSize                XMaxRequestSize ( dpy -- n )
1 libX11 XExtendedMaxRequestSize        XExtendedMaxRequestSize ( dpy -- n )
1 libX11 XResourceManagerString         XResourceManagerString  ( dpy -- string )
1 libX11 XScreenResourceString          XScreenResourceString   ( screen -- string )
1 libX11 XDisplayMotionBufferSize       XDisplayMotionBufferSize        ( dpy -- u )
1 libX11 XVisualIDFromVisual            XVisualIDFromVisual     ( visual -- visualID )
0 libX11 XInitThreads                   XInitThreads    ( -- status )
1 libX11 XLockDisplay                   XLockDisplay    ( dpy -- r )
1 libX11 XUnlockDisplay                 XUnlockDisplay  ( dpy -- r )
2 libX11 XInitExtension                 XInitExtension  ( name dpy -- extcodes )
1 libX11 XAddExtension                  XAddExtension   ( dpy -- extcodes )
2 libX11 XFindOnExtensionList           XFindOnExtensionList    ( number structure -- extdata )
1 libX11 XEHeadOfExtensionList          XEHeadOfExtensionList   ( object -- extdata** )
2 libX11 XRootWindow                    XRootWindow     ( screen_nr dpy -- window )
1 libX11 XDefaultRootWindow             XDefaultRootWindow      ( dpy -- window )
1 libX11 XRootWindowOfScreen            XRootWindowOfScreen     ( screen -- window )
2 libX11 XDefaultVisual                 XDefaultVisual  ( screen_nr dpy -- visual )
1 libX11 XDefaultVisualOfScreen         XDefaultVisualOfScreen  ( screen -- visual )
2 libX11 XDefaultGC                     XDefaultGC      ( screen_nr dpy -- gc )
1 libX11 XDefaultGCOfScreen             XDefaultGCOfScreen      ( screen -- gc )
2 libX11 XBlackPixel                    XBlackPixel     ( screen_nr dpy -- u )
2 libX11 XWhitePixel                    XWhitePixel     ( screen_nr dpy -- u )
0 libX11 XAllPlanes                     XAllPlanes      ( -- u )
1 libX11 XBlackPixelOfScreen            XBlackPixelOfScreen     ( screen -- u )
1 libX11 XWhitePixelOfScreen            XWhitePixelOfScreen     ( screen -- u )
1 libX11 XNextRequest                   XNextRequest    ( dpy -- u )
1 libX11 XLastKnownRequestProcessed     XLastKnownRequestProcessed      ( dpy -- u )
1 libX11 XServerVendor                  XServerVendor   ( dpy -- string )
1 libX11 XDisplayString                 XDisplayString  ( dpy -- string )
2 libX11 XDefaultColormap               XDefaultColormap        ( screen_nr dpy -- colormap )
1 libX11 XDefaultColormapOfScreen       XDefaultColormapOfScreen        ( screen -- colormap )
1 libX11 XDisplayOfScreen               XDisplayOfScreen        ( screen -- dpy )
2 libX11 XScreenOfDisplay               XScreenOfDisplay        ( screen_nr dpy -- screen )
1 libX11 XDefaultScreenOfDisplay        XDefaultScreenOfDisplay ( dpy -- screen )
1 libX11 XEventMaskOfScreen             XEventMaskOfScreen      ( screen -- mask )
1 libX11 XScreenNumberOfScreen          XScreenNumberOfScreen   ( screen -- n )
1 libX11 XSetErrorHandler               XSetErrorHandler        ( handler -- errorhandler )
1 libX11 XSetIOErrorHandler             XSetIOErrorHandler      ( handler -- ioerrorhandler )
2 libX11 XListPixmapFormats             XListPixmapFormats      ( count_r dpy -- pixmapformatvalues )
3 libX11 XListDepths                    XListDepths     ( count_r screen_nr dpy -- int* )
5 libX11 XReconfigureWMWindow           XReconfigureWMWindow    ( changes mask screen_nr w dpy -- status )
4 libX11 XGetWMProtocols                XGetWMProtocols ( count_r protocols_r w dpy -- status )
4 libX11 XSetWMProtocols                XSetWMProtocols ( count protocols w dpy -- status )
3 libX11 XIconifyWindow                 XIconifyWindow  ( screen_nr w dpy -- status )
3 libX11 XWithdrawWindow                XWithdrawWindow ( screen_nr w dpy -- status )
4 libX11 XGetCommand                    XGetCommand     ( argc_r argv_r w dpy -- status )
4 libX11 XGetWMColormapWindows          XGetWMColormapWindows   ( count_r windows_r w dpy -- status )
4 libX11 XSetWMColormapWindows          XSetWMColormapWindows   ( count colormap_windows w dpy -- status )
1 libX11 XFreeStringList                XFreeStringList ( list -- r )
3 libX11 XSetTransientForHint           XSetTransientForHint    ( propw w dpy -- r )
1 libX11 XActivateScreenSaver           XActivateScreenSaver    ( dpy -- r )
2 libX11 XAddHost                       XAddHost        ( host dpy -- r )
3 libX11 XAddHosts                      XAddHosts       ( num hosts dpy -- r )
2 libX11 XAddToExtensionList            XAddToExtensionList     ( extdata structure -- r )
2 libX11 XAddToSaveSet                  XAddToSaveSet   ( w dpy -- r )
3 libX11 XAllocColor                    XAllocColor     ( color colormap dpy -- status )
7 libX11 XAllocColorCells               XAllocColorCells        ( pixels pixels_r planes planemask_r contig colormap dpy -- status )
B libX11 XAllocColorPlanes              XAllocColorPlanes       ( bmask_r gmask_r rmask_r blues greens reds colors pixels_r contig colormap dpy -- status )
5 libX11 XAllocNamedColor               XAllocNamedColor        ( exact_def_r screen_def_r cname colormap dpy -- status )
3 libX11 XAllowEvents                   XAllowEvents    ( time event_mode dpy -- r )
1 libX11 XAutoRepeatOff                 XAutoRepeatOff  ( dpy -- r )
1 libX11 XAutoRepeatOn                  XAutoRepeatOn   ( dpy -- r )
2 libX11 XBell                          XBell   ( percent dpy -- r )
1 libX11 XBitmapBitOrder                XBitmapBitOrder ( dpy -- n )
1 libX11 XBitmapPad                     XBitmapPad      ( dpy -- n )
1 libX11 XBitmapUnit                    XBitmapUnit     ( dpy -- n )
1 libX11 XCellsOfScreen                 XCellsOfScreen  ( screen -- n )
4 libX11 XChangeActivePointerGrab       XChangeActivePointerGrab        ( time cursor event_mask dpy -- r )
4 libX11 XChangeGC                      XChangeGC       ( values valuemask gc dpy -- r )
3 libX11 XChangeKeyboardControl         XChangeKeyboardControl  ( values valuemask dpy -- r )
5 libX11 XChangeKeyboardMapping         XChangeKeyboardMapping  ( num_codes keysyms keysyms/keycode first_kc dpy -- r )
6 libX11 XChangePointerControl          XChangePointerControl   ( threshold accel_denom accel_num do_thres do_accel dpy -- r )
8 libX11 XChangeProperty                XChangeProperty ( elements data mode format type property w dpy -- r )
3 libX11 XChangeSaveSet                 XChangeSaveSet  ( change_mode w dpy -- r )
4 libX11 XChangeWindowAttributes        XChangeWindowAttributes ( attributes valuemask w dpy -- r )
4 libX11 XCheckIfEvent                  XCheckIfEvent   ( arg predicate event_return dpy -- flag )
3 libX11 XCheckMaskEvent                XCheckMaskEvent ( event_r event_mask dpy -- flag )
3 libX11 XCheckTypedEvent               XCheckTypedEvent        ( event_r event_type dpy -- flag )
4 libX11 XCheckTypedWindowEvent         XCheckTypedWindowEvent  ( event_r event_type w dpy -- flag )
4 libX11 XCheckWindowEvent              XCheckWindowEvent       ( event_r event_mask w dpy -- flag )
3 libX11 XCirculateSubwindows           XCirculateSubwindows    ( direction w dpy -- r )
2 libX11 XCirculateSubwindowsDown       XCirculateSubwindowsDown        ( w dpy -- r )
2 libX11 XCirculateSubwindowsUp         XCirculateSubwindowsUp  ( w dpy -- r )
7 libX11 XClearArea                     XClearArea      ( exposures h w y x w dpy -- r )
2 libX11 XClearWindow                   XClearWindow    ( w dpy -- r )
1 libX11 XCloseDisplay                  XCloseDisplay   ( dpy -- r )
4 libX11 XConfigureWindow               XConfigureWindow        ( values value_mask w dpy -- r )
1 libX11 XConnectionNumber              XConnectionNumber       ( dpy -- r )
6 libX11 XConvertSelection              XConvertSelection       ( time requestor property target selection dpy -- r )
A libX11 XCopyArea                      XCopyArea       ( dy dx h w y x gc dest src dpy -- r )
4 libX11 XCopyGC                        XCopyGC ( dest valuemask src dpy -- r )
B libX11 XCopyPlane                     XCopyPlane      ( plane dy dx h w y x gc dest src dpy -- r )
2 libX11 XDefaultDepth                  XDefaultDepth   ( screen_nr dpy -- i )
1 libX11 XDefaultDepthOfScreen          XDefaultDepthOfScreen   ( screen -- i )
1 libX11 XDefaultScreen                 XDefaultScreen  ( dpy -- i )
3 libX11 XDefineCursor                  XDefineCursor   ( cursor w dpy -- r )
3 libX11 XDeleteProperty                XDeleteProperty ( atom w dpy -- r )
2 libX11 XDestroyWindow                 XDestroyWindow  ( w dpy -- r )
2 libX11 XDestroySubwindows             XDestroySubwindows      ( w dpy -- r )
1 libX11 XDoesBackingStore              XDoesBackingStore       ( screen -- i )
1 libX11 XDoesSaveUnders                XDoesSaveUnders ( screen -- flag )
1 libX11 XDisableAccessControl          XDisableAccessControl   ( dpy -- r )
2 libX11 XDisplayCells                  XDisplayCells   ( screen_nr dpy -- i )
2 libX11 XDisplayHeight                 XDisplayHeight  ( screen_nr dpy -- i )
2 libX11 XDisplayHeightMM               XDisplayHeightMM        ( screen_nr dpy -- i )
3 libX11 XDisplayKeycodes               XDisplayKeycodes        ( min_keycodes_r max_keycodes_r dpy -- r )
2 libX11 XDisplayPlanes                 XDisplayPlanes  ( screen_nr dpy -- i )
2 libX11 XDisplayWidth                  XDisplayWidth   ( screen_nr dpy -- i )
2 libX11 XDisplayWidthMM                XDisplayWidthMM ( screen_nr dpy -- i )
9 libX11 XDrawArc                       XDrawArc        ( angle2 angle1 h w y x gc d dpy -- r )
5 libX11 XDrawArcs                      XDrawArcs       ( narcs arcs gc d dpy -- r )
7 libX11 XDrawImageString               XDrawImageString        ( length string y x gc d dpy -- r )
7 libX11 XDrawImageString16             XDrawImageString16      ( length string y x gc d dpy -- r )
7 libX11 XDrawLine                      XDrawLine       ( y2 y1 x2 x1 gc d dpy -- r )
6 libX11 XDrawLines                     XDrawLines      ( mode npoints points gc d dpy -- r )
5 libX11 XDrawPoint                     XDrawPoint      ( y x gc d dpy -- r )
6 libX11 XDrawPoints                    XDrawPoints     ( mode npoints point gc d dpy -- r )
7 libX11 XDrawRectangle                 XDrawRectangle  ( h w y x gc d dpy -- r )
5 libX11 XDrawRectangles                XDrawRectangles ( nrects rects gc d dpy -- r )
5 libX11 XDrawSegments                  XDrawSegments   ( nsegments segments gc d dpy -- r )
7 libX11 XDrawString                    XDrawString     ( length string y x gc d dpy -- r )
7 libX11 XDrawString16                  XDrawString16   ( length string y x gc d dpy -- r )
7 libX11 XDrawText                      XDrawText       ( nitems items y x gc d dpy -- r )
7 libX11 XDrawText16                    XDrawText16     ( nitems items y x gc d dpy -- r )
1 libX11 XEnableAccessControl           XEnableAccessControl    ( dpy -- r )
2 libX11 XEventsQueued                  XEventsQueued   ( mode dpy -- i )
3 libX11 XFetchName                     XFetchName      ( name_r w dpy -- status )
9 libX11 XFillArc                       XFillArc        ( angle2 angle1 h w y x gc d dpy -- r )
5 libX11 XFillArcs                      XFillArcs       ( narcs arcs gc d dpy -- r )
7 libX11 XFillPolygon                   XFillPolygon    ( mode shape npoints points gc d dpy -- r )
7 libX11 XFillRectangle                 XFillRectangle  ( h w y x gc d dpy -- r )
5 libX11 XFillRectangles                XFillRectangles ( nrects rects gc d dpy -- r )
1 libX11 XFlush                         XFlush  ( dpy -- r )
2 libX11 XForceScreenSaver              XForceScreenSaver       ( mode dpy -- r )
1 libX11 XFree                          XFree   ( data -- r )
2 libX11 XFreeColormap                  XFreeColormap   ( colormap dpy -- r )
5 libX11 XFreeColors                    XFreeColors     ( planes npixels pixels colormap dpy -- r )
2 libX11 XFreeCursor                    XFreeCursor     ( cursor dpy -- r )
1 libX11 XFreeExtensionList             XFreeExtensionList      ( list -- r )
2 libX11 XFreeFont                      XFreeFont       ( fontstruct dpy -- r )
3 libX11 XFreeFontInfo                  XFreeFontInfo   ( actual_count free_info names -- r )
1 libX11 XFreeFontNames                 XFreeFontNames  ( list -- r )
1 libX11 XFreeFontPath                  XFreeFontPath   ( list -- r )
2 libX11 XFreeGC                        XFreeGC ( gc dpy -- r )
1 libX11 XFreeModifiermap               XFreeModifiermap        ( modmap -- r )
2 libX11 XFreePixmap                    XFreePixmap     ( pixmap dpy -- r )
D libX11 XGeometry                      XGeometry       ( hr wr yr xr yadder xadder fh fw bw default_pos pos screen dpy -- n )
6 libX11 XGetErrorDatabaseText          XGetErrorDatabaseText   ( int buffer_r default_string message name dpy -- r )
4 libX11 XGetErrorText                  XGetErrorText   ( length buffer_r code dpy -- r )
3 libX11 XGetFontProperty               XGetFontProperty        ( value_r atom fontstruct -- flag )
4 libX11 XGetGCValues                   XGetGCValues    ( values_r valuemask gc dpy -- status )
9 libX11 XGetGeometry                   XGetGeometry    ( depth_r borderw_r h_r w_r y_r x_r root_r d dpy -- status )
3 libX11 XGetIconName                   XGetIconName    ( icon_name-r w dpy -- status )
3 libX11 XGetInputFocus                 XGetInputFocus  ( revert_to_r focus_r dpy -- r )
2 libX11 XGetKeyboardControl            XGetKeyboardControl     ( values_r dpy -- r )
4 libX11 XGetPointerControl             XGetPointerControl      ( threshold_r accel_denom_r accel_num_r dpy -- r )
3 libX11 XGetPointerMapping             XGetPointerMapping      ( nmap map_r dpy -- n )
5 libX11 XGetScreenSaver                XGetScreenSaver ( allow_exposures_r prefer_blanking_r interval_r timeout_r dpy -- r )
3 libX11 XGetTransientForHint           XGetTransientForHint    ( prop_w_r w dpy -- status )
C libX11 XGetWindowProperty             XGetWindowProperty      ( prop_r bytes_after_r nitems_r actual_format_r actual_typer req_type delete length offset property w dpy -- n )
3 libX11 XGetWindowAttributes           XGetWindowAttributes    ( windows_attributes_r w dpy -- status )
9 libX11 XGrabButton                    XGrabButton     ( cursor confine_to keyboard_mode pointer_mode owner_events grab_window modifiers button dpy -- r )
8 libX11 XGrabKey                       XGrabKey        ( keyboard_mode pointer_mode owner_events grab_events grab_window modifiers keycode dpy -- r )
6 libX11 XGrabKeyboard                  XGrabKeyboard   ( time keyboard_mode pointer_mode owner_events grab_window dpy -- n )
9 libX11 XGrabPointer                   XGrabPointer    ( time cursor confine_to keyboard_mode pointer_mode owner_events grab_window dpy -- n )
1 libX11 XGrabServer                    XGrabServer     ( dpy -- r )
1 libX11 XHeightMMOfScreen              XHeightMMOfScreen       ( screen -- n )
1 libX11 XHeightOfScreen                XHeightOfScreen ( screen -- n )
4 libX11 XIfEvent                       XIfEvent        ( arg predicate event_r dpy -- r )
1 libX11 XImageByteOrder                XImageByteOrder ( dpy -- n )
2 libX11 XInstallColormap               XInstallColormap        ( colormap dpy -- r )
2 libX11 XKeysymToKeycode               XKeysymToKeycode        ( keysym dpy -- keycode )
2 libX11 XKillClient                    XKillClient     ( resource dpy -- r )
\ 1 libX11 XLastKnownRequestProcessed   XLastKnownRequestProcessed      ( dpy -- u )
5 libX11 XLookupColor                   XLookupColor    ( screen_def_r exact_def_r color_name colormap dpy -- status )
2 libX11 XLowerWindow                   XLowerWindow    ( w dpy -- r )
2 libX11 XMapRaised                     XMapRaised      ( w dpy -- r )
2 libX11 XMapSubwindows                 XMapSubwindows  ( w dpy -- r )
2 libX11 XMapWindow                     XMapWindow      ( w dpy -- r )
3 libX11 XMaskEvent                     XMaskEvent      ( event_r event_mask dpy -- r )
1 libX11 XMaxCmapsOfScreen              XMaxCmapsOfScreen       ( screen -- n )
1 libX11 XMinCmapsOfScreen              XMinCmapsOfScreen       ( screen -- n )
6 libX11 XMoveResizeWindow              XMoveResizeWindow       ( h w y x w dpy -- r )
4 libX11 XMoveWindow                    XMoveWindow     ( y x w dpy -- r )
2 libX11 XNextEvent                     XNextEvent      ( event_r dpy -- r )
1 libX11 XNoOp                          XNoOp   ( dpy -- r )
4 libX11 XParseColor                    XParseColor     ( exact_def_r spec colormap dpy -- status )
5 libX11 XParseGeometry                 XParseGeometry  ( h_r w_r y_r x_r parsestring -- n )
2 libX11 XPeekEvent                     XPeekEvent      ( event_r dpy -- r )
4 libX11 XPeekIfEvent                   XPeekIfEvent    ( arg predicate event_r dpy -- r )
1 libX11 XPending                       XPending        ( dpy -- n )
1 libX11 XPlanesOfScreen                XPlanesOfScreen ( screen -- n )
1 libX11 XProtocolRevision              XProtocolRevision       ( dpy -- n )
1 libX11 XProtocolVersion               XProtocolVersion        ( dpy -- n )
2 libX11 XPutBackEvent                  XPutBackEvent   ( event dpy -- r )
A libX11 XPutImage                      XPutImage       ( h w d_y d_x s_y s_x image gc d dpy -- r )
1 libX11 XQLength                       XQLength        ( dpy -- n )
6 libX11 XQueryBestCursor               XQueryBestCursor        ( h_r w_r h w d dpy -- status )
7 libX11 XQueryBestSize                 XQueryBestSize  ( h_r w_r h w which_screen class dpy -- status )
6 libX11 XQueryBestStipple              XQueryBestStipple       ( h_r w_r h w which_screen dpy -- status )
6 libX11 XQueryBestTile                 XQueryBestTile  ( h_r w_r h w which_screen dpy -- status )
3 libX11 XQueryColor                    XQueryColor     ( def_in_out colormap dpy -- r )
4 libX11 XQueryColors                   XQueryColors    ( ncolors defs_in_out colormap dpy -- r )
5 libX11 XQueryExtension                XQueryExtension ( first_error_r first_event_r major_opcode_r name dpy -- flag )
2 libX11 XQueryKeymap                   XQueryKeymap    ( keys_r dpy -- r )
9 libX11 XQueryPointer                  XQueryPointer   ( mask_r win_y_r win_x_r root_y_r root_x_r child_r root_r w dpy -- flag )
8 libX11 XQueryTextExtents              XQueryTextExtents       ( overall_r font_descent_r font_ascent_r direction_r nchars string font_id dpy -- r )
8 libX11 XQueryTextExtents16            XQueryTextExtents16     ( overall_r font_descent_r font_ascent_r direction_r nchars string font_id dpy -- r )
6 libX11 XQueryTree                     XQueryTree      ( nchildren_r children_r parent_r root_r w dpy -- status )
2 libX11 XRaiseWindow                   XRaiseWindow    ( w dpy -- r )
8 libX11 XReadBitmapFile                XReadBitmapFile ( y_hot_r x_hot_r bitmap_r height_r width_r filename d dpy -- n )
6 libX11 XReadBitmapFileData            XReadBitmapFileData     ( y_hot_r x_hot_r bitmap_r height_r width_r filename -- n )
6 libX11 XRebindKeysym                  XRebindKeysym   ( bytes_string string mod_count list keysym dpy -- r )
4 libX11 XRecolorCursor                 XRecolorCursor  ( bg fg cursor dpy -- r )
1 libX11 XRefreshKeyboardMapping        XRefreshKeyboardMapping ( event_map -- r )
2 libX11 XRemoveFromSaveSet             XRemoveFromSaveSet      ( w dpy -- r )
2 libX11 XRemoveHost                    XRemoveHost     ( host dpy -- r )
3 libX11 XRemoveHosts                   XRemoveHosts    ( num_hosts hosts dpy -- r )
5 libX11 XReparentWindow                XReparentWindow ( y x parent w dpy -- r )
1 libX11 XResetScreenSaver              XResetScreenSaver       ( dpy -- r )
4 libX11 XResizeWindow                  XResizeWindow   ( h w w dpy -- r )
3 libX11 XRestackWindows                XRestackWindows ( nwindows windows dpy -- r )
2 libX11 XRotateBuffers                 XRotateBuffers  ( rotate dpy -- r )
5 libX11 XRotateWindowProperties        XRotateWindowProperties ( npositions num_prop properties w dpy -- r )
1 libX11 XScreenCount                   XScreenCount    ( dpy -- n )
3 libX11 XSelectInput                   XSelectInput    ( event_mask w dpy -- r )
5 libX11 XSendEvent                     XSendEvent      ( event_send event_mask propagate w dpy -- status )
2 libX11 XSetAccessControl              XSetAccessControl       ( mode dpy -- r )
3 libX11 XSetArcMode                    XSetArcMode     ( arc_mode gc dpy -- r )
3 libX11 XSetBackground                 XSetBackground  ( background gc dpy -- r )
3 libX11 XSetClipMask                   XSetClipMask    ( pixmap gc dpy -- r )
4 libX11 XSetClipOrigin                 XSetClipOrigin  ( clip_y_orig clip_x_orig gc dpy -- r )
7 libX11 XSetClipRectangles             XSetClipRectangles      ( ordering n rectangles clip_y_orig clip_x_orig gc dpy -- r )
2 libX11 XSetCloseDownMode              XSetCloseDownMode       ( close_mode dpy -- r )
4 libX11 XSetCommand                    XSetCommand     ( argc argv w dpy -- r )
5 libX11 XSetDashes                     XSetDashes      ( n dash_list dash_ofset gc dpy -- r )
3 libX11 XSetFillRule                   XSetFillRule    ( fill_rule gc dpy -- r )
3 libX11 XSetFillStyle                  XSetFillStyle   ( fill_style gc dpy -- r )
3 libX11 XSetFont                       XSetFont        ( font gc dpy -- r )
3 libX11 XSetFontPath                   XSetFontPath    ( ndirs directories dpy -- r )
3 libX11 XSetForeground                 XSetForeground  ( fg gc dpy -- r )
3 libX11 XSetFunction                   XSetFunction    ( function gc dpy -- r )
3 libX11 XSetGraphicsExposures          XSetGraphicsExposures   ( graphics_exposures gc dpy -- r )
3 libX11 XSetIconName                   XSetIconName    ( icon_name w dpy -- r )
4 libX11 XSetInputFocus                 XSetInputFocus  ( time revert_to focus dpy -- r )
6 libX11 XSetLineAttributes             XSetLineAttributes      ( join_style cap_style line_style line_width gc dpy -- r )
2 libX11 XSetModifierMapping            XSetModifierMapping     ( modmap dpy -- n )
3 libX11 XSetPlaneMask                  XSetPlaneMask   ( plane_mask gc dpy -- r )
3 libX11 XSetPointerMapping             XSetPointerMapping      ( nmap map dpy -- n )
5 libX11 XSetScreenSaver                XSetScreenSaver ( allow_exposures prefer_blanking interval timeout dpy -- r )
4 libX11 XSetSelectionOwner             XSetSelectionOwner      ( time owner selection dpy -- r )
6 libX11 XSetState                      XSetState       ( plane_mask function bg fg gc dpy -- r )
3 libX11 XSetStipple                    XSetStipple     ( stripple gc dpy -- r )
3 libX11 XSetSubwindowMode              XSetSubwindowMode       ( subwindow_mode gc dpy -- r )
4 libX11 XSetTSOrigin                   XSetTSOrigin    ( ts_y_orig ts_x_orig gc dpy -- r )
3 libX11 XSetTile                       XSetTile        ( tile gc dpy -- )
3 libX11 XSetWindowBackground           XSetWindowBackground    ( bg_pixel w dpy -- )
3 libX11 XSetWindowBackgroundPixmap     XSetWindowBackgroundPixmap      ( bg_pixmap w dpy -- r )
3 libX11 XSetWindowBorder               XSetWindowBorder        ( border_pixel w dpy -- r )
3 libX11 XSetWindowBorderPixmap         XSetWindowBorderPixmap  ( border_pixmap w dpy -- r )
3 libX11 XSetWindowBorderWidth          XSetWindowBorderWidth   ( width w dpy -- r )
3 libX11 XSetWindowColormap             XSetWindowColormap      ( colormap w dpy -- r )
4 libX11 XStoreBuffer                   XStoreBuffer    ( buffer nbytes bytes dpy -- r )
3 libX11 XStoreBytes                    XStoreBytes     ( nbytes bytes dpy -- r )
3 libX11 XStoreColor                    XStoreColor     ( color colormap dpy -- r )
4 libX11 XStoreColors                   XStoreColors    ( ncolors color colormap dpy -- r )
3 libX11 XStoreName                     XStoreName      ( window_name w dpy -- r )
5 libX11 XStoreNamedColor               XStoreNamedColor        ( flags pixel color colormap dpy -- r )
2 libX11 XSync                          XSync   ( discard dpy -- r )
7 libX11 XTextExtents                   XTextExtents    ( overall_r font_descent_r font_ascent_r direction_r nchars string font_struct -- r )
7 libX11 XTextExtents16                 XTextExtents16  ( overall_r font_descent_r font_ascent_r direction_r nchars string font_struct -- r )
3 libX11 XTextWidth                     XTextWidth      ( count string font_struct -- n )
3 libX11 XTextWidth16                   XTextWidth16    ( count string font_struct -- n )
8 libX11 XTranslateCoordinates          XTranslateCoordinates   ( child_r dest_y_r dest_x_r src_y src_x dest_w src_w dpy -- flag )
2 libX11 XUndefineCursor                XUndefineCursor ( w dpy -- r )
4 libX11 XUngrabButton                  XUngrabButton   ( grab_window modifiers button dpy -- r )
4 libX11 XUngrabKey                     XUngrabKey      ( grab_window modifiers keycode dpy -- r )
2 libX11 XUngrabKeyboard                XUngrabKeyboard ( time dpy -- r )
2 libX11 XUngrabPointer                 XUngrabPointer  ( time dpy -- r )
1 libX11 XUngrabServer                  XUngrabServer   ( dpy -- r )
2 libX11 XUninstallColormap             XUninstallColormap      ( colormap dpy -- r )
2 libX11 XUnloadFont                    XUnloadFont     ( font dpy -- r )
2 libX11 XUnmapSubwindows               XUnmapSubwindows        ( w dpy -- r )
2 libX11 XUnmapWindow                   XUnmapWindow    ( w dpy -- r )
1 libX11 XVendorRelease                 XVendorRelease  ( dpy -- n )
9 libX11 XWarpPointer                   XWarpPointer    ( dest_y dest_x src_h src_w src_y src_x dest_w src_w dpy -- r )
1 libX11 XWidthMMOfScreen               XWidthMMOfScreen        ( screen -- n )
1 libX11 XWidthOfScreen                 XWidthOfScreen  ( screen -- n )
4 libX11 XWindowEvent                   XWindowEvent    ( event_r event_mask w dpy -- r )
7 libX11 XWriteBitmapFile               XWriteBitmapFile        ( y_hot x_hot h w bitmap filename dpy -- r )
0 libX11 XSupportsLocale                XSupportsLocale ( -- flag )
1 libX11 XSetLocaleModifiers            XSetLocaleModifiers     ( modifier_list -- string )
4 libX11 XOpenOM                        XOpenOM ( res_class res_name rdb dpy -- XOM )
1 libX11 XCloseOM                       XCloseOM        ( om -- status )
1 libX11 XSetOMValues                   XSetOMValues    ( ...om -- string )
1 libX11 XGetOMValues                   XGetOMValues    ( ...om -- string )
1 libX11 XDisplayOfOM                   XDisplayOfOM    ( om -- dpy )
1 libX11 XLocaleOfOM                    XLocaleOfOM     ( om -- string )
1 libX11 XCreateOC                      XCreateOC       ( ...om -- XOC )
1 libX11 XDestroyOC                     XDestroyOC      ( oc -- r )
1 libX11 XOMOfOC                        XOMOfOC ( oc -- XOM )
1 libX11 XSetOCValues                   XSetOCValues    ( ...oc -- string )
1 libX11 XGetOCValues                   XGetOCValues    ( ...oc -- string )
5 libX11 XCreateFontSet                 XCreateFontSet  ( def_string missing-charset_count missing_charset_list base_font_name_list dpy -- fontset )
2 libX11 XFreeFontSet                   XFreeFontSet    ( fontset dpy -- r )
3 libX11 XFontsOfFontSet                XFontsOfFontSet ( font_name_list font_struct_list font_set -- n )
1 libX11 XBaseFontNameListOfFontSet     XBaseFontNameListOfFontSet       ( fontset -- string )
1 libX11 XLocaleOfFontSet               XLocaleOfFontSet        ( fontset -- string )
1 libX11 XContextDependentDrawing       XContextDependentDrawing        ( fontset -- flag )
1 libX11 XDirectionalDependentDrawing   XDirectionalDependentDrawing    ( fontset -- flag )
1 libX11 XContextualDrawing             XContextualDrawing      ( fontset -- flag )
1 libX11 XExtentsOfFontSet              XExtentsOfFontSet       ( fontset -- fontsetextents )
3 libX11 XmbTextEscapement              XmbTextEscapement       ( bytes_text text fontset -- n )
3 libX11 XwcTextEscapement              XwcTextEscapement       ( num_wchars text fontset -- n )
5 libX11 XmbTextExtents                 XmbTextExtents  ( overall_logical_r overall_ink_r bytes_text text fontset -- n )
5 libX11 XwcTextExtents                 XwcTextExtents  ( overall_logical_r overall_ink_r num_wchars text fontset -- n )
9 libX11 XmbTextPerCharExtents          XmbTextPerCharExtents   ( overal_logical_r overall_ink_r num_chars buffer_size logical_extents_buffer ink_extents_buffer bytes_text text fontset -- status )
9 libX11 XwcTextPerCharExtents          XwcTextPerCharExtents   ( overal_logical_r overall_ink_r num_chars buffer_size logical_extents_buffer ink_extents_buffer num_wchars text fontset -- status )
7 libX11 XmbDrawText                    XmbDrawText     ( nitems text_items y x gc d dpy -- r )
7 libX11 XwcDrawText                    XwcDrawText     ( nitems text_items y x gc d dpy -- r )
8 libX11 XmbDrawString                  XmbDrawString   ( bytes_text text y x gc fontset d dpy -- r )
8 libX11 XwcDrawString                  XwcDrawString   ( num_wchars text y x gc fontset d dpy -- r )
8 libX11 XmbDrawImageString             XmbDrawImageString      ( bytes_text text y x gc fontset d dpy -- r )
8 libX11 XwcDrawImageString             XwcDrawImageString      ( num_wchars text y x gc fontset d dpy -- r )
4 libX11 XOpenIM                        XOpenIM ( res_class res_name rdb dpy -- XIM )
1 libX11 XCloseIM                       XCloseIM        ( im -- status )
4 libX11 XGetIMValues_1                 XGetIMValues    ( ...im -- string )
6 libX11 XGetIMValues_2                 XGetIMValues    ( ...im -- string )
8 libX11 XGetIMValues_3                 XGetIMValues    ( ...im -- string )
4 libX11 XSetIMValues_1                 XSetIMValues    ( ... im -- string )
6 libX11 XSetIMValues_2                 XSetIMValues    ( ... im -- string )
8 libX11 XSetIMValues_3                 XSetIMValues    ( ... im -- string )
1 libX11 XDisplayOfIM                   XDisplayOfIM    ( im -- dpy )
1 libX11 XLocaleOfIM                    XLocaleOfIM     ( im -- string )
4 libX11 XCreateIC_1                    XCreateIC       ( im -- XIC )
6 libX11 XCreateIC_2                    XCreateIC       ( im -- XIC )
8 libX11 XCreateIC_3                    XCreateIC       ( im -- XIC )
&10 libX11 XCreateIC_4                  XCreateIC       ( im -- XIC )
&12 libX11 XCreateIC_5                  XCreateIC       ( im -- XIC )
1 libX11 XCreateIC                      XCreateIC       ( im -- XIC )
1 libX11 XDestroyIC                     XDestroyIC      ( ic -- r )
1 libX11 XSetICFocus                    XSetICFocus     ( ic -- r )
1 libX11 XUnsetICFocus                  XUnsetICFocus   ( ic -- r )
1 libX11 XwcResetIC                     XwcResetIC      ( ic -- wstring )
1 libX11 XmbResetIC                     XmbResetIC      ( ic -- string )
4 libX11 XSetICValues_1                 XSetICValues    ( ... ic -- string )
6 libX11 XSetICValues_2                 XSetICValues    ( ... ic -- string )
8 libX11 XSetICValues_3                 XSetICValues    ( ... ic -- string )
4 libX11 XGetICValues_1                 XGetICValues    ( ... ic -- string )
6 libX11 XGetICValues_2                 XGetICValues    ( ... ic -- string )
8 libX11 XGetICValues_3                 XGetICValues    ( ... ic -- string )
1 libX11 XIMOfIC                        XIMOfIC ( ic -- XIM )
2 libX11 XFilterEvent                   XFilterEvent    ( w event -- flag )
6 libX11 XmbLookupString                XmbLookupString ( status_r keysym_r bytes_buffer buffer_r event ic -- n )
6 libX11 XwcLookupString                XwcLookupString ( status_r keysym_r wchars_buffer buffer_r event ic -- n )
[IFDEF] has-utf8
6 libX11 Xutf8LookupString              Xutf8LookupString ( status_r keysym_r wchars_buffer buffer_r event ic -- n )
[THEN]
4 libX11 XVaCreateNestedList_1          XVaCreateNestedList     ( ...unused -- vanestedlist )
6 libX11 XVaCreateNestedList_2          XVaCreateNestedList     ( ...unused -- vanestedlist )
8 libX11 XVaCreateNestedList_3          XVaCreateNestedList     ( ...unused -- vanestedlist )
&10 libX11 XVaCreateNestedList_4          XVaCreateNestedList     ( ...unused -- vanestedlist )
6 libX11 XRegisterIMInstantiateCallback XRegisterIMInstantiateCallback  ( client_data callback res_class res_name rdb dpy -- flag )
6 libX11 XUnregisterIMInstantiateCallbac        XUnregisterIMInstantiateCallback        ( client_data callback res_class res_name rdb dpy -- flag )
3 libX11 XInternalConnectionNumbers     XInternalConnectionNumbers      ( count_r fd_r dpy -- status )
2 libX11 XProcessInternalConnection     XProcessInternalConnection      ( fd dpy -- r )
3 libX11 XAddConnectionWatch            XAddConnectionWatch     ( client_data callback dpy -- status )
3 libX11 XRemoveConnectionWatch         XRemoveConnectionWatch  ( client_data callback dpy -- status )

\ Xutil.h
\ The following functions are not performed by the XServer, but in Xlib.

0 libX11 XAllocClassHint                XAllocClassHint ( -- classhint* )
0 libX11 XAllocIconSize                 XAllocIconSize  ( -- iconsize* )
0 libX11 XAllocSizeHints                XAllocSizeHints ( -- sizehints* )
0 libX11 XAllocStandardColormap         XAllocStandardColormap  ( -- stdcmap* )
0 libX11 XAllocWMHints                  XAllocWMHints   ( -- wmhints* )
2 libX11 XClipBox                       XClipBox        ( rect reg -- r )
0 libX11 XCreateRegion                  XCreateRegion   ( -- reg )
0 libX11 XDefaultString                 XDefaultString  ( -- char* )
3 libX11 XDeleteContext                 XDeleteContext  ( context rid dpy -- n )
1 libX11 XDestroyRegion                 XDestroyRegion  ( reg -- r )
1 libX11 XEmptyRegion                   XEmptyRegion    ( reg -- r )
2 libX11 XEqualRegion                   XEqualRegion    ( r1 r2 -- r )
4 libX11 XFindContext                   XFindContext    ( data_r context rid dpy -- n )
3 libX11 XGetClassHint                  XGetClassHint   ( class_hints_r w dpy -- status )
4 libX11 XGetIconSizes                  XGetIconSizes   ( count_r size_list_r w dpy -- status )
3 libX11 XGetNormalHints                XGetNormalHints ( hints_r w dpy -- status )
5 libX11 XGetRGBColormaps               XGetRGBColormaps        ( prop count_r stdcmap_r w dpy -- status )
4 libX11 XGetSizeHints                  XGetSizeHints   ( prop hints_r w dpy -- status )
4 libX11 XGetStandardColormap           XGetStandardColormap    ( prop colormap_r w dpy -- status )
4 libX11 XGetTextProperty               XGetTextProperty        ( prop text_prop_r w dpy -- status )
4 libX11 XGetVisualInfo                 XGetVisualInfo  ( nitems_r vinfo_templ vinfo_mask dpy -- vinfo* )
3 libX11 XGetWMClientMachine            XGetWMClientMachine     ( text_prop_r w dpy -- status )
2 libX11 XGetWMHints                    XGetWMHints     ( w dpy -- WMHints* )
3 libX11 XGetWMIconName                 XGetWMIconName  ( text_prop_r w dpy -- status )
3 libX11 XGetWMName                     XGetWMName      ( text_prop_r w dpy -- status )
4 libX11 XGetWMNormalHints              XGetWMNormalHints       ( supplied_r hints_r w dpy -- status )
5 libX11 XGetWMSizeHints                XGetWMSizeHints ( prop supplied_r hints_r w dpy -- status )
3 libX11 XGetZoomHints                  XGetZoomHints   ( zhints_r w dpy -- status )
3 libX11 XIntersectRegion               XIntersectRegion        ( dr_r srb sra -- r )
3 libX11 XConvertCase                   XConvertCase    ( upper* lower* sym -- r )
5 libX11 XLookupString                  XLookupString   ( composestatus* keysym_r bufsize buffer event -- n )
5 libX11 XMatchVisualInfo               XMatchVisualInfo        ( vinfo_r class depth screen dpy -- status )
3 libX11 XOffsetRegion                  XOffsetRegion   ( dy dx reg -- r )
3 libX11 XPointInRegion                 XPointInRegion  ( y x reg -- flag )
3 libX11 XPolygonRegion                 XPolygonRegion  ( fill_rile n points -- reg )
5 libX11 XRectInRegion                  XRectInRegion   ( h w y x reg -- n )
4 libX11 XSaveContext                   XSaveContext    ( data context rid dpy -- n )
3 libX11 XSetClassHint                  XSetClassHint   ( class_hints w dpy -- r )
4 libX11 XSetIconSizes                  XSetIconSizes   ( count size_list w dpy -- r )
3 libX11 XSetNormalHints                XSetNormalHints ( hints w dpy -- r )
5 libX11 XSetRGBColormaps               XSetRGBColormaps        ( prop count stdcmaps w dpy -- r )
4 libX11 XSetSizeHints                  XSetSizeHints   ( prop hints w dpy -- r )
8 libX11 XSetStandardProperties         XSetStandardProperties  ( sizehints argc argv icon_pixmap icon_name window_name w dpy -- r )
4 libX11 XSetTextProperty               XSetTextProperty        ( prop text_prop w dpy -- r )
3 libX11 XSetWMClientMachine            XSetWMClientMachine     ( text_prop w dpy -- r )
3 libX11 XSetWMHints                    XSetWMHints     ( wm_hints w dpy -- r )
3 libX11 XSetWMIconName                 XSetWMIconName  ( text_prop w dpy -- r )
3 libX11 XSetWMName                     XSetWMName      ( text_prop w dpy -- r )
3 libX11 XSetWMNormalHints              XSetWMNormalHints       ( hints w dpy -- r )
9 libX11 XSetWMProperties               XSetWMProperties        ( class_hints wm_hints normal_hints argc argv icon_name window_name w dpy -- r )
9 libX11 XmbSetWMProperties             XmbSetWMProperties      ( class_hints wm_hints normal_hints argc argv icon_name window_name w dpy -- r )
4 libX11 XSetWMSizeHints                XSetWMSizeHints ( prop hints w dpy -- r )
3 libX11 XSetRegion                     XSetRegion      ( reg gc dpy -- r )
4 libX11 XSetStandardColormap           XSetStandardColormap    ( prop colormap w dpy -- r )
3 libX11 XSetZoomHints                  XSetZoomHints   ( zhints w dpy -- r )
3 libX11 XShrinkRegion                  XShrinkRegion   ( dy dx reg -- r )
3 libX11 XStringListToTextProperty      XStringListToTextProperty       ( text_prop_r count list -- status )
3 libX11 XSubtractRegion                XSubtractRegion ( dr_r srb sra -- r )
5 libX11 XmbTextListToTextProperty      XmbTextListToTextProperty       ( text_prop_r style count list dpy -- n )
5 libX11 XwcTextListToTextProperty      XwcTextListToTextProperty       ( text_prop_r style count list dpy -- n )
1 libX11 XwcFreeStringList              XwcFreeStringList       ( list -- r )
3 libX11 XTextPropertyToStringList      XTextPropertyToStringList       ( count_r list_r text_prop -- status )
4 libX11 XmbTextPropertyToTextList      XmbTextPropertyToTextList       ( count_r list_r text_prop dpy -- n )
4 libX11 XwcTextPropertyToTextList      XwcTextPropertyToTextList       ( count_r list_r text_prop dpy -- n )
3 libX11 XUnionRectWithRegion           XUnionRectWithRegion    ( dest_reg_r src_reg rect -- r )
3 libX11 XUnionRegion                   XUnionRegion    ( dr_r srb sra -- r )
&10 libX11 XWMGeometry                  XWMGeometry     ( gravity_r h_r w_r y_r x_r hints border_w default_geometry user_geometry screen_nr dpy -- n )
3 libX11 XXorRegion                     XXorRegion      ( dr_r srb sra -- r )

/* **************************************************************
 *
 * Memory Management
 *
 ****************************************************************/

1 libX11 Xpermalloc                     Xpermalloc      ( size -- addr )
1 libX11 XrmStringToQuark               XrmStringToQuark        ( string -- quark )
1 libX11 XrmPermStringToQuark           XrmPermStringToQuark    ( string -- quark )
1 libX11 XrmQuarkToString               XrmQuarkToString        ( quark -- string )
0 libX11 XrmUniqueQuark                 XrmUniqueQuark  ( -- quark )
2 libX11 XrmStringToQuarkList           XrmStringToQuarkList    ( quarks string -- r )
3 libX11 XrmStringToBindingQuarkList    XrmStringToBindingQuarkList     ( quarks bindings string -- r )

struct{
    cell size
    cell addr
} XrmValue

1 libX11 XrmDestroyDatabase             XrmDestroyDatabase      ( dbase -- r )
5 libX11 XrmQPutResource                XrmQPutResource ( value type quarks bindings dbase -- r )
4 libX11 XrmPutResource                 XrmPutResource  ( value type spec dbase -- r )
4 libX11 XrmQPutStringResource          XrmQPutStringResource   ( value quarks bindings dbase -- r )
3 libX11 XrmPutStringResource           XrmPutStringResource    ( value spec dbase -- r )
2 libX11 XrmPutLineResource             XrmPutLineResource      ( line dbase -- r )
5 libX11 XrmQGetResource                XrmQGetResource ( value_r quark_t_r quark_c quark_n dbase -- r )
5 libX11 XrmGetResource                 XrmGetResource  ( value_r str_t_r str_c str_n dbase -- flag )
5 libX11 XrmQGetSearchList              XrmQGetSearchList       ( list_len list_r classes names dbase -- flag )
5 libX11 XrmQGetSearchResource          XrmQGetSearchResource   ( value_r type_r class name list -- flag )
2 libX11 XrmSetDatabase                 XrmSetDatabase  ( dbase dpy -- r )
1 libX11 XrmGetDatabase                 XrmGetDatabase  ( dpy -- dbase )
1 libX11 XrmGetFileDatabase             XrmGetFileDatabase      ( filename -- dbase )
3 libX11 XrmCombineFileDatabase         XrmCombineFileDatabase  ( flag dbase* filename -- status )
1 libX11 XrmGetStringDatabase           XrmGetStringDatabase    ( string -- dbase )
2 libX11 XrmPutFileDatabase             XrmPutFileDatabase      ( string dbase -- r )
2 libX11 XrmMergeDatabases              XrmMergeDatabases       ( dbase* dbase -- r )
3 libX11 XrmCombineDatabase             XrmCombineDatabase      ( flag dbase* dbase )
6 libX11 XrmEnumerateDatabase           XrmEnumerateDatabase    ( closure callback mode class_prefix name_prefix db -- flag )
1 libX11 XrmLocaleOfDatabase            XrmLocaleOfDatabase     ( dbase -- string )
6 libX11 XrmParseCommand                XrmParseCommand ( argv_io argc_io name table-count table dbase -- r )

\ X extensions

B libXext XShmPutImage                  XShmPutImage            ( send_event h w dy dx sy sx im gc win dpy -- status )

base !

include Xstring.fs

Module;
