\ X11 interface

Vocabulary X11

also X11 definitions

library: libX11.so.6
library: libXext.so.6 \ depends libX11

base @ hex

synonym has-utf8 noop
synonym has-png noop
synonym has-xft noop

extern: int XGetModifierMapping( int ); ( dpy -- modmap )
extern: int XNewModifiermap( int ); ( maxkeys -- modmap )
extern: int XInitImage( int ); ( image -- status )
extern: int XOpenDisplay( int ); ( name -- dpy )
extern: int XDisplayName( int ); ( string -- string )
extern: int XKeysymToString( int ); ( keysym -- string )
extern: int XGContextFromGC( int ); ( gc -- gcontext )
extern: int XStringToKeysym( int ); ( string -- keysym )
extern: int XMaxRequestSize( int ); ( dpy -- n )
extern: int XExtendedMaxRequestSize( int ); ( dpy -- n )
extern: int XResourceManagerString( int ); ( dpy -- string )
extern: int XScreenResourceString( int ); ( screen -- string )
extern: int XDisplayMotionBufferSize( int ); ( dpy -- u )
extern: int XVisualIDFromVisual( int ); ( visual -- visualID )
extern: int XLockDisplay( int ); ( dpy -- r )
extern: int XUnlockDisplay( int ); ( dpy -- r )
extern: int XAddExtension( int ); ( dpy -- extcodes )
extern: int XEHeadOfExtensionList( int ); ( object -- extdata** )
extern: int XDefaultRootWindow( int ); ( dpy -- window )
extern: int XRootWindowOfScreen( int ); ( screen -- window )
extern: int XDefaultVisualOfScreen( int ); ( screen -- visual )
extern: int XDefaultGCOfScreen( int ); ( screen -- gc )
extern: int XBlackPixelOfScreen( int ); ( screen -- u )
extern: int XWhitePixelOfScreen( int ); ( screen -- u )
extern: int XNextRequest( int ); ( dpy -- u )
extern: int XLastKnownRequestProcessed( int ); ( dpy -- u )
extern: int XServerVendor( int ); ( dpy -- string )
extern: int XDisplayString( int ); ( dpy -- string )
extern: int XDefaultColormapOfScreen( int ); ( screen -- colormap )
extern: int XDisplayOfScreen( int ); ( screen -- dpy )
extern: int XDefaultScreenOfDisplay( int ); ( dpy -- screen )
extern: int XEventMaskOfScreen( int ); ( screen -- mask )
extern: int XScreenNumberOfScreen( int ); ( screen -- n )
extern: int XSetErrorHandler( int ); ( handler -- errorhandler )
extern: int XSetIOErrorHandler( int ); ( handler -- ioerrorhandler )
extern: int XFreeStringList( int ); ( list -- r )
extern: int XActivateScreenSaver( int ); ( dpy -- r )
extern: int XAutoRepeatOff( int ); ( dpy -- r )
extern: int XAutoRepeatOn( int ); ( dpy -- r )
extern: int XBitmapBitOrder( int ); ( dpy -- n )
extern: int XBitmapPad( int ); ( dpy -- n )
extern: int XBitmapUnit( int ); ( dpy -- n )
extern: int XCellsOfScreen( int ); ( screen -- n )
extern: int XCloseDisplay( int ); ( dpy -- r )
extern: int XConnectionNumber( int ); ( dpy -- r )
extern: int XDefaultDepthOfScreen( int ); ( screen -- i )
extern: int XDefaultScreen( int ); ( dpy -- i )
extern: int XDoesBackingStore( int ); ( screen -- i )
extern: int XDoesSaveUnders( int ); ( screen -- flag )
extern: int XDisableAccessControl( int ); ( dpy -- r )
extern: int XEnableAccessControl( int ); ( dpy -- r )
extern: void XFlush( int ); ( dpy -- r )
extern: int XFree( int ); ( data -- r )
extern: int XFreeExtensionList( int ); ( list -- r )
extern: int XFreeFontNames( int ); ( list -- r )
extern: int XFreeFontPath( int ); ( list -- r )
extern: int XFreeModifiermap( int ); ( modmap -- r )
extern: int XGrabServer( int ); ( dpy -- r )
extern: int XHeightMMOfScreen( int ); ( screen -- n )
extern: int XHeightOfScreen( int ); ( screen -- n )
extern: int XImageByteOrder( int ); ( dpy -- n )
extern: int XMaxCmapsOfScreen( int ); ( screen -- n )
extern: int XMinCmapsOfScreen( int ); ( screen -- n )
extern: int XNoOp( int ); ( dpy -- r )
extern: int XPending( int ); ( dpy -- n )
extern: int XPlanesOfScreen( int ); ( screen -- n )
extern: int XProtocolRevision( int ); ( dpy -- n )
extern: int XProtocolVersion( int ); ( dpy -- n )
extern: int XQLength( int ); ( dpy -- n )
extern: int XRefreshKeyboardMapping( int ); ( event_map -- r )
extern: int XResetScreenSaver( int ); ( dpy -- r )
extern: int XScreenCount( int ); ( dpy -- n )
extern: int XUngrabServer( int ); ( dpy -- r )
extern: int XVendorRelease( int ); ( dpy -- n )
extern: int XWidthMMOfScreen( int ); ( screen -- n )
extern: int XWidthOfScreen( int ); ( screen -- n )
extern: int XSetLocaleModifiers( int ); ( modifier_list -- string )
extern: int XCloseOM( int ); ( om -- status )
extern: int XSetOMValues( int ); ( ...om -- string )
extern: int XGetOMValues( int ); ( ...om -- string )
extern: int XDisplayOfOM( int ); ( om -- dpy )
extern: int XLocaleOfOM( int ); ( om -- string )
extern: int XCreateOC( int ); ( ...om -- XOC )
extern: int XDestroyOC( int ); ( oc -- r )
extern: int XOMOfOC( int ); ( oc -- XOM )
extern: int XSetOCValues( int ); ( ...oc -- string )
extern: int XGetOCValues( int ); ( ...oc -- string )
extern: int XBaseFontNameListOfFontSet( int ); ( fontset -- string )
extern: int XLocaleOfFontSet( int ); ( fontset -- string )
extern: int XContextDependentDrawing( int ); ( fontset -- flag )
extern: int XDirectionalDependentDrawing( int ); ( fontset -- flag )
extern: int XContextualDrawing( int ); ( fontset -- flag )
extern: int XExtentsOfFontSet( int ); ( fontset -- fontsetextents )
extern: int XCloseIM( int ); ( im -- status )
extern: int XDisplayOfIM( int ); ( im -- dpy )
extern: int XLocaleOfIM( int ); ( im -- string )
extern: int XCreateIC( int ); ( im -- XIC )
extern: int XDestroyIC( int ); ( ic -- r )
extern: int XSetICFocus( int ); ( ic -- r )
extern: int XUnsetICFocus( int ); ( ic -- r )
extern: int XwcResetIC( int ); ( ic -- wstring )
extern: int XmbResetIC( int ); ( ic -- string )
extern: int XIMOfIC( int ); ( ic -- XIM )
extern: int XDestroyRegion( int ); ( reg -- r )
extern: int XEmptyRegion( int ); ( reg -- r )
extern: int XwcFreeStringList( int ); ( list -- r )
extern: int Xpermalloc( int ); ( size -- addr )
extern: int XrmStringToQuark( int ); ( string -- quark )
extern: int XrmPermStringToQuark( int ); ( string -- quark )
extern: int XrmQuarkToString( int ); ( quark -- string )
extern: int XrmDestroyDatabase( int ); ( dbase -- r )
extern: int XrmGetDatabase( int ); ( dpy -- dbase )
extern: int XrmGetFileDatabase( int ); ( filename -- dbase )
extern: int XrmGetStringDatabase( int ); ( string -- dbase )
extern: int XrmLocaleOfDatabase( int ); ( dbase -- string )

extern: int XrmInitialize( );   ( -- r )
extern: int XInitThreads( );    ( -- status )
extern: int XAllPlanes( );      ( -- u )
extern: int XAllocClassHint( ); ( -- classhint* )
extern: int XAllocIconSize( );  ( -- iconsize* )
extern: int XAllocSizeHints( ); ( -- sizehints* )
extern: int XAllocStandardColormap( );  ( -- stdcmap* )
extern: int XAllocWMHints( );   ( -- wmhints* )
extern: int XCreateRegion( );   ( -- reg )
extern: int XDefaultString( );  ( -- char* )
extern: int XrmUniqueQuark( );  ( -- quark )

extern: int XLoadQueryFont( int , int ); ( dpy name -- fontstruct )
extern: int XAllocColor( int , int , int ); ( color colormap dpy -- status )
extern: int XGetWindowAttributes( int , int , int ); ( dpy win windows_attributes_r -- status )
extern: int XChangeWindowAttributes( int , int , int , int ); ( dpy win valuemask attributes -- r )
extern: int XGetErrorText( int , int , int , int ); ( dpy code buffer_r length -- r )
extern: int XSupportsLocale( ); ( -- flag )
extern: int XGetVisualInfo( int , int , int , int ); ( dpy vinfo_mask vinfo_templ nitems_r -- vinfo* )
extern: int XCreateColormap( int , int , int , int ); ( dpy w visual alloc -- colormap )
extern: int XOpenIM( int , int , int , int ); ( dpy rdb res_name res_class -- XIM )
AliasedExtern: XGetIMValues_1 void * XGetIMValues( int , int , int , int ); ( im ... -- string )
AliasedExtern: XGetIMValues_2 void * XGetIMValues( int , int , int , int , int , int ); ( im ... -- string )
AliasedExtern: XGetIMValues_3 void * XGetIMValues( int , int , int , int , int , int , int , int ); ( im ... -- string )
AliasedExtern: XSetIMValues_1 void * XSetIMValues( int , int , int , int ); ( im ... -- string )
AliasedExtern: XSetIMValues_2 void * XSetIMValues( int , int , int , int , int , int ); ( im ... -- string )
AliasedExtern: XSetIMValues_3 void * XSetIMValues( int , int , int , int , int , int , int , int ); ( im ... -- string )
AliasedExtern: XVaCreateNestedList_1 void * XVaCreateNestedList( int , int , int , int ); ( ...unused -- vanestedlist )
AliasedExtern: XVaCreateNestedList_2 void * XVaCreateNestedList( int , int , int , int , int , int ); ( ...unused -- vanestedlist )
AliasedExtern: XVaCreateNestedList_3 void * XVaCreateNestedList( int , int , int , int , int , int , int , int ); ( ...unused -- vanestedlist )
AliasedExtern: XVaCreateNestedList_4 void * XVaCreateNestedList( int , int , int , int , int , int , int , int , int , int ); ( ...unused -- vanestedlist )
AliasedExtern: XCreateIC_1 void * XCreateIC( int , int , int , int ); ( im -- XIC )
AliasedExtern: XCreateIC_2 void * XCreateIC( int , int , int , int , int , int ); ( im -- XIC )
AliasedExtern: XCreateIC_3 void * XCreateIC( int , int , int , int , int , int , int , int ); ( im -- XIC )
AliasedExtern: XCreateIC_4 void * XCreateIC( int , int , int , int , int , int , int , int , int , int ); ( im -- XIC )
AliasedExtern: XCreateIC_5 void * XCreateIC( int , int , int , int , int , int , int , int , int , int , int , int ); ( im -- XIC )
extern: void * XCreateGC( int , int , int , int ); ( dpy d valuemask values -- gc )
extern: int XDestroyWindow( int , int ); ( dpy win -- r )
extern: int XKeycodeToKeysym( int , int , int ); ( dpy keycode index -- keysym )
extern: int XCreateFontSet( int , int , int , int , int ); ( dpy base_font_name_list missing_charset_list missing-charset_count def_string -- fontset )
extern: int XFreeColors( int , int , int , int , int ); ( dpy colormap pixels npixels planes -- r )
extern: int XCreateFontCursor( int , int ); ( dpy shape -- cursor )
extern: int XChangeGC( int , int , int , int ); ( dpy gc valuemask values -- r )
extern: int XSetFunction( int , int , int ); ( dpy gc function -- r )
extern: int XStoreBytes( int , int , int ); ( dpy bytes nbytes -- r )
extern: int XSetSelectionOwner( int , int , int , int ); ( dpy selection owner time -- r )
extern: int XChangeProperty( int , int , int , int , int , int , int , int ); ( dpy w property type format mode data elements -- r )
extern: int XConvertSelection( int , int , int , int , int , int ); ( dpy selection target property requestor time -- r )
extern: int XGetSelectionOwner( int , int ); ( dpy atom -- window )
extern: int XFetchBytes( int , int ); ( dpy nbytesr -- buffer )
extern: int XCreateWindow( int , int , int , int , int , int , int , int , int , int , int , int ); ( dpy parent x y w h borderwidth depth class visual valuemask attribs -- window )
extern: int XGetWindowProperty( int , int , int , int , int , int , int , int , int , int , int , int ); ( dpy w property offset length delete req_type actual_typer actual_format_r nitems_r bytes_after_r prop_r -- n )
extern: int XDefineCursor( int , int , int ); ( dpy win cursor -- r )
extern: int XSetLineAttributes( int , int , int , int , int , int ); ( dpy gc line_width line_style cap_style join_style -- r )
extern: void XDrawLine( int , int , int , int , int , int , int ); ( dpy d gc x1 x2 y1 y2 -- )
extern: void XFillRectangle( int , int , int , int , int , int , int ); ( dpy d gc x y w h -- )
extern: void XFillPolygon( int , int , int , int , int , int , int ); ( dpy d gc points npoints shape mode -- )
extern: void XDrawLines( int , int , int , int , int , int ); ( dpy d gc points npoints mode -- )
extern: void XSetClipMask( int , int , int ); ( dpy gc pixmap -- )
extern: void XSetClipOrigin( int , int , int , int ); ( dpy gc clip_x_orig clip_y_orig -- )
extern: void XCopyArea( int , int , int , int , int , int , int , int , int , int ); ( dpy src dest gc x y w h dx dy -- )
extern: void XUnionRectWithRegion( int , int , int ); ( rect src_reg dest_reg_r -- )
extern: void XSetRegion( int , int , int ); ( dpy gc reg -- )
extern: int XCheckMaskEvent( int , int , int ); ( dpy event_mask event_r -- flag )
extern: void XNextEvent( int , int ); ( dpy event_r -- )
extern: void XSync( int , int ); ( dpy discard -- )
extern: int XQueryPointer( int , int , int , int , int , int , int , int , int ); ( dpy w root_r child_r root_x_r root_y_r win_x_r win_y_r mask_r -- flag )
[defined] has-utf8 [IF]
extern: int Xutf8LookupString( int , int , int , int , int , int ); ( ic event buffer_r wchars_buffer keysym_r status_r -- n )
[THEN]
extern: int XLookupString( int , int , int , int , int ); ( event buffer bufsize keysym_r composestatus* -- n )
extern: int XGetAtomName( int , int ); ( dpy atom -- name )
extern: int XSendEvent( int , int , int , int , int ); ( dpy w propagate event_mask event_send -- status )
extern: void XTextExtents( int , int , int , int , int , int , int ); ( font_struct string nchars direction_r font_ascent_r font_descent_r overall_r -- )
extern: void XTextExtents16( int , int , int , int , int , int , int ); ( font_struct string nchars direction_r font_ascent_r font_descent_r overall_r -- )
extern: void XDrawText( int , int , int , int , int , int , int ); ( dpy d gc x y items nitems -- r )
extern: void XDrawText16( int , int , int , int , int , int , int ); ( dpy d gc x y items nitems -- r )
extern: void XFreePixmap( int , int ); ( dpy pixmap -- )
extern: int XCreatePixmap( int , int , int , int , int ); ( dpy d w h depth -- pixmap )
extern: void * XCreateImage( int , int , int , int , int , int , int , int , int , int ); ( dpy visual depth format offset data w h bmpad b/line -- image )
extern: void * XGetImage( int , int , int , int , int , int , int , int ); ( dpy d x y w h planemask format -- image )
extern: int XInternAtom( int , int , int ); ( dpy atomname flag -- atom )
extern: int XListPixmapFormats( int , int ); ( dpy count_r -- pixmapformatvalues )
extern: void XSetTransientForHint( int , int , int ); ( dpy w propw -- )
extern: void XCopyPlane( int , int , int , int , int , int , int , int , int , int , int ); ( dpy src dest gc x y w h dx dy plane -- )
extern: void XFreeColormap( int , int ); ( dpy colormap -- )
extern: void XFreeGC( int , int ); ( dpy gc -- )
extern: int XGetGeometry( int , int , int , int , int , int , int , int , int ); ( dpy d root_r x_r y_r w_r h_r borderw_r depth_r -- status )
extern: int XGrabPointer( int , int , int , int , int , int , int , int , int ); ( time cursor confine_to keyboard_mode pointer_mode owner_events grab_window dpy -- n )
extern: void XMapRaised( int , int ); ( dpy w -- )
extern: void XMapWindow( int , int ); ( dpy w -- o)
extern: void XMoveResizeWindow( int , int , int , int , int , int ); ( dpy win x y w h -- r )
extern: void XMoveWindow( int , int , int , int ); ( dpy win x y -- )
extern: int XParseGeometry( int , int , int , int , int ); ( parsestring x_r y_r w_r h_r -- n )
extern: void XPutImage( int , int , int , int , int , int , int , int , int , int ); ( dpy d gc image s_x s_y d_x d_y w h -- )
extern: void XResizeWindow( int , int , int , int ); ( dpy win w h -- )
extern: void XSetBackground( int , int , int ); ( dpy gc background -- )
extern: void XSetForeground( int , int , int ); ( dpy gc fg -- )
extern: void XSetIconName( int , int , int ); ( dpy win icon_name -- )
extern: void XSetInputFocus( int , int , int , int ); ( dpy focus revert_to time -- )
extern: void XStoreName( int , int , int ); ( dpy win window_name -- )
extern: void XUngrabPointer( int , int ); ( dpy time -- )
extern: void XUnmapWindow( int , int ); ( dpy w -- )
extern: void XWarpPointer( int , int , int , int , int , int , int , int , int ); ( dpy src_w dest_w src_x src_y src_w src_h dest_x dest_y -- )
extern: void XSelectInput( int , int , int ); ( dpy w event_mask -- )
extern: void XWindowEvent( int , int , int , int ); ( dpy w event_mask event_r -- )
AliasedExtern: XSetICValues_1 int XSetICValues( int , int , int , int ); ( ic ... -- string )
AliasedExtern: XSetICValues_2 int XSetICValues( int , int , int , int , int , int ); ( ic ... -- string )
AliasedExtern: XSetICValues_3 int XSetICValues( int , int , int , int , int , int , int , int ); ( ic ... -- string )
extern: int XFilterEvent( int , int ); ( event w -- flag )
extern: void XIntersectRegion( int , int , int ); ( sra srb dr_r -- )
extern: void XSetClassHint( int , int , int ); ( dpy w class_hints -- )
extern: void XSetTextProperty( int , int , int , int ); ( dpy w text_prop prop -- )
extern: void XSetWMHints( int , int , int ); ( dpy w wm_hints -- )
extern: void XSetWMNormalHints( int , int , int ); ( dpy w hints -- )
extern: int XCreateSimpleWindow( int , int , int , int , int , int , int , int , int ); ( dpy parent x y w h bwidth border bg -- window )

\ Unused stuff, machine converted

\ -1 extern: _XPrivDisplay               _XPrivDisplay   ( -- addr )
\ -1 extern: _Xdebug                       _Xdebug         ( -- addr )
extern: int XQueryFont( int , int ); ( XID dpy -- fontstruct )
extern: int XGetMotionEvents( int , int , int , int , int ); ( neventsr stop start w dpy -- timecoord )
extern: int XDeleteModifiermapEntry( int , int , int ); ( mod keycode modmap -- modmap )
extern: int XInsertModifiermapEntry( int , int , int ); ( mod keycode modmap -- modmap )
extern: int XGetSubImage( int , int , int , int , int , int , int , int , int , int , int ); ( dy dx dimage format planemask h w y x d dpy -- image )
extern: int XFetchBuffer( int , int , int ); ( buffer nbytesr dpy -- buffer )
extern: int XGetAtomNames( int , int , int , int ); ( namesr count atoms dpy -- status )
extern: int XGetDefault( int , int , int ); ( option program dpy --  string )
extern: int XInternAtoms( int , int , int , int , int ); ( atoms flag count names dpy -- status )
extern: int XCopyColormapAndFree( int , int ); ( colormap dpy -- colormap )
extern: int XCreatePixmapCursor( int , int , int , int , int , int , int ); ( y x bgcol fgcol mask source dpy -- cursor )
extern: int XCreateGlyphCursor( int , int , int , int , int , int , int ); ( bgcol fgcol maskc sourcec maskfont sourcefont dpy -- cursor )
extern: int XLoadFont( int , int ); ( name dpy -- font )
extern: int XFlushGC( int , int ); ( gc dpy -- r )
extern: int XCreateBitmapFromData( int , int , int , int , int ); ( h w data d dpy -- pixmap )
extern: int XCreatePixmapFromBitmapData( int , int , int , int , int , int , int , int ); ( depth bg fg h w data d dpy -- pixmap )
extern: int XListInstalledColormaps( int , int , int ); ( num_r w dpy -- colormap* )
extern: int XListFonts( int , int , int , int ); ( actual_count_r maxnames pattern dpy -- char** )
extern: int XListFontsWithInfo( int , int , int , int , int ); ( info_r count_r maxnames pattern dpy -- char** )
extern: int XGetFontPath( int , int ); ( npaths_r dpy -- char** )
extern: int XListExtensions( int , int ); ( nextensions_r dpy -- char** )
extern: int XListProperties( int , int , int ); ( num_prop_r w dpy -- atom* )
extern: int XListHosts( int , int , int ); ( status_r nhosts_r dpy -- hostaddr* )
extern: int XLookupKeysym( int , int ); ( index key_event -- keysym )
extern: int XGetKeyboardMapping( int , int , int , int ); ( keysym/keycode_r keycode_c first_kc dpy -- keysym* )
extern: int XInitExtension( int , int ); ( name dpy -- extcodes )
extern: int XFindOnExtensionList( int , int ); ( number structure -- extdata )
extern: int XRootWindow( int , int ); ( screen_nr dpy -- window )
extern: int XDefaultVisual( int , int ); ( screen_nr dpy -- visual )
extern: int XDefaultGC( int , int ); ( screen_nr dpy -- gc )
extern: int XBlackPixel( int , int ); ( screen_nr dpy -- u )
extern: int XWhitePixel( int , int ); ( screen_nr dpy -- u )
extern: int XDefaultColormap( int , int ); ( screen_nr dpy -- colormap )
extern: int XScreenOfDisplay( int , int ); ( screen_nr dpy -- screen )
extern: int XListDepths( int , int , int ); ( count_r screen_nr dpy -- int* )
extern: int XReconfigureWMWindow( int , int , int , int , int ); ( changes mask screen_nr w dpy -- status )
extern: int XGetWMProtocols( int , int , int , int ); ( count_r protocols_r w dpy -- status )
extern: int XSetWMProtocols( int , int , int , int ); ( count protocols w dpy -- status )
extern: int XIconifyWindow( int , int , int ); ( screen_nr w dpy -- status )
extern: int XWithdrawWindow( int , int , int ); ( screen_nr w dpy -- status )
extern: int XGetCommand( int , int , int , int ); ( argc_r argv_r w dpy -- status )
extern: int XGetWMColormapWindows( int , int , int , int ); ( count_r windows_r w dpy -- status )
extern: int XSetWMColormapWindows( int , int , int , int ); ( count colormap_windows w dpy -- status )
extern: int XAddHost( int , int ); ( host dpy -- r )
extern: int XAddHosts( int , int , int ); ( num hosts dpy -- r )
extern: int XAddToExtensionList( int , int ); ( extdata structure -- r )
extern: int XAddToSaveSet( int , int ); ( w dpy -- r )
extern: int XAllocColorCells( int , int , int , int , int , int , int ); ( pixels pixels_r planes planemask_r contig colormap dpy -- status )
extern: int XAllocColorPlanes( int , int , int , int , int , int , int , int , int , int , int ); ( bmask_r gmask_r rmask_r blues greens reds colors pixels_r contig colormap dpy -- status )
extern: int XAllocNamedColor( int , int , int , int , int ); ( exact_def_r screen_def_r cname colormap dpy -- status )
extern: int XAllowEvents( int , int , int ); ( time event_mode dpy -- r )
extern: int XBell( int , int ); ( percent dpy -- r )
extern: int XChangeActivePointerGrab( int , int , int , int ); ( time cursor event_mask dpy -- r )
extern: int XChangeKeyboardControl( int , int , int ); ( values valuemask dpy -- r )
extern: int XChangeKeyboardMapping( int , int , int , int , int ); ( num_codes keysyms keysyms/keycode first_kc dpy -- r )
extern: int XChangePointerControl( int , int , int , int , int , int ); ( threshold accel_denom accel_num do_thres do_accel dpy -- r )
extern: int XChangeSaveSet( int , int , int ); ( change_mode w dpy -- r )
extern: int XCheckIfEvent( int , int , int , int ); ( arg predicate event_return dpy -- flag )
extern: int XCheckTypedEvent( int , int , int ); ( event_r event_type dpy -- flag )
extern: int XCheckTypedWindowEvent( int , int , int , int ); ( event_r event_type w dpy -- flag )
extern: int XCheckWindowEvent( int , int , int , int ); ( event_r event_mask w dpy -- flag )
extern: int XCirculateSubwindows( int , int , int ); ( direction w dpy -- r )
extern: int XCirculateSubwindowsDown( int , int ); ( w dpy -- r )
extern: int XCirculateSubwindowsUp( int , int ); ( w dpy -- r )
extern: int XClearArea( int , int , int , int , int , int , int ); ( exposures h w y x w dpy -- r )
extern: int XClearWindow( int , int ); ( w dpy -- r )
extern: int XConfigureWindow( int , int , int , int ); ( values value_mask w dpy -- r )
extern: int XCopyGC( int , int , int , int ); ( dest valuemask src dpy -- r )
extern: int XDefaultDepth( int , int ); ( screen_nr dpy -- i )
extern: int XDeleteProperty( int , int , int ); ( atom w dpy -- r )
extern: int XDestroySubwindows( int , int ); ( w dpy -- r )
extern: int XDisplayCells( int , int ); ( screen_nr dpy -- i )
extern: int XDisplayHeight( int , int ); ( screen_nr dpy -- i )
extern: int XDisplayHeightMM( int , int ); ( screen_nr dpy -- i )
extern: int XDisplayKeycodes( int , int , int ); ( min_keycodes_r max_keycodes_r dpy -- r )
extern: int XDisplayPlanes( int , int ); ( screen_nr dpy -- i )
extern: int XDisplayWidth( int , int ); ( screen_nr dpy -- i )
extern: int XDisplayWidthMM( int , int ); ( screen_nr dpy -- i )
extern: int XDrawArc( int , int , int , int , int , int , int , int , int ); ( angle2 angle1 h w y x gc d dpy -- r )
extern: int XDrawArcs( int , int , int , int , int ); ( narcs arcs gc d dpy -- r )
extern: int XDrawImageString( int , int , int , int , int , int , int ); ( length string y x gc d dpy -- r )
extern: int XDrawImageString16( int , int , int , int , int , int , int ); ( length string y x gc d dpy -- r )
extern: int XDrawPoint( int , int , int , int , int ); ( y x gc d dpy -- r )
extern: int XDrawPoints( int , int , int , int , int , int ); ( mode npoints point gc d dpy -- r )
extern: int XDrawRectangle( int , int , int , int , int , int , int ); ( h w y x gc d dpy -- r )
extern: int XDrawRectangles( int , int , int , int , int ); ( nrects rects gc d dpy -- r )
extern: int XDrawSegments( int , int , int , int , int ); ( nsegments segments gc d dpy -- r )
extern: int XDrawString( int , int , int , int , int , int , int ); ( length string y x gc d dpy -- r )
extern: int XDrawString16( int , int , int , int , int , int , int ); ( length string y x gc d dpy -- r )
extern: int XEventsQueued( int , int ); ( mode dpy -- i )
extern: int XFetchName( int , int , int ); ( name_r w dpy -- status )
extern: int XFillArc( int , int , int , int , int , int , int , int , int ); ( angle2 angle1 h w y x gc d dpy -- r )
extern: int XFillArcs( int , int , int , int , int ); ( narcs arcs gc d dpy -- r )
extern: int XFillRectangles( int , int , int , int , int ); ( nrects rects gc d dpy -- r )
extern: int XForceScreenSaver( int , int ); ( mode dpy -- r )
extern: int XFreeCursor( int , int ); ( cursor dpy -- r )
extern: int XFreeFont( int , int ); ( fontstruct dpy -- r )
extern: int XFreeFontInfo( int , int , int ); ( actual_count free_info names -- r )
extern: int XGeometry( int , int , int , int , int , int , int , int , int , int , int , int , int ); ( hr wr yr xr yadder xadder fh fw bw default_pos pos screen dpy -- n )
extern: int XGetErrorDatabaseText( int , int , int , int , int , int ); (( int ); ( int , int , int ); ( value_r atom fontstruct -- flag )
extern: int XGetGCValues( int , int , int , int ); ( values_r valuemask gc dpy -- status )
extern: int XGetIconName( int , int , int ); ( icon_name-r w dpy -- status )
extern: int XGetInputFocus( int , int , int ); ( revert_to_r focus_r dpy -- r )
extern: int XGetKeyboardControl( int , int ); ( values_r dpy -- r )
extern: int XGetPointerControl( int , int , int , int ); ( threshold_r accel_denom_r accel_num_r dpy -- r )
extern: int XGetPointerMapping( int , int , int ); ( nmap map_r dpy -- n )
extern: int XGetScreenSaver( int , int , int , int , int ); ( allow_exposures_r prefer_blanking_r interval_r timeout_r dpy -- r )
extern: int XGetTransientForHint( int , int , int ); ( prop_w_r w dpy -- status )
extern: int XGrabButton( int , int , int , int , int , int , int , int , int ); ( cursor confine_to keyboard_mode pointer_mode owner_events grab_window modifiers button dpy -- r )
extern: int XGrabKey( int , int , int , int , int , int , int , int ); ( keyboard_mode pointer_mode owner_events grab_events grab_window modifiers keycode dpy -- r )
extern: int XGrabKeyboard( int , int , int , int , int , int ); ( time keyboard_mode pointer_mode owner_events grab_window dpy -- n )
extern: int XIfEvent( int , int , int , int ); ( arg predicate event_r dpy -- r )
extern: int XInstallColormap( int , int ); ( colormap dpy -- r )
extern: int XKeysymToKeycode( int , int ); ( keysym dpy -- keycode )
extern: int XKillClient( int , int ); ( resource dpy -- r )
\ 1 extern: XLastKnownRequestProcessed   XLastKnownRequestProcessed      ( dpy -- u )
extern: int XLookupColor( int , int , int , int , int ); ( screen_def_r exact_def_r color_name colormap dpy -- status )
extern: int XLowerWindow( int , int ); ( w dpy -- r )
extern: int XMapSubwindows( int , int ); ( w dpy -- r )
extern: int XMaskEvent( int , int , int ); ( event_r event_mask dpy -- r )
extern: int XParseColor( int , int , int , int ); ( exact_def_r spec colormap dpy -- status )
extern: int XPeekEvent( int , int ); ( event_r dpy -- r )
extern: int XPeekIfEvent( int , int , int , int ); ( arg predicate event_r dpy -- r )
extern: int XPutBackEvent( int , int ); ( event dpy -- r )
extern: int XQueryBestCursor( int , int , int , int , int , int ); ( h_r w_r h w d dpy -- status )
extern: int XQueryBestSize( int , int , int , int , int , int , int ); ( h_r w_r h w which_screen class dpy -- status )
extern: int XQueryBestStipple( int , int , int , int , int , int ); ( h_r w_r h w which_screen dpy -- status )
extern: int XQueryBestTile( int , int , int , int , int , int ); ( h_r w_r h w which_screen dpy -- status )
extern: int XQueryColor( int , int , int ); ( def_in_out colormap dpy -- r )
extern: int XQueryColors( int , int , int , int ); ( ncolors defs_in_out colormap dpy -- r )
extern: int XQueryExtension( int , int , int , int , int ); ( first_error_r first_event_r major_opcode_r name dpy -- flag )
extern: int XQueryKeymap( int , int ); ( keys_r dpy -- r )
extern: int XQueryTextExtents( int , int , int , int , int , int , int , int ); ( overall_r font_descent_r font_ascent_r direction_r nchars string font_id dpy -- r )
extern: int XQueryTextExtents16( int , int , int , int , int , int , int , int ); ( overall_r font_descent_r font_ascent_r direction_r nchars string font_id dpy -- r )
extern: int XQueryTree( int , int , int , int , int , int ); ( nchildren_r children_r parent_r root_r w dpy -- status )
extern: int XRaiseWindow( int , int ); ( w dpy -- r )
extern: int XReadBitmapFile( int , int , int , int , int , int , int , int ); ( y_hot_r x_hot_r bitmap_r height_r width_r filename d dpy -- n )
extern: int XReadBitmapFileData( int , int , int , int , int , int ); ( y_hot_r x_hot_r bitmap_r height_r width_r filename -- n )
extern: int XRebindKeysym( int , int , int , int , int , int ); ( bytes_string string mod_count list keysym dpy -- r )
extern: int XRecolorCursor( int , int , int , int ); ( bg fg cursor dpy -- r )
extern: int XRemoveFromSaveSet( int , int ); ( w dpy -- r )
extern: int XRemoveHost( int , int ); ( host dpy -- r )
extern: int XRemoveHosts( int , int , int ); ( num_hosts hosts dpy -- r )
extern: int XReparentWindow( int , int , int , int , int ); ( y x parent w dpy -- r )
extern: int XRestackWindows( int , int , int ); ( nwindows windows dpy -- r )
extern: int XRotateBuffers( int , int ); ( rotate dpy -- r )
extern: int XRotateWindowProperties( int , int , int , int , int ); ( npositions num_prop properties w dpy -- r )
extern: int XSetAccessControl( int , int ); ( mode dpy -- r )
extern: int XSetArcMode( int , int , int ); ( arc_mode gc dpy -- r )
extern: int XSetClipRectangles( int , int , int , int , int , int , int ); ( ordering n rectangles clip_y_orig clip_x_orig gc dpy -- r )
extern: int XSetCloseDownMode( int , int ); ( close_mode dpy -- r )
extern: int XSetCommand( int , int , int , int ); ( argc argv w dpy -- r )
extern: int XSetDashes( int , int , int , int , int ); ( n dash_list dash_ofset gc dpy -- r )
extern: int XSetFillRule( int , int , int ); ( fill_rule gc dpy -- r )
extern: int XSetFillStyle( int , int , int ); ( fill_style gc dpy -- r )
extern: int XSetFont( int , int , int ); ( font gc dpy -- r )
extern: int XSetFontPath( int , int , int ); ( ndirs directories dpy -- r )
extern: int XSetGraphicsExposures( int , int , int ); ( graphics_exposures gc dpy -- r )
extern: int XSetModifierMapping( int , int ); ( modmap dpy -- n )
extern: int XSetPlaneMask( int , int , int ); ( plane_mask gc dpy -- r )
extern: int XSetPointerMapping( int , int , int ); ( nmap map dpy -- n )
extern: int XSetScreenSaver( int , int , int , int , int ); ( allow_exposures prefer_blanking interval timeout dpy -- r )
extern: int XSetState( int , int , int , int , int , int ); ( plane_mask function bg fg gc dpy -- r )
extern: int XSetStipple( int , int , int ); ( stripple gc dpy -- r )
extern: int XSetSubwindowMode( int , int , int ); ( subwindow_mode gc dpy -- r )
extern: int XSetTSOrigin( int , int , int , int ); ( ts_y_orig ts_x_orig gc dpy -- r )
extern: int XSetTile( int , int , int ); ( tile gc dpy -- )
extern: int XSetWindowBackground( int , int , int ); ( bg_pixel w dpy -- )
extern: int XSetWindowBackgroundPixmap( int , int , int ); ( bg_pixmap w dpy -- r )
extern: int XSetWindowBorder( int , int , int ); ( border_pixel w dpy -- r )
extern: int XSetWindowBorderPixmap( int , int , int ); ( border_pixmap w dpy -- r )
extern: int XSetWindowBorderWidth( int , int , int ); ( width w dpy -- r )
extern: int XSetWindowColormap( int , int , int ); ( colormap w dpy -- r )
extern: int XStoreBuffer( int , int , int , int ); ( buffer nbytes bytes dpy -- r )
extern: int XStoreColor( int , int , int ); ( color colormap dpy -- r )
extern: int XStoreColors( int , int , int , int ); ( ncolors color colormap dpy -- r )
extern: int XStoreNamedColor( int , int , int , int , int ); ( flags pixel color colormap dpy -- r )
extern: int XTextWidth( int , int , int ); ( count string font_struct -- n )
extern: int XTextWidth16( int , int , int ); ( count string font_struct -- n )
extern: int XTranslateCoordinates( int , int , int , int , int , int , int , int ); ( child_r dest_y_r dest_x_r src_y src_x dest_w src_w dpy -- flag )
extern: int XUndefineCursor( int , int ); ( w dpy -- r )
extern: int XUngrabButton( int , int , int , int ); ( grab_window modifiers button dpy -- r )
extern: int XUngrabKey( int , int , int , int ); ( grab_window modifiers keycode dpy -- r )
extern: int XUngrabKeyboard( int , int ); ( time dpy -- r )
extern: int XUninstallColormap( int , int ); ( colormap dpy -- r )
extern: int XUnloadFont( int , int ); ( font dpy -- r )
extern: int XUnmapSubwindows( int , int ); ( w dpy -- r )
extern: int XWriteBitmapFile( int , int , int , int , int , int , int ); ( y_hot x_hot h w bitmap filename dpy -- r )
extern: int XOpenOM( int , int , int , int ); ( res_class res_name rdb dpy -- XOM )
extern: int XFreeFontSet( int , int ); ( fontset dpy -- r )
extern: int XFontsOfFontSet( int , int , int ); ( font_name_list font_struct_list font_set -- n )
extern: int XmbTextEscapement( int , int , int ); ( bytes_text text fontset -- n )
extern: int XwcTextEscapement( int , int , int ); ( num_wchars text fontset -- n )
extern: int XmbTextExtents( int , int , int , int , int ); ( overall_logical_r overall_ink_r bytes_text text fontset -- n )
extern: int XwcTextExtents( int , int , int , int , int ); ( overall_logical_r overall_ink_r num_wchars text fontset -- n )
extern: int XmbTextPerCharExtents( int , int , int , int , int , int , int , int , int ); ( overal_logical_r overall_ink_r num_chars buffer_size logical_extents_buffer ink_extents_buffer bytes_text text fontset -- status )
extern: int XwcTextPerCharExtents( int , int , int , int , int , int , int , int , int ); ( overal_logical_r overall_ink_r num_chars buffer_size logical_extents_buffer ink_extents_buffer num_wchars text fontset -- status )
extern: int XmbDrawText( int , int , int , int , int , int , int ); ( nitems text_items y x gc d dpy -- r )
extern: int XwcDrawText( int , int , int , int , int , int , int ); ( nitems text_items y x gc d dpy -- r )
extern: int XmbDrawString( int , int , int , int , int , int , int , int ); ( bytes_text text y x gc fontset d dpy -- r )
extern: int XwcDrawString( int , int , int , int , int , int , int , int ); ( num_wchars text y x gc fontset d dpy -- r )
extern: int XmbDrawImageString( int , int , int , int , int , int , int , int ); ( bytes_text text y x gc fontset d dpy -- r )
extern: int XwcDrawImageString( int , int , int , int , int , int , int , int ); ( num_wchars text y x gc fontset d dpy -- r )
AliasedExtern: XGetICValues_1 int XGetICValues( int , int , int , int ); ( ... ic -- string )
AliasedExtern: XGetICValues_2 int XGetICValues( int , int , int , int , int , int ); ( ... ic -- string )
AliasedExtern: XGetICValues_3 int XGetICValues( int , int , int , int , int , int , int , int ); ( ... ic -- string )
extern: int XmbLookupString( int , int , int , int , int , int ); ( status_r keysym_r bytes_buffer buffer_r event ic -- n )
extern: int XwcLookupString( int , int , int , int , int , int ); ( status_r keysym_r wchars_buffer buffer_r event ic -- n )
extern: int XRegisterIMInstantiateCallback( int , int , int , int , int , int ); ( client_data callback res_class res_name rdb dpy -- flag )
extern: int XUnregisterIMInstantiateCallbac( int , int , int , int , int , int ); ( client_data callback res_class res_name rdb dpy -- flag )
extern: int XInternalConnectionNumbers( int , int , int ); ( count_r fd_r dpy -- status )
extern: int XProcessInternalConnection( int , int ); ( fd dpy -- r )
extern: int XAddConnectionWatch( int , int , int ); ( client_data callback dpy -- status )
extern: int XRemoveConnectionWatch( int , int , int ); ( client_data callback dpy -- status )

\ Xutil.h
\ The following functions are not performed by the XServer, but in Xlib.

extern: int XClipBox( int , int ); ( rect reg -- r )
extern: int XDeleteContext( int , int , int ); ( context rid dpy -- n )
extern: int XEqualRegion( int , int ); ( r1 r2 -- r )
extern: int XFindContext( int , int , int , int ); ( data_r context rid dpy -- n )
extern: int XGetClassHint( int , int , int ); ( class_hints_r w dpy -- status )
extern: int XGetIconSizes( int , int , int , int ); ( count_r size_list_r w dpy -- status )
extern: int XGetNormalHints( int , int , int ); ( hints_r w dpy -- status )
extern: int XGetRGBColormaps( int , int , int , int , int ); ( prop count_r stdcmap_r w dpy -- status )
extern: int XGetSizeHints( int , int , int , int ); ( prop hints_r w dpy -- status )
extern: int XGetStandardColormap( int , int , int , int ); ( prop colormap_r w dpy -- status )
extern: int XGetTextProperty( int , int , int , int ); ( prop text_prop_r w dpy -- status )
extern: int XGetWMClientMachine( int , int , int ); ( text_prop_r w dpy -- status )
extern: int XGetWMHints( int , int ); ( w dpy -- WMHints* )
extern: int XGetWMIconName( int , int , int ); ( text_prop_r w dpy -- status )
extern: int XGetWMName( int , int , int ); ( text_prop_r w dpy -- status )
extern: int XGetWMNormalHints( int , int , int , int ); ( supplied_r hints_r w dpy -- status )
extern: int XGetWMSizeHints( int , int , int , int , int ); ( prop supplied_r hints_r w dpy -- status )
extern: int XGetZoomHints( int , int , int ); ( zhints_r w dpy -- status )
extern: int XConvertCase( int , int , int ); ( upper* lower* sym -- r )
extern: int XMatchVisualInfo( int , int , int , int , int ); ( vinfo_r class depth screen dpy -- status )
extern: int XOffsetRegion( int , int , int ); ( dy dx reg -- r )
extern: int XPointInRegion( int , int , int ); ( y x reg -- flag )
extern: int XPolygonRegion( int , int , int ); ( fill_rile n points -- reg )
extern: int XRectInRegion( int , int , int , int , int ); ( h w y x reg -- n )
extern: int XSaveContext( int , int , int , int ); ( data context rid dpy -- n )
extern: int XSetIconSizes( int , int , int , int ); ( count size_list w dpy -- r )
extern: int XSetNormalHints( int , int , int ); ( hints w dpy -- r )
extern: int XSetRGBColormaps( int , int , int , int , int ); ( prop count stdcmaps w dpy -- r )
extern: int XSetSizeHints( int , int , int , int ); ( prop hints w dpy -- r )
extern: int XSetStandardProperties( int , int , int , int , int , int , int , int ); ( sizehints argc argv icon_pixmap icon_name window_name w dpy -- r )
extern: int XSetWMClientMachine( int , int , int ); ( text_prop w dpy -- r )
extern: int XSetWMIconName( int , int , int ); ( text_prop w dpy -- r )
extern: int XSetWMName( int , int , int ); ( text_prop w dpy -- r )
extern: int XSetWMProperties( int , int , int , int , int , int , int , int , int ); ( class_hints wm_hints normal_hints argc argv icon_name window_name w dpy -- r )
extern: int XmbSetWMProperties( int , int , int , int , int , int , int , int , int ); ( class_hints wm_hints normal_hints argc argv icon_name window_name w dpy -- r )
extern: int XSetWMSizeHints( int , int , int , int ); ( prop hints w dpy -- r )
extern: int XSetStandardColormap( int , int , int , int ); ( prop colormap w dpy -- r )
extern: int XSetZoomHints( int , int , int ); ( zhints w dpy -- r )
extern: int XShrinkRegion( int , int , int ); ( dy dx reg -- r )
extern: int XStringListToTextProperty( int , int , int ); ( text_prop_r count list -- status )
extern: int XSubtractRegion( int , int , int ); ( dr_r srb sra -- r )
extern: int XmbTextListToTextProperty( int , int , int , int , int ); ( text_prop_r style count list dpy -- n )
extern: int XwcTextListToTextProperty( int , int , int , int , int ); ( text_prop_r style count list dpy -- n )
extern: int XTextPropertyToStringList( int , int , int ); ( count_r list_r text_prop -- status )
extern: int XmbTextPropertyToTextList( int , int , int , int ); ( count_r list_r text_prop dpy -- n )
extern: int XwcTextPropertyToTextList( int , int , int , int ); ( count_r list_r text_prop dpy -- n )
extern: int XUnionRegion( int , int , int ); ( dr_r srb sra -- r )
extern: int XWMGeometry( int , int , int , int , int , int , int , int , int , int ); ( gravity_r h_r w_r y_r x_r hints border_w default_geometry user_geometry screen_nr dpy -- n )
extern: int XXorRegion( int , int , int ); ( dr_r srb sra -- r )

\ Memory Management
extern: int XrmStringToQuarkList( int , int ); ( quarks string -- r )
extern: int XrmStringToBindingQuarkList( int , int , int ); ( quarks bindings string -- r )

struct{
    cell size
    cell addr
} XrmValue

extern: int XrmQPutResource( int , int , int , int , int ); ( value type quarks bindings dbase -- r )
extern: int XrmPutResource( int , int , int , int ); ( value type spec dbase -- r )
extern: int XrmQPutStringResource( int , int , int , int ); ( value quarks bindings dbase -- r )
extern: int XrmPutStringResource( int , int , int ); ( value spec dbase -- r )
extern: int XrmPutLineResource( int , int ); ( line dbase -- r )
extern: int XrmQGetResource( int , int , int , int , int ); ( value_r quark_t_r quark_c quark_n dbase -- r )
extern: int XrmGetResource( int , int , int , int , int ); ( value_r str_t_r str_c str_n dbase -- flag )
extern: int XrmQGetSearchList( int , int , int , int , int ); ( list_len list_r classes names dbase -- flag )
extern: int XrmQGetSearchResource( int , int , int , int , int ); ( value_r type_r class name list -- flag )
extern: int XrmSetDatabase( int , int ); ( dbase dpy -- r )
extern: int XrmCombineFileDatabase( int , int , int ); ( flag dbase* filename -- status )
extern: int XrmPutFileDatabase( int , int ); ( string dbase -- r )
extern: int XrmMergeDatabases( int , int ); ( dbase* dbase -- r )
extern: int XrmCombineDatabase( int , int , int ); ( flag dbase* dbase )
extern: int XrmEnumerateDatabase( int , int , int , int , int , int ); ( closure callback mode class_prefix name_prefix db -- flag )
extern: int XrmParseCommand( int , int , int , int , int , int ); ( argv_io argc_io name table-count table dbase -- r )

\ X extensions

extern: int XShmPutImage( int , int , int , int , int , int , int , int , int , int , int ); ( send_event h w dy dx sy sx im gc win dpy -- status )

previous

base !

include Xstring.fs

previous definitions

.( End loading X11 stuff) cr