\ X11 interface

Vocabulary X11

also X11 definitions

library: libX11.so.6
library: libXext.so.6 \ depends libX11

base @ hex

synonym has-utf8 noop
synonym has-png noop
synonym has-xft noop

LocalExtern: XGetModifierMapping int XGetModifierMapping( int ); ( dpy -- modmap )
LocalExtern: XNewModifiermap int XNewModifiermap( int ); ( maxkeys -- modmap )
LocalExtern: XInitImage int XInitImage( int ); ( image -- status )
LocalExtern: XOpenDisplay int XOpenDisplay( int ); ( name -- dpy )
LocalExtern: XDisplayName int XDisplayName( int ); ( string -- string )
LocalExtern: XKeysymToString int XKeysymToString( int ); ( keysym -- string )
LocalExtern: XGContextFromGC int XGContextFromGC( int ); ( gc -- gcontext )
LocalExtern: XStringToKeysym int XStringToKeysym( int ); ( string -- keysym )
LocalExtern: XMaxRequestSize int XMaxRequestSize( int ); ( dpy -- n )
LocalExtern: XExtendedMaxRequestSize int XExtendedMaxRequestSize( int ); ( dpy -- n )
LocalExtern: XResourceManagerString int XResourceManagerString( int ); ( dpy -- string )
LocalExtern: XScreenResourceString int XScreenResourceString( int ); ( screen -- string )
LocalExtern: XDisplayMotionBufferSize int XDisplayMotionBufferSize( int ); ( dpy -- u )
LocalExtern: XVisualIDFromVisual int XVisualIDFromVisual( int ); ( visual -- visualID )
LocalExtern: XLockDisplay int XLockDisplay( int ); ( dpy -- r )
LocalExtern: XUnlockDisplay int XUnlockDisplay( int ); ( dpy -- r )
LocalExtern: XAddExtension int XAddExtension( int ); ( dpy -- extcodes )
LocalExtern: XEHeadOfExtensionList int XEHeadOfExtensionList( int ); ( object -- extdata** )
LocalExtern: XDefaultRootWindow int XDefaultRootWindow( int ); ( dpy -- window )
LocalExtern: XRootWindowOfScreen int XRootWindowOfScreen( int ); ( screen -- window )
LocalExtern: XDefaultVisualOfScreen int XDefaultVisualOfScreen( int ); ( screen -- visual )
LocalExtern: XDefaultGCOfScreen int XDefaultGCOfScreen( int ); ( screen -- gc )
LocalExtern: XBlackPixelOfScreen int XBlackPixelOfScreen( int ); ( screen -- u )
LocalExtern: XWhitePixelOfScreen int XWhitePixelOfScreen( int ); ( screen -- u )
LocalExtern: XNextRequest int XNextRequest( int ); ( dpy -- u )
LocalExtern: XLastKnownRequestProcessed int XLastKnownRequestProcessed( int ); ( dpy -- u )
LocalExtern: XServerVendor int XServerVendor( int ); ( dpy -- string )
LocalExtern: XDisplayString int XDisplayString( int ); ( dpy -- string )
LocalExtern: XDefaultColormapOfScreen int XDefaultColormapOfScreen( int ); ( screen -- colormap )
LocalExtern: XDisplayOfScreen int XDisplayOfScreen( int ); ( screen -- dpy )
LocalExtern: XDefaultScreenOfDisplay int XDefaultScreenOfDisplay( int ); ( dpy -- screen )
LocalExtern: XEventMaskOfScreen int XEventMaskOfScreen( int ); ( screen -- mask )
LocalExtern: XScreenNumberOfScreen int XScreenNumberOfScreen( int ); ( screen -- n )
LocalExtern: XSetErrorHandler int XSetErrorHandler( int ); ( handler -- errorhandler )
LocalExtern: XSetIOErrorHandler int XSetIOErrorHandler( int ); ( handler -- ioerrorhandler )
LocalExtern: XFreeStringList int XFreeStringList( int ); ( list -- r )
LocalExtern: XActivateScreenSaver int XActivateScreenSaver( int ); ( dpy -- r )
LocalExtern: XAutoRepeatOff int XAutoRepeatOff( int ); ( dpy -- r )
LocalExtern: XAutoRepeatOn int XAutoRepeatOn( int ); ( dpy -- r )
LocalExtern: XBitmapBitOrder int XBitmapBitOrder( int ); ( dpy -- n )
LocalExtern: XBitmapPad int XBitmapPad( int ); ( dpy -- n )
LocalExtern: XBitmapUnit int XBitmapUnit( int ); ( dpy -- n )
LocalExtern: XCellsOfScreen int XCellsOfScreen( int ); ( screen -- n )
LocalExtern: XCloseDisplay int XCloseDisplay( int ); ( dpy -- r )
LocalExtern: XConnectionNumber int XConnectionNumber( int ); ( dpy -- r )
LocalExtern: XDefaultDepthOfScreen int XDefaultDepthOfScreen( int ); ( screen -- i )
LocalExtern: XDefaultScreen int XDefaultScreen( int ); ( dpy -- i )
LocalExtern: XDoesBackingStore int XDoesBackingStore( int ); ( screen -- i )
LocalExtern: XDoesSaveUnders int XDoesSaveUnders( int ); ( screen -- flag )
LocalExtern: XDisableAccessControl int XDisableAccessControl( int ); ( dpy -- r )
LocalExtern: XEnableAccessControl int XEnableAccessControl( int ); ( dpy -- r )
LocalExtern: XFlush void XFlush( int ); ( dpy -- r )
LocalExtern: XFree int XFree( int ); ( data -- r )
LocalExtern: XFreeExtensionList int XFreeExtensionList( int ); ( list -- r )
LocalExtern: XFreeFontNames int XFreeFontNames( int ); ( list -- r )
LocalExtern: XFreeFontPath int XFreeFontPath( int ); ( list -- r )
LocalExtern: XFreeModifiermap int XFreeModifiermap( int ); ( modmap -- r )
LocalExtern: XGrabServer int XGrabServer( int ); ( dpy -- r )
LocalExtern: XHeightMMOfScreen int XHeightMMOfScreen( int ); ( screen -- n )
LocalExtern: XHeightOfScreen int XHeightOfScreen( int ); ( screen -- n )
LocalExtern: XImageByteOrder int XImageByteOrder( int ); ( dpy -- n )
LocalExtern: XMaxCmapsOfScreen int XMaxCmapsOfScreen( int ); ( screen -- n )
LocalExtern: XMinCmapsOfScreen int XMinCmapsOfScreen( int ); ( screen -- n )
LocalExtern: XNoOp int XNoOp( int ); ( dpy -- r )
LocalExtern: XPending int XPending( int ); ( dpy -- n )
LocalExtern: XPlanesOfScreen int XPlanesOfScreen( int ); ( screen -- n )
LocalExtern: XProtocolRevision int XProtocolRevision( int ); ( dpy -- n )
LocalExtern: XProtocolVersion int XProtocolVersion( int ); ( dpy -- n )
LocalExtern: XQLength int XQLength( int ); ( dpy -- n )
LocalExtern: XRefreshKeyboardMapping int XRefreshKeyboardMapping( int ); ( event_map -- r )
LocalExtern: XResetScreenSaver int XResetScreenSaver( int ); ( dpy -- r )
LocalExtern: XScreenCount int XScreenCount( int ); ( dpy -- n )
LocalExtern: XUngrabServer int XUngrabServer( int ); ( dpy -- r )
LocalExtern: XVendorRelease int XVendorRelease( int ); ( dpy -- n )
LocalExtern: XWidthMMOfScreen int XWidthMMOfScreen( int ); ( screen -- n )
LocalExtern: XWidthOfScreen int XWidthOfScreen( int ); ( screen -- n )
LocalExtern: XSetLocaleModifiers int XSetLocaleModifiers( int ); ( modifier_list -- string )
LocalExtern: XCloseOM int XCloseOM( int ); ( om -- status )
LocalExtern: XSetOMValues int XSetOMValues( int ); ( ...om -- string )
LocalExtern: XGetOMValues int XGetOMValues( int ); ( ...om -- string )
LocalExtern: XDisplayOfOM int XDisplayOfOM( int ); ( om -- dpy )
LocalExtern: XLocaleOfOM int XLocaleOfOM( int ); ( om -- string )
LocalExtern: XCreateOC int XCreateOC( int ); ( ...om -- XOC )
LocalExtern: XDestroyOC int XDestroyOC( int ); ( oc -- r )
LocalExtern: XOMOfOC int XOMOfOC( int ); ( oc -- XOM )
LocalExtern: XSetOCValues int XSetOCValues( int ); ( ...oc -- string )
LocalExtern: XGetOCValues int XGetOCValues( int ); ( ...oc -- string )
LocalExtern: XBaseFontNameListOfFontSet int XBaseFontNameListOfFontSet( int ); ( fontset -- string )
LocalExtern: XLocaleOfFontSet int XLocaleOfFontSet( int ); ( fontset -- string )
LocalExtern: XContextDependentDrawing int XContextDependentDrawing( int ); ( fontset -- flag )
LocalExtern: XDirectionalDependentDrawing int XDirectionalDependentDrawing( int ); ( fontset -- flag )
LocalExtern: XContextualDrawing int XContextualDrawing( int ); ( fontset -- flag )
LocalExtern: XExtentsOfFontSet int XExtentsOfFontSet( int ); ( fontset -- fontsetextents )
LocalExtern: XCloseIM int XCloseIM( int ); ( im -- status )
LocalExtern: XDisplayOfIM int XDisplayOfIM( int ); ( im -- dpy )
LocalExtern: XLocaleOfIM int XLocaleOfIM( int ); ( im -- string )
LocalExtern: XCreateIC int XCreateIC( int ); ( im -- XIC )
LocalExtern: XDestroyIC int XDestroyIC( int ); ( ic -- r )
LocalExtern: XSetICFocus int XSetICFocus( int ); ( ic -- r )
LocalExtern: XUnsetICFocus int XUnsetICFocus( int ); ( ic -- r )
LocalExtern: XwcResetIC int XwcResetIC( int ); ( ic -- wstring )
LocalExtern: XmbResetIC int XmbResetIC( int ); ( ic -- string )
LocalExtern: XIMOfIC int XIMOfIC( int ); ( ic -- XIM )
LocalExtern: XDestroyRegion int XDestroyRegion( int ); ( reg -- r )
LocalExtern: XEmptyRegion int XEmptyRegion( int ); ( reg -- r )
LocalExtern: XwcFreeStringList int XwcFreeStringList( int ); ( list -- r )
LocalExtern: Xpermalloc int Xpermalloc( int ); ( size -- addr )
LocalExtern: XrmStringToQuark int XrmStringToQuark( int ); ( string -- quark )
LocalExtern: XrmPermStringToQuark int XrmPermStringToQuark( int ); ( string -- quark )
LocalExtern: XrmQuarkToString int XrmQuarkToString( int ); ( quark -- string )
LocalExtern: XrmDestroyDatabase int XrmDestroyDatabase( int ); ( dbase -- r )
LocalExtern: XrmGetDatabase int XrmGetDatabase( int ); ( dpy -- dbase )
LocalExtern: XrmGetFileDatabase int XrmGetFileDatabase( int ); ( filename -- dbase )
LocalExtern: XrmGetStringDatabase int XrmGetStringDatabase( int ); ( string -- dbase )
LocalExtern: XrmLocaleOfDatabase int XrmLocaleOfDatabase( int ); ( dbase -- string )

LocalExtern: XrmInitialize int XrmInitialize( );   ( -- r )
LocalExtern: XInitThreads int XInitThreads( );    ( -- status )
LocalExtern: XAllPlanes int XAllPlanes( );      ( -- u )
LocalExtern: XAllocClassHint int XAllocClassHint( ); ( -- classhint* )
LocalExtern: XAllocIconSize int XAllocIconSize( );  ( -- iconsize* )
LocalExtern: XAllocSizeHints int XAllocSizeHints( ); ( -- sizehints* )
LocalExtern: XAllocStandardColormap int XAllocStandardColormap( );  ( -- stdcmap* )
LocalExtern: XAllocWMHints int XAllocWMHints( );   ( -- wmhints* )
LocalExtern: XCreateRegion int XCreateRegion( );   ( -- reg )
LocalExtern: XDefaultString int XDefaultString( );  ( -- char* )
LocalExtern: XrmUniqueQuark int XrmUniqueQuark( );  ( -- quark )

LocalExtern: XLoadQueryFont int XLoadQueryFont( int , int ); ( dpy name -- fontstruct )
LocalExtern: XAllocColor int XAllocColor( int , int , int ); ( color colormap dpy -- status )
LocalExtern: XGetWindowAttributes int XGetWindowAttributes( int , int , int ); ( dpy win windows_attributes_r -- status )
LocalExtern: XChangeWindowAttributes int XChangeWindowAttributes( int , int , int , int ); ( dpy win valuemask attributes -- r )
LocalExtern: XGetErrorText int XGetErrorText( int , int , int , int ); ( dpy code buffer_r length -- r )
LocalExtern: XSupportsLocale int XSupportsLocale( ); ( -- flag )
LocalExtern: XGetVisualInfo int XGetVisualInfo( int , int , int , int ); ( dpy vinfo_mask vinfo_templ nitems_r -- vinfo* )
LocalExtern: XCreateColormap int XCreateColormap( int , int , int , int ); ( dpy w visual alloc -- colormap )
LocalExtern: XOpenIM int XOpenIM( int , int , int , int ); ( dpy rdb res_name res_class -- XIM )
LocalExtern: XGetIMValues_1 void * XGetIMValues( int , int , int , int ); ( im ... -- string )
LocalExtern: XGetIMValues_2 void * XGetIMValues( int , int , int , int , int , int ); ( im ... -- string )
LocalExtern: XGetIMValues_3 void * XGetIMValues( int , int , int , int , int , int , int , int ); ( im ... -- string )
LocalExtern: XSetIMValues_1 void * XSetIMValues( int , int , int , int ); ( im ... -- string )
LocalExtern: XSetIMValues_2 void * XSetIMValues( int , int , int , int , int , int ); ( im ... -- string )
LocalExtern: XSetIMValues_3 void * XSetIMValues( int , int , int , int , int , int , int , int ); ( im ... -- string )
LocalExtern: XVaCreateNestedList_1 void * XVaCreateNestedList( int , int , int , int ); ( ...unused -- vanestedlist )
LocalExtern: XVaCreateNestedList_2 void * XVaCreateNestedList( int , int , int , int , int , int ); ( ...unused -- vanestedlist )
LocalExtern: XVaCreateNestedList_3 void * XVaCreateNestedList( int , int , int , int , int , int , int , int ); ( ...unused -- vanestedlist )
LocalExtern: XVaCreateNestedList_4 void * XVaCreateNestedList( int , int , int , int , int , int , int , int , int , int ); ( ...unused -- vanestedlist )
LocalExtern: XCreateIC_1 void * XCreateIC( int , int , int , int ); ( im -- XIC )
LocalExtern: XCreateIC_2 void * XCreateIC( int , int , int , int , int , int ); ( im -- XIC )
LocalExtern: XCreateIC_3 void * XCreateIC( int , int , int , int , int , int , int , int ); ( im -- XIC )
LocalExtern: XCreateIC_4 void * XCreateIC( int , int , int , int , int , int , int , int , int , int ); ( im -- XIC )
LocalExtern: XCreateIC_5 void * XCreateIC( int , int , int , int , int , int , int , int , int , int , int , int ); ( im -- XIC )
LocalExtern: XCreateGC void * XCreateGC( int , int , int , int ); ( dpy d valuemask values -- gc )
LocalExtern: XDestroyWindow int XDestroyWindow( int , int ); ( dpy win -- r )
LocalExtern: XKeycodeToKeysym int XKeycodeToKeysym( int , int , int ); ( dpy keycode index -- keysym )
LocalExtern: XCreateFontSet int XCreateFontSet( int , int , int , int , int ); ( dpy base_font_name_list missing_charset_list missing-charset_count def_string -- fontset )
LocalExtern: XFreeColors int XFreeColors( int , int , int , int , int ); ( dpy colormap pixels npixels planes -- r )
LocalExtern: XCreateFontCursor int XCreateFontCursor( int , int ); ( dpy shape -- cursor )
LocalExtern: XChangeGC int XChangeGC( int , int , int , int ); ( dpy gc valuemask values -- r )
LocalExtern: XSetFunction int XSetFunction( int , int , int ); ( dpy gc function -- r )
LocalExtern: XStoreBytes int XStoreBytes( int , int , int ); ( dpy bytes nbytes -- r )
LocalExtern: XSetSelectionOwner int XSetSelectionOwner( int , int , int , int ); ( dpy selection owner time -- r )
LocalExtern: XChangeProperty int XChangeProperty( int , int , int , int , int , int , int , int ); ( dpy w property type format mode data elements -- r )
LocalExtern: XConvertSelection int XConvertSelection( int , int , int , int , int , int ); ( dpy selection target property requestor time -- r )
LocalExtern: XGetSelectionOwner int XGetSelectionOwner( int , int ); ( dpy atom -- window )
LocalExtern: XFetchBytes int XFetchBytes( int , int ); ( dpy nbytesr -- buffer )
LocalExtern: XCreateWindow int XCreateWindow( int , int , int , int , int , int , int , int , int , int , int , int ); ( dpy parent x y w h borderwidth depth class visual valuemask attribs -- window )
LocalExtern: XGetWindowProperty int XGetWindowProperty( int , int , int , int , int , int , int , int , int , int , int , int ); ( dpy w property offset length delete req_type actual_typer actual_format_r nitems_r bytes_after_r prop_r -- n )
LocalExtern: XDefineCursor int XDefineCursor( int , int , int ); ( dpy win cursor -- r )
LocalExtern: XSetLineAttributes int XSetLineAttributes( int , int , int , int , int , int ); ( dpy gc line_width line_style cap_style join_style -- r )
LocalExtern: XDrawLine void XDrawLine( int , int , int , int , int , int , int ); ( dpy d gc x1 x2 y1 y2 -- )
LocalExtern: XFillRectangle void XFillRectangle( int , int , int , int , int , int , int ); ( dpy d gc x y w h -- )
LocalExtern: XFillPolygon void XFillPolygon( int , int , int , int , int , int , int ); ( dpy d gc points npoints shape mode -- )
LocalExtern: XDrawLines void XDrawLines( int , int , int , int , int , int ); ( dpy d gc points npoints mode -- )
LocalExtern: XSetClipMask void XSetClipMask( int , int , int ); ( dpy gc pixmap -- )
LocalExtern: XSetClipOrigin void XSetClipOrigin( int , int , int , int ); ( dpy gc clip_x_orig clip_y_orig -- )
LocalExtern: XCopyArea void XCopyArea( int , int , int , int , int , int , int , int , int , int ); ( dpy src dest gc x y w h dx dy -- )
LocalExtern: XUnionRectWithRegion void XUnionRectWithRegion( int , int , int ); ( rect src_reg dest_reg_r -- )
LocalExtern: XSetRegion void XSetRegion( int , int , int ); ( dpy gc reg -- )
LocalExtern: XCheckMaskEvent int XCheckMaskEvent( int , int , int ); ( dpy event_mask event_r -- flag )
LocalExtern: XNextEvent void XNextEvent( int , int ); ( dpy event_r -- )
LocalExtern: XSync void XSync( int , int ); ( dpy discard -- )
LocalExtern: XQueryPointer int XQueryPointer( int , int , int , int , int , int , int , int , int ); ( dpy w root_r child_r root_x_r root_y_r win_x_r win_y_r mask_r -- flag )
[defined] has-utf8 [IF]
LocalExtern: Xutf8LookupString int Xutf8LookupString( int , int , int , int , int , int ); ( ic event buffer_r wchars_buffer keysym_r status_r -- n )
[THEN]
LocalExtern: XLookupString int XLookupString( int , int , int , int , int ); ( event buffer bufsize keysym_r composestatus* -- n )
LocalExtern: XGetAtomName int XGetAtomName( int , int ); ( dpy atom -- name )
LocalExtern: XSendEvent int XSendEvent( int , int , int , int , int ); ( dpy w propagate event_mask event_send -- status )
LocalExtern: XTextExtents void XTextExtents( int , int , int , int , int , int , int ); ( font_struct string nchars direction_r font_ascent_r font_descent_r overall_r -- )
LocalExtern: XTextExtents16 void XTextExtents16( int , int , int , int , int , int , int ); ( font_struct string nchars direction_r font_ascent_r font_descent_r overall_r -- )
LocalExtern: XDrawText void XDrawText( int , int , int , int , int , int , int ); ( dpy d gc x y items nitems -- r )
LocalExtern: XDrawText16 void XDrawText16( int , int , int , int , int , int , int ); ( dpy d gc x y items nitems -- r )
LocalExtern: XFreePixmap void XFreePixmap( int , int ); ( dpy pixmap -- )
LocalExtern: XCreatePixmap int XCreatePixmap( int , int , int , int , int ); ( dpy d w h depth -- pixmap )
LocalExtern: XCreateImage void * XCreateImage( int , int , int , int , int , int , int , int , int , int ); ( dpy visual depth format offset data w h bmpad b/line -- image )
LocalExtern: XGetImage void * XGetImage( int , int , int , int , int , int , int , int ); ( dpy d x y w h planemask format -- image )
LocalExtern: XInternAtom int XInternAtom( int , int , int ); ( dpy atomname flag -- atom )
LocalExtern: XListPixmapFormats int XListPixmapFormats( int , int ); ( dpy count_r -- pixmapformatvalues )
LocalExtern: XSetTransientForHint void XSetTransientForHint( int , int , int ); ( dpy w propw -- )
LocalExtern: XCopyPlane void XCopyPlane( int , int , int , int , int , int , int , int , int , int , int ); ( dpy src dest gc x y w h dx dy plane -- )
LocalExtern: XFreeColormap void XFreeColormap( int , int ); ( dpy colormap -- )
LocalExtern: XFreeGC void XFreeGC( int , int ); ( dpy gc -- )
LocalExtern: XGetGeometry int XGetGeometry( int , int , int , int , int , int , int , int , int ); ( dpy d root_r x_r y_r w_r h_r borderw_r depth_r -- status )
LocalExtern: XGrabPointer int XGrabPointer( int , int , int , int , int , int , int , int , int ); ( time cursor confine_to keyboard_mode pointer_mode owner_events grab_window dpy -- n )
LocalExtern: XMapRaised void XMapRaised( int , int ); ( dpy w -- )
LocalExtern: XMapWindow void XMapWindow( int , int ); ( dpy w -- o)
LocalExtern: XMoveResizeWindow void XMoveResizeWindow( int , int , int , int , int , int ); ( dpy win x y w h -- r )
LocalExtern: XMoveWindow void XMoveWindow( int , int , int , int ); ( dpy win x y -- )
LocalExtern: XParseGeometry int XParseGeometry( int , int , int , int , int ); ( parsestring x_r y_r w_r h_r -- n )
LocalExtern: XPutImage void XPutImage( int , int , int , int , int , int , int , int , int , int ); ( dpy d gc image s_x s_y d_x d_y w h -- )
LocalExtern: XResizeWindow void XResizeWindow( int , int , int , int ); ( dpy win w h -- )
LocalExtern: XSetBackground void XSetBackground( int , int , int ); ( dpy gc background -- )
LocalExtern: XSetForeground void XSetForeground( int , int , int ); ( dpy gc fg -- )
LocalExtern: XSetIconName void XSetIconName( int , int , int ); ( dpy win icon_name -- )
LocalExtern: XSetInputFocus void XSetInputFocus( int , int , int , int ); ( dpy focus revert_to time -- )
LocalExtern: XStoreName void XStoreName( int , int , int ); ( dpy win window_name -- )
LocalExtern: XUngrabPointer void XUngrabPointer( int , int ); ( dpy time -- )
LocalExtern: XUnmapWindow void XUnmapWindow( int , int ); ( dpy w -- )
LocalExtern: XWarpPointer void XWarpPointer( int , int , int , int , int , int , int , int , int ); ( dpy src_w dest_w src_x src_y src_w src_h dest_x dest_y -- )
LocalExtern: XSelectInput void XSelectInput( int , int , int ); ( dpy w event_mask -- )
LocalExtern: XWindowEvent void XWindowEvent( int , int , int , int ); ( dpy w event_mask event_r -- )
LocalExtern: XSetICValues_1 int XSetICValues( int , int , int , int ); ( ic ... -- string )
LocalExtern: XSetICValues_2 int XSetICValues( int , int , int , int , int , int ); ( ic ... -- string )
LocalExtern: XSetICValues_3 int XSetICValues( int , int , int , int , int , int , int , int ); ( ic ... -- string )
LocalExtern: XFilterEvent int XFilterEvent( int , int ); ( event w -- flag )
LocalExtern: XIntersectRegion void XIntersectRegion( int , int , int ); ( sra srb dr_r -- )
LocalExtern: XSetClassHint void XSetClassHint( int , int , int ); ( dpy w class_hints -- )
LocalExtern: XSetTextProperty void XSetTextProperty( int , int , int , int ); ( dpy w text_prop prop -- )
LocalExtern: XSetWMHints void XSetWMHints( int , int , int ); ( dpy w wm_hints -- )
LocalExtern: XSetWMNormalHints void XSetWMNormalHints( int , int , int ); ( dpy w hints -- )
LocalExtern: XCreateSimpleWindow int XCreateSimpleWindow( int , int , int , int , int , int , int , int , int ); ( dpy parent x y w h bwidth border bg -- window )

\ Unused stuff, machine converted

\ -1 Extern: _XPrivDisplay               _XPrivDisplay   ( -- addr )
\ -1 Extern: _Xdebug                       _Xdebug         ( -- addr )
LocalExtern: XQueryFont int XQueryFont( int , int ); ( XID dpy -- fontstruct )
LocalExtern: XGetMotionEvents int XGetMotionEvents( int , int , int , int , int ); ( neventsr stop start w dpy -- timecoord )
LocalExtern: XDeleteModifiermapEntry int XDeleteModifiermapEntry( int , int , int ); ( mod keycode modmap -- modmap )
LocalExtern: XInsertModifiermapEntry int XInsertModifiermapEntry( int , int , int ); ( mod keycode modmap -- modmap )
LocalExtern: XGetSubImage int XGetSubImage( int , int , int , int , int , int , int , int , int , int , int ); ( dy dx dimage format planemask h w y x d dpy -- image )
LocalExtern: XFetchBuffer int XFetchBuffer( int , int , int ); ( buffer nbytesr dpy -- buffer )
LocalExtern: XGetAtomNames int XGetAtomNames( int , int , int , int ); ( namesr count atoms dpy -- status )
LocalExtern: XGetDefault int XGetDefault( int , int , int ); ( option program dpy --  string )
LocalExtern: XInternAtoms int XInternAtoms( int , int , int , int , int ); ( atoms flag count names dpy -- status )
LocalExtern: XCopyColormapAndFree int XCopyColormapAndFree( int , int ); ( colormap dpy -- colormap )
LocalExtern: XCreatePixmapCursor int XCreatePixmapCursor( int , int , int , int , int , int , int ); ( y x bgcol fgcol mask source dpy -- cursor )
LocalExtern: XCreateGlyphCursor int XCreateGlyphCursor( int , int , int , int , int , int , int ); ( bgcol fgcol maskc sourcec maskfont sourcefont dpy -- cursor )
LocalExtern: XLoadFont int XLoadFont( int , int ); ( name dpy -- font )
LocalExtern: XFlushGC int XFlushGC( int , int ); ( gc dpy -- r )
LocalExtern: XCreateBitmapFromData int XCreateBitmapFromData( int , int , int , int , int ); ( h w data d dpy -- pixmap )
LocalExtern: XCreatePixmapFromBitmapData int XCreatePixmapFromBitmapData( int , int , int , int , int , int , int , int ); ( depth bg fg h w data d dpy -- pixmap )
LocalExtern: XListInstalledColormaps int XListInstalledColormaps( int , int , int ); ( num_r w dpy -- colormap* )
LocalExtern: XListFonts int XListFonts( int , int , int , int ); ( actual_count_r maxnames pattern dpy -- char** )
LocalExtern: XListFontsWithInfo int XListFontsWithInfo( int , int , int , int , int ); ( info_r count_r maxnames pattern dpy -- char** )
LocalExtern: XGetFontPath int XGetFontPath( int , int ); ( npaths_r dpy -- char** )
LocalExtern: XListExtensions int XListExtensions( int , int ); ( nextensions_r dpy -- char** )
LocalExtern: XListProperties int XListProperties( int , int , int ); ( num_prop_r w dpy -- atom* )
LocalExtern: XListHosts int XListHosts( int , int , int ); ( status_r nhosts_r dpy -- hostaddr* )
LocalExtern: XLookupKeysym int XLookupKeysym( int , int ); ( index key_event -- keysym )
LocalExtern: XGetKeyboardMapping int XGetKeyboardMapping( int , int , int , int ); ( keysym/keycode_r keycode_c first_kc dpy -- keysym* )
LocalExtern: XInitExtension int XInitExtension( int , int ); ( name dpy -- extcodes )
LocalExtern: XFindOnExtensionList int XFindOnExtensionList( int , int ); ( number structure -- extdata )
LocalExtern: XRootWindow int XRootWindow( int , int ); ( screen_nr dpy -- window )
LocalExtern: XDefaultVisual int XDefaultVisual( int , int ); ( screen_nr dpy -- visual )
LocalExtern: XDefaultGC int XDefaultGC( int , int ); ( screen_nr dpy -- gc )
LocalExtern: XBlackPixel int XBlackPixel( int , int ); ( screen_nr dpy -- u )
LocalExtern: XWhitePixel int XWhitePixel( int , int ); ( screen_nr dpy -- u )
LocalExtern: XDefaultColormap int XDefaultColormap( int , int ); ( screen_nr dpy -- colormap )
LocalExtern: XScreenOfDisplay int XScreenOfDisplay( int , int ); ( screen_nr dpy -- screen )
LocalExtern: XListDepths int XListDepths( int , int , int ); ( count_r screen_nr dpy -- int* )
LocalExtern: XReconfigureWMWindow int XReconfigureWMWindow( int , int , int , int , int ); ( changes mask screen_nr w dpy -- status )
LocalExtern: XGetWMProtocols int XGetWMProtocols( int , int , int , int ); ( count_r protocols_r w dpy -- status )
LocalExtern: XSetWMProtocols int XSetWMProtocols( int , int , int , int ); ( count protocols w dpy -- status )
LocalExtern: XIconifyWindow int XIconifyWindow( int , int , int ); ( screen_nr w dpy -- status )
LocalExtern: XWithdrawWindow int XWithdrawWindow( int , int , int ); ( screen_nr w dpy -- status )
LocalExtern: XGetCommand int XGetCommand( int , int , int , int ); ( argc_r argv_r w dpy -- status )
LocalExtern: XGetWMColormapWindows int XGetWMColormapWindows( int , int , int , int ); ( count_r windows_r w dpy -- status )
LocalExtern: XSetWMColormapWindows int XSetWMColormapWindows( int , int , int , int ); ( count colormap_windows w dpy -- status )
LocalExtern: XAddHost int XAddHost( int , int ); ( host dpy -- r )
LocalExtern: XAddHosts int XAddHosts( int , int , int ); ( num hosts dpy -- r )
LocalExtern: XAddToExtensionList int XAddToExtensionList( int , int ); ( extdata structure -- r )
LocalExtern: XAddToSaveSet int XAddToSaveSet( int , int ); ( w dpy -- r )
LocalExtern: XAllocColorCells int XAllocColorCells( int , int , int , int , int , int , int ); ( pixels pixels_r planes planemask_r contig colormap dpy -- status )
LocalExtern: XAllocColorPlanes int XAllocColorPlanes( int , int , int , int , int , int , int , int , int , int , int ); ( bmask_r gmask_r rmask_r blues greens reds colors pixels_r contig colormap dpy -- status )
LocalExtern: XAllocNamedColor int XAllocNamedColor( int , int , int , int , int ); ( exact_def_r screen_def_r cname colormap dpy -- status )
LocalExtern: XAllowEvents int XAllowEvents( int , int , int ); ( time event_mode dpy -- r )
LocalExtern: XBell int XBell( int , int ); ( percent dpy -- r )
LocalExtern: XChangeActivePointerGrab int XChangeActivePointerGrab( int , int , int , int ); ( time cursor event_mask dpy -- r )
LocalExtern: XChangeKeyboardControl int XChangeKeyboardControl( int , int , int ); ( values valuemask dpy -- r )
LocalExtern: XChangeKeyboardMapping int XChangeKeyboardMapping( int , int , int , int , int ); ( num_codes keysyms keysyms/keycode first_kc dpy -- r )
LocalExtern: XChangePointerControl int XChangePointerControl( int , int , int , int , int , int ); ( threshold accel_denom accel_num do_thres do_accel dpy -- r )
LocalExtern: XChangeSaveSet int XChangeSaveSet( int , int , int ); ( change_mode w dpy -- r )
LocalExtern: XCheckIfEvent int XCheckIfEvent( int , int , int , int ); ( arg predicate event_return dpy -- flag )
LocalExtern: XCheckTypedEvent int XCheckTypedEvent( int , int , int ); ( event_r event_type dpy -- flag )
LocalExtern: XCheckTypedWindowEvent int XCheckTypedWindowEvent( int , int , int , int ); ( event_r event_type w dpy -- flag )
LocalExtern: XCheckWindowEvent int XCheckWindowEvent( int , int , int , int ); ( event_r event_mask w dpy -- flag )
LocalExtern: XCirculateSubwindows int XCirculateSubwindows( int , int , int ); ( direction w dpy -- r )
LocalExtern: XCirculateSubwindowsDown int XCirculateSubwindowsDown( int , int ); ( w dpy -- r )
LocalExtern: XCirculateSubwindowsUp int XCirculateSubwindowsUp( int , int ); ( w dpy -- r )
LocalExtern: XClearArea int XClearArea( int , int , int , int , int , int , int ); ( exposures h w y x w dpy -- r )
LocalExtern: XClearWindow int XClearWindow( int , int ); ( w dpy -- r )
LocalExtern: XConfigureWindow int XConfigureWindow( int , int , int , int ); ( values value_mask w dpy -- r )
LocalExtern: XCopyGC int XCopyGC( int , int , int , int ); ( dest valuemask src dpy -- r )
LocalExtern: XDefaultDepth int XDefaultDepth( int , int ); ( screen_nr dpy -- i )
LocalExtern: XDeleteProperty int XDeleteProperty( int , int , int ); ( atom w dpy -- r )
LocalExtern: XDestroySubwindows int XDestroySubwindows( int , int ); ( w dpy -- r )
LocalExtern: XDisplayCells int XDisplayCells( int , int ); ( screen_nr dpy -- i )
LocalExtern: XDisplayHeight int XDisplayHeight( int , int ); ( screen_nr dpy -- i )
LocalExtern: XDisplayHeightMM int XDisplayHeightMM( int , int ); ( screen_nr dpy -- i )
LocalExtern: XDisplayKeycodes int XDisplayKeycodes( int , int , int ); ( min_keycodes_r max_keycodes_r dpy -- r )
LocalExtern: XDisplayPlanes int XDisplayPlanes( int , int ); ( screen_nr dpy -- i )
LocalExtern: XDisplayWidth int XDisplayWidth( int , int ); ( screen_nr dpy -- i )
LocalExtern: XDisplayWidthMM int XDisplayWidthMM( int , int ); ( screen_nr dpy -- i )
LocalExtern: XDrawArc int XDrawArc( int , int , int , int , int , int , int , int , int ); ( angle2 angle1 h w y x gc d dpy -- r )
LocalExtern: XDrawArcs int XDrawArcs( int , int , int , int , int ); ( narcs arcs gc d dpy -- r )
LocalExtern: XDrawImageString int XDrawImageString( int , int , int , int , int , int , int ); ( length string y x gc d dpy -- r )
LocalExtern: XDrawImageString16 int XDrawImageString16( int , int , int , int , int , int , int ); ( length string y x gc d dpy -- r )
[defined] has-utf8 [IF]
    LocalExtern: Xutf8DrawText void Xutf8DrawText( int , int , int , int , int , int , int ); ( dpy d gc x y items nitems -- )
[THEN]
LocalExtern: XDrawPoint int XDrawPoint( int , int , int , int , int ); ( y x gc d dpy -- r )
LocalExtern: XDrawPoints int XDrawPoints( int , int , int , int , int , int ); ( mode npoints point gc d dpy -- r )
LocalExtern: XDrawRectangle int XDrawRectangle( int , int , int , int , int , int , int ); ( h w y x gc d dpy -- r )
LocalExtern: XDrawRectangles int XDrawRectangles( int , int , int , int , int ); ( nrects rects gc d dpy -- r )
LocalExtern: XDrawSegments int XDrawSegments( int , int , int , int , int ); ( nsegments segments gc d dpy -- r )
LocalExtern: XDrawString int XDrawString( int , int , int , int , int , int , int ); ( length string y x gc d dpy -- r )
LocalExtern: XDrawString16 int XDrawString16( int , int , int , int , int , int , int ); ( length string y x gc d dpy -- r )
LocalExtern: XEventsQueued int XEventsQueued( int , int ); ( mode dpy -- i )
LocalExtern: XFetchName int XFetchName( int , int , int ); ( name_r w dpy -- status )
LocalExtern: XFillArc int XFillArc( int , int , int , int , int , int , int , int , int ); ( angle2 angle1 h w y x gc d dpy -- r )
LocalExtern: XFillArcs int XFillArcs( int , int , int , int , int ); ( narcs arcs gc d dpy -- r )
LocalExtern: XFillRectangles int XFillRectangles( int , int , int , int , int ); ( nrects rects gc d dpy -- r )
LocalExtern: XForceScreenSaver int XForceScreenSaver( int , int ); ( mode dpy -- r )
LocalExtern: XFreeCursor int XFreeCursor( int , int ); ( cursor dpy -- r )
LocalExtern: XFreeFont int XFreeFont( int , int ); ( fontstruct dpy -- r )
LocalExtern: XFreeFontInfo int XFreeFontInfo( int , int , int ); ( actual_count free_info names -- r )
LocalExtern: XGeometry int XGeometry( int , int , int , int , int , int , int , int , int , int , int , int , int ); ( hr wr yr xr yadder xadder fh fw bw default_pos pos screen dpy -- n )
LocalExtern: XGetErrorDatabaseText int XGetErrorDatabaseText( int , int , int , int , int , int ); (( int ); ( int , int , int ); ( value_r atom fontstruct -- flag )
LocalExtern: XGetGCValues int XGetGCValues( int , int , int , int ); ( values_r valuemask gc dpy -- status )
LocalExtern: XGetIconName int XGetIconName( int , int , int ); ( icon_name-r w dpy -- status )
LocalExtern: XGetInputFocus int XGetInputFocus( int , int , int ); ( revert_to_r focus_r dpy -- r )
LocalExtern: XGetKeyboardControl int XGetKeyboardControl( int , int ); ( values_r dpy -- r )
LocalExtern: XGetPointerControl int XGetPointerControl( int , int , int , int ); ( threshold_r accel_denom_r accel_num_r dpy -- r )
LocalExtern: XGetPointerMapping int XGetPointerMapping( int , int , int ); ( nmap map_r dpy -- n )
LocalExtern: XGetScreenSaver int XGetScreenSaver( int , int , int , int , int ); ( allow_exposures_r prefer_blanking_r interval_r timeout_r dpy -- r )
LocalExtern: XGetTransientForHint int XGetTransientForHint( int , int , int ); ( prop_w_r w dpy -- status )
LocalExtern: XGrabButton int XGrabButton( int , int , int , int , int , int , int , int , int ); ( cursor confine_to keyboard_mode pointer_mode owner_events grab_window modifiers button dpy -- r )
LocalExtern: XGrabKey int XGrabKey( int , int , int , int , int , int , int , int ); ( keyboard_mode pointer_mode owner_events grab_events grab_window modifiers keycode dpy -- r )
LocalExtern: XGrabKeyboard int XGrabKeyboard( int , int , int , int , int , int ); ( time keyboard_mode pointer_mode owner_events grab_window dpy -- n )
LocalExtern: XIfEvent int XIfEvent( int , int , int , int ); ( arg predicate event_r dpy -- r )
LocalExtern: XInstallColormap int XInstallColormap( int , int ); ( colormap dpy -- r )
LocalExtern: XKeysymToKeycode int XKeysymToKeycode( int , int ); ( keysym dpy -- keycode )
LocalExtern: XKillClient int XKillClient( int , int ); ( resource dpy -- r )
\ 1 Extern: XLastKnownRequestProcessed   XLastKnownRequestProcessed      ( dpy -- u )
LocalExtern: XLookupColor int XLookupColor( int , int , int , int , int ); ( screen_def_r exact_def_r color_name colormap dpy -- status )
LocalExtern: XLowerWindow int XLowerWindow( int , int ); ( w dpy -- r )
LocalExtern: XMapSubwindows int XMapSubwindows( int , int ); ( w dpy -- r )
LocalExtern: XMaskEvent int XMaskEvent( int , int , int ); ( event_r event_mask dpy -- r )
LocalExtern: XParseColor int XParseColor( int , int , int , int ); ( exact_def_r spec colormap dpy -- status )
LocalExtern: XPeekEvent int XPeekEvent( int , int ); ( event_r dpy -- r )
LocalExtern: XPeekIfEvent int XPeekIfEvent( int , int , int , int ); ( arg predicate event_r dpy -- r )
LocalExtern: XPutBackEvent int XPutBackEvent( int , int ); ( event dpy -- r )
LocalExtern: XQueryBestCursor int XQueryBestCursor( int , int , int , int , int , int ); ( h_r w_r h w d dpy -- status )
LocalExtern: XQueryBestSize int XQueryBestSize( int , int , int , int , int , int , int ); ( h_r w_r h w which_screen class dpy -- status )
LocalExtern: XQueryBestStipple int XQueryBestStipple( int , int , int , int , int , int ); ( h_r w_r h w which_screen dpy -- status )
LocalExtern: XQueryBestTile int XQueryBestTile( int , int , int , int , int , int ); ( h_r w_r h w which_screen dpy -- status )
LocalExtern: XQueryColor int XQueryColor( int , int , int ); ( def_in_out colormap dpy -- r )
LocalExtern: XQueryColors int XQueryColors( int , int , int , int ); ( ncolors defs_in_out colormap dpy -- r )
LocalExtern: XQueryExtension int XQueryExtension( int , int , int , int , int ); ( first_error_r first_event_r major_opcode_r name dpy -- flag )
LocalExtern: XQueryKeymap int XQueryKeymap( int , int ); ( keys_r dpy -- r )
LocalExtern: XQueryTextExtents int XQueryTextExtents( int , int , int , int , int , int , int , int ); ( overall_r font_descent_r font_ascent_r direction_r nchars string font_id dpy -- r )
LocalExtern: XQueryTextExtents16 int XQueryTextExtents16( int , int , int , int , int , int , int , int ); ( overall_r font_descent_r font_ascent_r direction_r nchars string font_id dpy -- r )
LocalExtern: XQueryTree int XQueryTree( int , int , int , int , int , int ); ( nchildren_r children_r parent_r root_r w dpy -- status )
LocalExtern: XRaiseWindow int XRaiseWindow( int , int ); ( w dpy -- r )
LocalExtern: XReadBitmapFile int XReadBitmapFile( int , int , int , int , int , int , int , int ); ( y_hot_r x_hot_r bitmap_r height_r width_r filename d dpy -- n )
LocalExtern: XReadBitmapFileData int XReadBitmapFileData( int , int , int , int , int , int ); ( y_hot_r x_hot_r bitmap_r height_r width_r filename -- n )
LocalExtern: XRebindKeysym int XRebindKeysym( int , int , int , int , int , int ); ( bytes_string string mod_count list keysym dpy -- r )
LocalExtern: XRecolorCursor int XRecolorCursor( int , int , int , int ); ( bg fg cursor dpy -- r )
LocalExtern: XRemoveFromSaveSet int XRemoveFromSaveSet( int , int ); ( w dpy -- r )
LocalExtern: XRemoveHost int XRemoveHost( int , int ); ( host dpy -- r )
LocalExtern: XRemoveHosts int XRemoveHosts( int , int , int ); ( num_hosts hosts dpy -- r )
LocalExtern: XReparentWindow int XReparentWindow( int , int , int , int , int ); ( y x parent w dpy -- r )
LocalExtern: XRestackWindows int XRestackWindows( int , int , int ); ( nwindows windows dpy -- r )
LocalExtern: XRotateBuffers int XRotateBuffers( int , int ); ( rotate dpy -- r )
LocalExtern: XRotateWindowProperties int XRotateWindowProperties( int , int , int , int , int ); ( npositions num_prop properties w dpy -- r )
LocalExtern: XSetAccessControl int XSetAccessControl( int , int ); ( mode dpy -- r )
LocalExtern: XSetArcMode int XSetArcMode( int , int , int ); ( arc_mode gc dpy -- r )
LocalExtern: XSetClipRectangles int XSetClipRectangles( int , int , int , int , int , int , int ); ( ordering n rectangles clip_y_orig clip_x_orig gc dpy -- r )
LocalExtern: XSetCloseDownMode int XSetCloseDownMode( int , int ); ( close_mode dpy -- r )
LocalExtern: XSetCommand int XSetCommand( int , int , int , int ); ( argc argv w dpy -- r )
LocalExtern: XSetDashes int XSetDashes( int , int , int , int , int ); ( n dash_list dash_ofset gc dpy -- r )
LocalExtern: XSetFillRule int XSetFillRule( int , int , int ); ( fill_rule gc dpy -- r )
LocalExtern: XSetFillStyle int XSetFillStyle( int , int , int ); ( fill_style gc dpy -- r )
LocalExtern: XSetFont int XSetFont( int , int , int ); ( font gc dpy -- r )
LocalExtern: XSetFontPath int XSetFontPath( int , int , int ); ( ndirs directories dpy -- r )
LocalExtern: XSetGraphicsExposures int XSetGraphicsExposures( int , int , int ); ( graphics_exposures gc dpy -- r )
LocalExtern: XSetModifierMapping int XSetModifierMapping( int , int ); ( modmap dpy -- n )
LocalExtern: XSetPlaneMask int XSetPlaneMask( int , int , int ); ( plane_mask gc dpy -- r )
LocalExtern: XSetPointerMapping int XSetPointerMapping( int , int , int ); ( nmap map dpy -- n )
LocalExtern: XSetScreenSaver int XSetScreenSaver( int , int , int , int , int ); ( allow_exposures prefer_blanking interval timeout dpy -- r )
LocalExtern: XSetState int XSetState( int , int , int , int , int , int ); ( plane_mask function bg fg gc dpy -- r )
LocalExtern: XSetStipple int XSetStipple( int , int , int ); ( stripple gc dpy -- r )
LocalExtern: XSetSubwindowMode int XSetSubwindowMode( int , int , int ); ( subwindow_mode gc dpy -- r )
LocalExtern: XSetTSOrigin int XSetTSOrigin( int , int , int , int ); ( ts_y_orig ts_x_orig gc dpy -- r )
LocalExtern: XSetTile int XSetTile( int , int , int ); ( tile gc dpy -- )
LocalExtern: XSetWindowBackground int XSetWindowBackground( int , int , int ); ( bg_pixel w dpy -- )
LocalExtern: XSetWindowBackgroundPixmap int XSetWindowBackgroundPixmap( int , int , int ); ( bg_pixmap w dpy -- r )
LocalExtern: XSetWindowBorder int XSetWindowBorder( int , int , int ); ( border_pixel w dpy -- r )
LocalExtern: XSetWindowBorderPixmap int XSetWindowBorderPixmap( int , int , int ); ( border_pixmap w dpy -- r )
LocalExtern: XSetWindowBorderWidth int XSetWindowBorderWidth( int , int , int ); ( width w dpy -- r )
LocalExtern: XSetWindowColormap int XSetWindowColormap( int , int , int ); ( colormap w dpy -- r )
LocalExtern: XStoreBuffer int XStoreBuffer( int , int , int , int ); ( buffer nbytes bytes dpy -- r )
LocalExtern: XStoreColor int XStoreColor( int , int , int ); ( color colormap dpy -- r )
LocalExtern: XStoreColors int XStoreColors( int , int , int , int ); ( ncolors color colormap dpy -- r )
LocalExtern: XStoreNamedColor int XStoreNamedColor( int , int , int , int , int ); ( flags pixel color colormap dpy -- r )
LocalExtern: XTextWidth int XTextWidth( int , int , int ); ( count string font_struct -- n )
LocalExtern: XTextWidth16 int XTextWidth16( int , int , int ); ( count string font_struct -- n )
LocalExtern: XTranslateCoordinates int XTranslateCoordinates( int , int , int , int , int , int , int , int ); ( child_r dest_y_r dest_x_r src_y src_x dest_w src_w dpy -- flag )
LocalExtern: XUndefineCursor int XUndefineCursor( int , int ); ( w dpy -- r )
LocalExtern: XUngrabButton int XUngrabButton( int , int , int , int ); ( grab_window modifiers button dpy -- r )
LocalExtern: XUngrabKey int XUngrabKey( int , int , int , int ); ( grab_window modifiers keycode dpy -- r )
LocalExtern: XUngrabKeyboard int XUngrabKeyboard( int , int ); ( time dpy -- r )
LocalExtern: XUninstallColormap int XUninstallColormap( int , int ); ( colormap dpy -- r )
LocalExtern: XUnloadFont int XUnloadFont( int , int ); ( font dpy -- r )
LocalExtern: XUnmapSubwindows int XUnmapSubwindows( int , int ); ( w dpy -- r )
LocalExtern: XWriteBitmapFile int XWriteBitmapFile( int , int , int , int , int , int , int ); ( y_hot x_hot h w bitmap filename dpy -- r )
LocalExtern: XOpenOM int XOpenOM( int , int , int , int ); ( res_class res_name rdb dpy -- XOM )
LocalExtern: XFreeFontSet int XFreeFontSet( int , int ); ( fontset dpy -- r )
LocalExtern: XFontsOfFontSet int XFontsOfFontSet( int , int , int ); ( font_name_list font_struct_list font_set -- n )
LocalExtern: XmbTextEscapement int XmbTextEscapement( int , int , int ); ( bytes_text text fontset -- n )
LocalExtern: XwcTextEscapement int XwcTextEscapement( int , int , int ); ( num_wchars text fontset -- n )
LocalExtern: XmbTextExtents int XmbTextExtents( int , int , int , int , int ); ( overall_logical_r overall_ink_r bytes_text text fontset -- n )
LocalExtern: XwcTextExtents int XwcTextExtents( int , int , int , int , int ); ( overall_logical_r overall_ink_r num_wchars text fontset -- n )
LocalExtern: XmbTextPerCharExtents int XmbTextPerCharExtents( int , int , int , int , int , int , int , int , int ); ( overal_logical_r overall_ink_r num_chars buffer_size logical_extents_buffer ink_extents_buffer bytes_text text fontset -- status )
LocalExtern: XwcTextPerCharExtents int XwcTextPerCharExtents( int , int , int , int , int , int , int , int , int ); ( overal_logical_r overall_ink_r num_chars buffer_size logical_extents_buffer ink_extents_buffer num_wchars text fontset -- status )
LocalExtern: XmbDrawText int XmbDrawText( int , int , int , int , int , int , int ); ( nitems text_items y x gc d dpy -- r )
LocalExtern: XwcDrawText int XwcDrawText( int , int , int , int , int , int , int ); ( nitems text_items y x gc d dpy -- r )
LocalExtern: XmbDrawString int XmbDrawString( int , int , int , int , int , int , int , int ); ( bytes_text text y x gc fontset d dpy -- r )
LocalExtern: XwcDrawString int XwcDrawString( int , int , int , int , int , int , int , int ); ( num_wchars text y x gc fontset d dpy -- r )
LocalExtern: XmbDrawImageString int XmbDrawImageString( int , int , int , int , int , int , int , int ); ( bytes_text text y x gc fontset d dpy -- r )
LocalExtern: XwcDrawImageString int XwcDrawImageString( int , int , int , int , int , int , int , int ); ( num_wchars text y x gc fontset d dpy -- r )
LocalExtern: XGetICValues_1 int XGetICValues( int , int , int , int ); ( ... ic -- string )
LocalExtern: XGetICValues_2 int XGetICValues( int , int , int , int , int , int ); ( ... ic -- string )
LocalExtern: XGetICValues_3 int XGetICValues( int , int , int , int , int , int , int , int ); ( ... ic -- string )
LocalExtern: XmbLookupString int XmbLookupString( int , int , int , int , int , int ); ( status_r keysym_r bytes_buffer buffer_r event ic -- n )
LocalExtern: XwcLookupString int XwcLookupString( int , int , int , int , int , int ); ( status_r keysym_r wchars_buffer buffer_r event ic -- n )
LocalExtern: XRegisterIMInstantiateCallback int XRegisterIMInstantiateCallback( int , int , int , int , int , int ); ( client_data callback res_class res_name rdb dpy -- flag )
LocalExtern: XUnregisterIMInstantiateCallbac int XUnregisterIMInstantiateCallbac( int , int , int , int , int , int ); ( client_data callback res_class res_name rdb dpy -- flag )
LocalExtern: XInternalConnectionNumbers int XInternalConnectionNumbers( int , int , int ); ( count_r fd_r dpy -- status )
LocalExtern: XProcessInternalConnection int XProcessInternalConnection( int , int ); ( fd dpy -- r )
LocalExtern: XAddConnectionWatch int XAddConnectionWatch( int , int , int ); ( client_data callback dpy -- status )
LocalExtern: XRemoveConnectionWatch int XRemoveConnectionWatch( int , int , int ); ( client_data callback dpy -- status )

\ Xutil.h
\ The following functions are not performed by the XServer, but in Xlib.

LocalExtern: XClipBox int XClipBox( int , int ); ( rect reg -- r )
LocalExtern: XDeleteContext int XDeleteContext( int , int , int ); ( context rid dpy -- n )
LocalExtern: XEqualRegion int XEqualRegion( int , int ); ( r1 r2 -- r )
LocalExtern: XFindContext int XFindContext( int , int , int , int ); ( data_r context rid dpy -- n )
LocalExtern: XGetClassHint int XGetClassHint( int , int , int ); ( class_hints_r w dpy -- status )
LocalExtern: XGetIconSizes int XGetIconSizes( int , int , int , int ); ( count_r size_list_r w dpy -- status )
LocalExtern: XGetNormalHints int XGetNormalHints( int , int , int ); ( hints_r w dpy -- status )
LocalExtern: XGetRGBColormaps int XGetRGBColormaps( int , int , int , int , int ); ( prop count_r stdcmap_r w dpy -- status )
LocalExtern: XGetSizeHints int XGetSizeHints( int , int , int , int ); ( prop hints_r w dpy -- status )
LocalExtern: XGetStandardColormap int XGetStandardColormap( int , int , int , int ); ( prop colormap_r w dpy -- status )
LocalExtern: XGetTextProperty int XGetTextProperty( int , int , int , int ); ( prop text_prop_r w dpy -- status )
LocalExtern: XGetWMClientMachine int XGetWMClientMachine( int , int , int ); ( text_prop_r w dpy -- status )
LocalExtern: XGetWMHints int XGetWMHints( int , int ); ( w dpy -- WMHints* )
LocalExtern: XGetWMIconName int XGetWMIconName( int , int , int ); ( text_prop_r w dpy -- status )
LocalExtern: XGetWMName int XGetWMName( int , int , int ); ( text_prop_r w dpy -- status )
LocalExtern: XGetWMNormalHints int XGetWMNormalHints( int , int , int , int ); ( supplied_r hints_r w dpy -- status )
LocalExtern: XGetWMSizeHints int XGetWMSizeHints( int , int , int , int , int ); ( prop supplied_r hints_r w dpy -- status )
LocalExtern: XGetZoomHints int XGetZoomHints( int , int , int ); ( zhints_r w dpy -- status )
LocalExtern: XConvertCase int XConvertCase( int , int , int ); ( upper* lower* sym -- r )
LocalExtern: XMatchVisualInfo int XMatchVisualInfo( int , int , int , int , int ); ( vinfo_r class depth screen dpy -- status )
LocalExtern: XOffsetRegion int XOffsetRegion( int , int , int ); ( dy dx reg -- r )
LocalExtern: XPointInRegion int XPointInRegion( int , int , int ); ( y x reg -- flag )
LocalExtern: XPolygonRegion int XPolygonRegion( int , int , int ); ( fill_rile n points -- reg )
LocalExtern: XRectInRegion int XRectInRegion( int , int , int , int , int ); ( h w y x reg -- n )
LocalExtern: XSaveContext int XSaveContext( int , int , int , int ); ( data context rid dpy -- n )
LocalExtern: XSetIconSizes int XSetIconSizes( int , int , int , int ); ( count size_list w dpy -- r )
LocalExtern: XSetNormalHints int XSetNormalHints( int , int , int ); ( hints w dpy -- r )
LocalExtern: XSetRGBColormaps int XSetRGBColormaps( int , int , int , int , int ); ( prop count stdcmaps w dpy -- r )
LocalExtern: XSetSizeHints int XSetSizeHints( int , int , int , int ); ( prop hints w dpy -- r )
LocalExtern: XSetStandardProperties int XSetStandardProperties( int , int , int , int , int , int , int , int ); ( sizehints argc argv icon_pixmap icon_name window_name w dpy -- r )
LocalExtern: XSetWMClientMachine int XSetWMClientMachine( int , int , int ); ( text_prop w dpy -- r )
LocalExtern: XSetWMIconName int XSetWMIconName( int , int , int ); ( text_prop w dpy -- r )
LocalExtern: XSetWMName int XSetWMName( int , int , int ); ( text_prop w dpy -- r )
LocalExtern: XSetWMProperties int XSetWMProperties( int , int , int , int , int , int , int , int , int ); ( class_hints wm_hints normal_hints argc argv icon_name window_name w dpy -- r )
LocalExtern: XmbSetWMProperties int XmbSetWMProperties( int , int , int , int , int , int , int , int , int ); ( class_hints wm_hints normal_hints argc argv icon_name window_name w dpy -- r )
LocalExtern: XSetWMSizeHints int XSetWMSizeHints( int , int , int , int ); ( prop hints w dpy -- r )
LocalExtern: XSetStandardColormap int XSetStandardColormap( int , int , int , int ); ( prop colormap w dpy -- r )
LocalExtern: XSetZoomHints int XSetZoomHints( int , int , int ); ( zhints w dpy -- r )
LocalExtern: XShrinkRegion int XShrinkRegion( int , int , int ); ( dy dx reg -- r )
LocalExtern: XStringListToTextProperty int XStringListToTextProperty( int , int , int ); ( text_prop_r count list -- status )
LocalExtern: XSubtractRegion int XSubtractRegion( int , int , int ); ( dr_r srb sra -- r )
LocalExtern: XmbTextListToTextProperty int XmbTextListToTextProperty( int , int , int , int , int ); ( text_prop_r style count list dpy -- n )
LocalExtern: XwcTextListToTextProperty int XwcTextListToTextProperty( int , int , int , int , int ); ( text_prop_r style count list dpy -- n )
LocalExtern: XTextPropertyToStringList int XTextPropertyToStringList( int , int , int ); ( count_r list_r text_prop -- status )
LocalExtern: XmbTextPropertyToTextList int XmbTextPropertyToTextList( int , int , int , int ); ( count_r list_r text_prop dpy -- n )
LocalExtern: XwcTextPropertyToTextList int XwcTextPropertyToTextList( int , int , int , int ); ( count_r list_r text_prop dpy -- n )
LocalExtern: XUnionRegion int XUnionRegion( int , int , int ); ( dr_r srb sra -- r )
LocalExtern: XWMGeometry int XWMGeometry( int , int , int , int , int , int , int , int , int , int ); ( gravity_r h_r w_r y_r x_r hints border_w default_geometry user_geometry screen_nr dpy -- n )
LocalExtern: XXorRegion int XXorRegion( int , int , int ); ( dr_r srb sra -- r )

\ Memory Management
LocalExtern: XrmStringToQuarkList int XrmStringToQuarkList( int , int ); ( quarks string -- r )
LocalExtern: XrmStringToBindingQuarkList int XrmStringToBindingQuarkList( int , int , int ); ( quarks bindings string -- r )

struct{
    cell size
    cell addr
} XrmValue

LocalExtern: XrmQPutResource int XrmQPutResource( int , int , int , int , int ); ( value type quarks bindings dbase -- r )
LocalExtern: XrmPutResource int XrmPutResource( int , int , int , int ); ( value type spec dbase -- r )
LocalExtern: XrmQPutStringResource int XrmQPutStringResource( int , int , int , int ); ( value quarks bindings dbase -- r )
LocalExtern: XrmPutStringResource int XrmPutStringResource( int , int , int ); ( value spec dbase -- r )
LocalExtern: XrmPutLineResource int XrmPutLineResource( int , int ); ( line dbase -- r )
LocalExtern: XrmQGetResource int XrmQGetResource( int , int , int , int , int ); ( value_r quark_t_r quark_c quark_n dbase -- r )
LocalExtern: XrmGetResource int XrmGetResource( int , int , int , int , int ); ( value_r str_t_r str_c str_n dbase -- flag )
LocalExtern: XrmQGetSearchList int XrmQGetSearchList( int , int , int , int , int ); ( list_len list_r classes names dbase -- flag )
LocalExtern: XrmQGetSearchResource int XrmQGetSearchResource( int , int , int , int , int ); ( value_r type_r class name list -- flag )
LocalExtern: XrmSetDatabase int XrmSetDatabase( int , int ); ( dbase dpy -- r )
LocalExtern: XrmCombineFileDatabase int XrmCombineFileDatabase( int , int , int ); ( flag dbase* filename -- status )
LocalExtern: XrmPutFileDatabase int XrmPutFileDatabase( int , int ); ( string dbase -- r )
LocalExtern: XrmMergeDatabases int XrmMergeDatabases( int , int ); ( dbase* dbase -- r )
LocalExtern: XrmCombineDatabase int XrmCombineDatabase( int , int , int ); ( flag dbase* dbase )
LocalExtern: XrmEnumerateDatabase int XrmEnumerateDatabase( int , int , int , int , int , int ); ( closure callback mode class_prefix name_prefix db -- flag )
LocalExtern: XrmParseCommand int XrmParseCommand( int , int , int , int , int , int ); ( argv_io argc_io name table-count table dbase -- r )

\ X extensions

LocalExtern: XShmPutImage int XShmPutImage( int , int , int , int , int , int , int , int , int , int , int ); ( send_event h w dy dx sy sx im gc win dpy -- status )

base !

include Xstring.fs

previous definitions
